[AN] feat: 랭크 path api 목서버 구현
woowacourse-teams/2023-naaga pull request #117
Opened 2023-07-31 12:01 UTC by hyunji1203

## 📌 관련 이슈
- closed: #113 

## 🛠️ 작업 내용
PR에서 작업한 주요 내용을 적어주세요.
- [X] 랭킹 path api 목서버 제작

## ⏳ 작업 시간
추정 시간: 2h  
실제 시간: 1h

2023-07-31 12:20 UTC, krrong requested changes
정말 빨리 구현했네요..! 저도 열심히 할게요!!

2023-07-31 12:20 UTC, krrong commented on android/app/src/main/java/com/now/naaga/RankMockWeb.kt
> +        thread.join()
join이 필요한 것이 맞나요?

2023-07-31 12:20 UTC, krrong commented on android/app/src/main/java/com/now/naaga/RankMockWeb.kt
> +                                val order = parameters["order"]?.toIntOrNull()
왜 `toIntOrNull`이 사용되나요?

2023-07-31 21:44 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/RankMockWeb.kt
> +        thread.join()
목 서버의 url이 만들어지길 기다린 후에 다 만들어지면 그때서야 retrofitBuilder에 url이 들어가야 한다 생각해 `join`을 사용했습니다!
만일 `join`을 쓰지 않는다면 url 생성이 다 되지 않았는데 builder가 먼저 service를 생성해버리면 들어가야할 url의 값이 비게 되어 오류가 터지지 않을까 예상합니다! 이에 대한 크롱 생각도 궁금해요!!

2023-08-01 03:21 UTC, krrong commented on android/app/src/main/java/com/now/naaga/RankMockWeb.kt
> +        thread.join()
그럴수도 있겠어요! 
저는 startWebServer()라는 메서드를 만들어서 뽀또가 만들어둔 서버를 시작하는 코드를 넣어두었어요. 그리고 이것을 repository에 init{} 블럭을 추가하고 그 안에서 실행하도록 했는데요. repository가 만들어질 때 서버의 실행이 선행되었던 것 같아요.
repository의 코드 수정 없이 테스트 하기 위해서는 뽀또 방법이 더 좋을 것 같네요! 답변 감사해요!

2023-08-01 04:09 UTC, merged