[AN] feat: RankActivity 구현
woowacourse-teams/2023-naaga pull request #119
Opened 2023-07-31 16:02 UTC by hyunji1203

## 📌 관련 이슈
- closed: #66 

## 🛠️ 작업 내용
- [ ] RankActivity 뷰 구현
- [ ] 리사이클러뷰 어댑터 연결
- [ ] 뒤로가기 버튼 추가
![랭킹화면](https://github.com/woowacourse-teams/2023-naaga/assets/83613106/4019c8f5-eada-4bfd-af8f-8f8d0ca9fc91)

## 🎯 리뷰 포인트
최대한 데이터 바인딩을 통해 데이터들이 뷰에 보여지도록 구현하였습니다. 그리고 리사이클러뷰를 ListAdapter를 활용해 구현하였는데, 이 두가지 부분들을 주의 깊게 봐주시면 감사하겠습니다.

## ⏳ 작업 시간
추정 시간:  1h 30m 
실제 시간:  3h 
이유: ListAdapter에 대해 깊이 알아보느라 시간이 좀 걸렸고, 거기가다 중간에 UI 디자인 변경으로 인해 생각보다 시간이 많이 걸렸습니다.

2023-07-31 16:44 UTC, krrong requested changes
그림자 관련해서 남긴 코멘트 참고하시면 좋을 것 같아요 👍

2023-07-31 16:44 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
> +        }
👍

2023-07-31 16:44 UTC, krrong commented on android/app/src/main/res/drawable/rect_radius_small_shadow.xml
> +<?xml version="1.0" encoding="utf-8"?>
아마 뷰에 그림자를 넣으려고 만든 것처럼 보여요!
저도 그림자를 어떻게 넣을까 고민을 많이 했었는데 뷰에 `elevation`이라는 attribute가 있더라구요. 이것을 활용하면 아래처럼 더 간단하게 구현이 가능할 수도 있을 것 같아요!

```
android:background="@drawable/rect_white_radius_small"
android:backgroundTint="@color/넣을 색상"
android:elevation="4dp"
```

참고로 뷰 주변에 어느정도의 여유공간이 있어야 그림자가 더 잘보인답니다!

2023-07-31 16:44 UTC, krrong commented on android/app/src/main/res/layout/activity_rank.xml
> +            android:id="@+id/d_rank_bottom"
이 친구의 이름이 d로 시작하는 이유가 있을까요?

2023-07-31 21:07 UTC, hyunji1203 commented on android/app/src/main/res/layout/activity_rank.xml
> +            android:id="@+id/d_rank_bottom"
원래 초반 만들 때는 divider component 였었는데 중간에 색상을 진하게 하고 싶어서 해당 divider 속성을 지워버리게 되어서 view에 d 네이밍이 붙여지게 된 상황이 된 것 같습니다! 수정할께요~!

2023-07-31 21:40 UTC, hyunji1203 commented on android/app/src/main/res/drawable/rect_radius_small_shadow.xml
> +<?xml version="1.0" encoding="utf-8"?>
그냥 elevation 속성을 적용시키면 적용이 안되길래 뷰 주변에 여유공간을 만들고자 constraintLayout인 부모뷰를 하나 생성해 부모뷰에 해당 속성들을 적어 주고  
```
android:paddingVertical="8dp"
android:clipToPadding="false"
```
자식 뷰에 
```
android:background="@drawable/rect_radius_small"
android:backgroundTint="@color/main_pink"
android:elevation="4dp"
```
위와 같은 속성들을 넣었습니다. 하지만 그림자가 적용이 잘 안되는 것 같습니다.. 주변의 여유공간도 만들고 배경색도 있는데 왜 안생길까요..? 근데 또 너무 같은 핑크색 뷰를 계속 보다보니까, 알고보니 이미 그림자가 생긴건데 제가 못보고 있는 건가 하는 생각도 들고 있습니다..... 지금 그림자가 생겼나요? 안 생겼다면 어떻게 해야할까요?🥹

2023-08-01 00:47 UTC, briandr97 commented on android/app/src/main/res/drawable/rect_radius_small_shadow.xml
> +<?xml version="1.0" encoding="utf-8"?>
tint에 색을 넣는 것으로는 배경색이 생기지 않습니다.
background에 `rect_radius_small` 대신 `rect_white_radius_small`을 넣고 tint는 그대로 두면 색은 tint 색으로 먹고 그림자도 생길겁니다!

2023-08-01 04:47 UTC, krrong approved these changes

2023-08-01 04:48 UTC, merged