[AN] feat: 카메라로 찍은 사진을 뷰에 띄우고 Uri 추출기능 구현
woowacourse-teams/2023-naaga pull request #120
Opened 2023-07-31 17:04 UTC by krrong

## 📌 관련 이슈
- closed: #69 

## 🛠️ 작업 내용
- [x] 카메라로 찍은 사진을 뷰에 띄우는 기능 구현
- [x] 카메라로 찍은 사진의 Uri 추출 기능 구현

## ⏳ 작업 시간
추정 시간: 1h 30m  
실제 시간: 2h

2023-07-31 18:23 UTC, briandr97 requested changes
고생하셨습니다. 어떻게 하는지 배워갑니다.
클릭리스너 내의 함수만 분리하면 좋을 것 같습니다!

2023-07-31 18:23 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +    ) { bitmap ->
오 이렇게 받아오는군요~!

2023-07-31 18:23 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +        }
클릭리스너 내의 로직들을 함수로 감싸서 함수명으로 어떤 일을 하는지 나타내면 좋을 것 같습니다! (이하 동문)

2023-07-31 18:23 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +        }
요 친구는 일단 지울까용..??

2023-07-31 18:23 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +        return null
비트맵을 uri로 변환하는 코드군요! 근데 혹시 어디에 쓰이나요? 멀티파트로 변환할 때 쓰이나요?

2023-08-01 03:06 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +        }
잘못등록 되어있던 리스너를 지우고 남겨뒀었네요! 지웠어요🙃

2023-08-01 06:08 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +        return null
Uri를 통해 File로 변환하고 File을 멀티파트로 변환하는데요, 결과적으로 멀티파트를 위한 것이 맞아요!

2023-08-01 06:08 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +        }
잘못 등록되어있던 리스너라 삭제했습니다 🙃

2023-08-01 06:08 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +        }
반영했어요!🙃

2023-08-01 07:02 UTC, briandr97 approved these changes
고생하셨습니다. 모르겠는 부분이 있어서 질문 하나 남겼습니다!

2023-08-01 07:02 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
>      }
이 친구는 어떤 역할을 하는 친구인가요?

2023-08-01 07:02 UTC, merged

2023-08-01 07:03 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
>      }
소수점 아래 4자리까지 만들어주는 역할을 합니다🙃