[AN] feat: 인게임 화면 기능 및 서버통신 구현
woowacourse-teams/2023-naaga pull request #149
Opened 2023-08-02 07:33 UTC by briandr97

## 📌 관련 이슈
- closed: #126 

## 🛠️ 작업 내용
- [x] 게임 포기
- [x] 게임 종료(도착)
- [x] 힌트 생성
- [x] 힌트 표시
- [x] 네이버 맵 관련 코드를 액티비티에서 분리
- [x] 다이얼로그 재사용 가능하도록 분리
 
## 🎯 리뷰 포인트
양이 좀 많습니다..

## ⏳ 작업 시간
추정 시간:   6h
실제 시간:   18h
자꾸 뭘 할려고해서 오래걸림... 그냥 박았으면 이렇게 오래 안걸렸는데..

2023-08-02 08:45 UTC, krrong requested changes
정말 고생많았어요!! 구현을 잘 한 것 같아서 많은 코멘트가 있지는 않아요!

리뷰하는 입장에서 작은 바람이 있다면 많은 내용이 한 번에 올라왔기 때문에 어디에 사용되는 클래스인지 한 번에 알아보기 어려울 것 같은 친구들에 대해 설명을 써주었으면 어떨까 싶어요! 그러면 리뷰하는 시간이 많이 단축될 것 같습니다 ㅎㅎ

추가로 featureList 파일이 있는데 필요하다고 판단하여 남겨둔 것일까요?

구현하느라 정말 고생했어요🙃

2023-08-02 08:45 UTC, krrong commented on android/domain/src/main/java/com/now/domain/model/Place.kt
> +    fun getDistance(other: Coordinate): Int {
Destination에 있는 기능이 Place로 넘어오고 확장된 것 같아요. Destination의 코드는 삭제하고 테스트 코드도 구성하면 좋을 것 같아요!

2023-08-02 08:45 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/DisposableLiveData.kt
> +            if (isFirst.compareAndSet(true, false)) {
굉장히 좋은 함수군요..?

2023-08-02 08:45 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/DisposableLiveData.kt
> +class DisposableLiveData<T> : MutableLiveData<T>() {
이 클래스를 만든 이유를 설명해주실 수 있을까요?

2023-08-02 08:45 UTC, krrong commented on android/app/src/main/res/layout/activity_on_adventure.xml
> +        <com.naver.maps.map.widget.CompassView
나침반을 뷰에 보여주는 것 같아요! UI setting을 코드로 빼지 않은 이유가 있나요??

2023-08-02 08:45 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
> +            }
ViewModelFactory를 이렇게 선언한 이유가 무엇일까요?

2023-08-02 09:09 UTC, hyunji1203 requested changes
빅스 진짜 너무 고생 많았어요! 코드 양 부터 코드의 깊이까지 18시간 걸릴만 했네요..
myCoordinate랑 Destination 라이브데이터들을 싱글 이벤트 라이브 데이터로 커스텀한게 인상에 남습니다... 
목서버 말고 실제 서버로 테스트해서 실제로 작동하는 모습이 너무 궁금해요!
진짜 너무 고생 많았어요~

2023-08-02 09:09 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
> +            val intent = Intent(this, AdventureResultActivity::class.java)
해당 액티비티에서 getIntent 함수 써서 받아오면 좋을 것 같아요~

2023-08-02 09:09 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    val startCoordinate = DisposableLiveData<Coordinate>()
👍 너무 좋은 구조네요..

2023-08-02 09:09 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +        class ViewModelFactory(private val adventureRepository2: AdventureRepository2) : ViewModelProvider.Factory {
ViewModelFactory class 개별 파일을 삭제하고 companion object에 넣은 이유가 뭔가요? 궁금해요!

2023-08-02 17:06 UTC, briandr97 commented on android/domain/src/main/java/com/now/domain/model/Place.kt
> +    fun getDistance(other: Coordinate): Int {
아 이 부분은 혹시 이전 도메인 객체가 사용되는 코드가 있을까봐 Destination을 남겨두었습니다. 테스트는 깜빡했네요.
사용하지 않는 2차 데모용 파일 삭제는 새로 이슈 파서 진행하도록 하겠습니다!

2023-08-02 17:06 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/DisposableLiveData.kt
> +            if (isFirst.compareAndSet(true, false)) {
compareAndSet 말씀이신가요?

2023-08-02 17:13 UTC, briandr97 commented on android/app/src/main/res/layout/activity_on_adventure.xml
> +        <com.naver.maps.map.widget.CompassView
코드단에서 uiSetting을 이용하여 활성화를 시킬 수 있습니다만
화면에서 어디에 표시될 지를 직접 지정해주기 위해 뷰에 표시하였습니다!

2023-08-02 17:15 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
> +            }
해당 뷰모델을 생성하는 팩토리이므로 해당 뷰모델과 같은 파일에 위치하는 것이 맞다고 생각하였습니다.
또한 이 것과는 조금 다르게 생겼지만 범용적으로 사용되는 팩토리 메서드 또한 해당 클래스의 동반 객체 (자바라면 스태틱 메서드)에 존재하기 때문입니다!

2023-08-02 17:16 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +        class ViewModelFactory(private val adventureRepository2: AdventureRepository2) : ViewModelProvider.Factory {
[위에 같은 질문이 있어 답을 달았습니다!](https://github.com/woowacourse-teams/2023-naaga/pull/149#discussion_r1282206293)

2023-08-02 17:16 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    val startCoordinate = DisposableLiveData<Coordinate>()
벌써 이해가 끝나셨군요

2023-08-02 17:20 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
> +            val intent = Intent(this, AdventureResultActivity::class.java)
수정하였습니다! 아까 작업할 때는 getIntent함수가 없었던 것 같은데 dev pull 받고 나니 생겼나봐요!

2023-08-02 17:26 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/DisposableLiveData.kt
> +class DisposableLiveData<T> : MutableLiveData<T>() {
현재 두 군데서 사용하고 있는데 한 가지를 예시로 설명드리겠습니다.

저희가 게임 시작 api를 요청하려면 유저의 시작 위치를 함께 보내야합니다.
이전엔 딜레이와 lastPosition을 이용해서 첫 위치를 잡았지만 위험성을 인지하여 바꾸기로 했습니다.
그래서 여러 방안을 고안하다 나온 결론입니다.

startCoordinate라는 라이브 데이터를 두고 locationChangeListener 내부에서 startCoordinate의 값을 지정해줍니다.
그리고 startCoordinate를 옵저빙하며 notify가 오면 시작 위치를 담아 게임 시작 api를 호출합니다.

하지만 여기서 문제가 발생합니다.
locationChangeListener는 위치 변화가 발생할 때마다 불리기 때문이죠.
게임 시작 api 요청은 처음 한 번만 호출해야하는데 리스너가 불릴 때마다 호출하게 되는 것입니다.

그래서 LiveData를 조금 고쳐서 처음 한번 setValue가 될 때만 notify를 주도록 했습니다. 그 이후로는 notify하지 않습니다.
그래서 startCoordinate는 locationChangeListener로 인해 계속 초기화 되지만 옵저버들에게는 더 이상 notify하지 않습니다.

즉 처음인지를 판단하는 플래그를 라이브데이터 내부에 넣었다고 생각하시면 될 것 같습니다.

이게 최선인지는 사실 잘 모르겠습니다.
처음 한번을 위한 변수가 있는게 저도 별로라고 느껴집니다.

향후 더 좋은 방법이 있는지 고민해보겠습니다.

2023-08-03 01:08 UTC, hyunji1203 approved these changes
👍

2023-08-03 01:10 UTC, krrong commented on android/app/src/main/res/layout/activity_on_adventure.xml
> +        <com.naver.maps.map.widget.CompassView
그렇게도 지정할 수 있군요!

2023-08-03 01:11 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
> +            }
그렇담 다른 뷰모델들의 팩토리들도 동반객체에 옮기는 것도 좋겠네요!

2023-08-03 01:17 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/DisposableLiveData.kt
> +class DisposableLiveData<T> : MutableLiveData<T>() {
처음에 고민했던 것보다 더 나은 형태로 발전한 것 같네요! 최선인가는 저도 확신하지 못하겠지만 충분히 좋은 형태인 것 같아요🙃

2023-08-03 01:18 UTC, merged