feat: 장소 업로드 기능 구현
woowacourse-teams/2023-naaga pull request #301
Opened 2023-09-06 11:07 UTC by krrong

## 📌 관련 이슈
- closed: #286 

## 🛠️ 작업 내용
장소 추가 기능 구현
- [x] Part로 보내던 데이터를 PartMap으로 변경한다.
- [x] 사진과 다른 정보들을 함께 업로드 하는 기능을 구현한다.
- [x] 핸들링 할 에러를 뷰모델에서 결정하고 액티비티에서 적절하게 핸들링한다. 

## 🎯 리뷰 포인트
### PlaceService
`@PartMap` 애노테이션을 통해 여러 개의 RequestBody를 묶어 한번에 보낼 수 있도록 기능을 구현했어요. 이런 방식으로 진행하면 POST 요청에서 서버에 보내야 하는 값이 하나 더 추가되더라도 PartMap에 추가만 해주면 되기 때문에 변경에 유연하다고 느껴집니다.

### DefaultPlaceRepository
String을 RequestBody로 바꿔 HashMap에 추가하여 PlaceService의 registerPlace 함수의 인자로 넣어줘요.  
이 때 PlaceService의 PartMap의 자료형을 Map으로 두고 DefaultPlaceRepository에서는 HashMap에 넣어줘서 보내니 아래와 같은 에러가 발생하더라구요. 그래서 HashMap으로 수정해주었습니다.
![image](https://github.com/woowacourse-teams/2023-naaga/assets/84285337/a152bc4f-cd61-4f72-9d47-34b97e60b215)

### UploadViewModel
DataThrowable로 반환된 예외 중 인증관련(200번대 에러 코드)를 잡는 UniversalThrowable과 장소관련(500번대 에러 코드)를 잡는 PlaceThrowable만을 잡아 핸들링 하도록 구현했어요.
205번 에러 : 요청 바디 값이 잘못 된 경우
215번 에러 : 사진 저장에서 문제가 생긴 경우
505번 에러 : 주변에 이미 저장된 장소가 있는 경우

### UploadActivity
위에서 잡은 예외들의 에러코드에 따라 적절한 메시지를 토스트로 띄워주도록 구현했어요.

### 포인트
- 적절한 에러를 적절한 방법으로 핸들링 했다고 생각하시는지 궁금합니다. 더 좋은 핸들링 방법이 있을 것 같기도 해서요!

## ⏳ 작업 시간
추정 시간: 1h  
실제 시간: 1h 30m  

PR을 자세하게 적으려고 좀 노력해서 시간이 조금 더 걸린 것 같아요.  
이번 회의 이후로 PR을 최대한 자세히 적자고 했으니 코드 리뷰 외에도 PR 내용에 대해서도 리뷰해주면 좋을 것 같아요! (너무 자세하다 혹은 너무 내용이 적다 등도 OK)

2023-09-07 07:39 UTC, hyunji1203 requested changes
크rrrrr롱 업로드 기능 구현하느라 고생많았어요!
우선 먼저 크롱이 질문한 에러 핸들링에 관해서, 전 크롱이 해놓은 방식이 적절한 방식인 것 같아 이대로 핸들링 진행해도 괜찮다고 생각합니다!
전체적으로 구현 잘해주셔서 크게 수정할 건 안보이네요!
자잘구리하게 리팩토링 할 만한 것들이나 궁금한 부분과 관련해 리뷰 남겼습니다~!

2023-09-07 07:39 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
> +    private val _successUpload = MutableLiveData<Boolean>()
성공 여부를 확인하는 해당 라이브 데이터는 값 변경이 한번만 이뤄질 것 같아서, 현재 만들어져 있는 DisposableLiveData 타입으로 바뀌어도 좋을 것 같아요! 크롱의 생각은 어떤가요?
(의견 제시 일 뿐 수정 요청은 아닙니다!)

2023-09-07 07:39 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
> +        @PartMap postData: HashMap<String, RequestBody>,
이 부분 덕분에, `@JvmSuppressWildcards`를 사용하면 해결된다는 사실을 알게 되어 좋았습니다!
이와 관련해서 아까 얘기 나눴던 부분들 말고 다른 부분들을 알게 되면 또 말씀드릴게요!

2023-09-07 07:39 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
> +        val nameRequestBody = name.toRequestBody("text/plain".toMediaTypeOrNull())
이런 식으로 바로 해당 값을 
 `postData["@@"] = name.toRequestBody("text/plain".toMediaTypeOrNull())`
 넣어 주지 않고 ,
하나하나 변수에 저장 후 그 후에 넣어주신 이유가 있나요?

2023-09-07 07:39 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
> +                shortToast("모든 정보를 입력해주세요.")
Strings로 빼주면 좋을 것 같아요!

2023-09-07 13:46 UTC, krrong commented on android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
> +        @PartMap postData: HashMap<String, RequestBody>,
좋아요! 저도 추가로 알게 되는 것이 있다면 공유하도록 하겠습니다 🤠

2023-09-07 13:47 UTC, krrong commented on android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
> +        val nameRequestBody = name.toRequestBody("text/plain".toMediaTypeOrNull())
좀 더 가독성 좋게 만들려고 했는데 변수에 저장하지 않고 바로 넣어주는 것이 더 가독성이 좋아보이나요?

2023-09-07 13:48 UTC, krrong commented on android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
> +        val nameRequestBody = name.toRequestBody("text/plain".toMediaTypeOrNull())
좀 더 가독성 좋다고 느껴져서 그렇게 진행했는데요, 변수에 저장하지 않고 바로 넣어주는 것이 더 가독성이 좋아보이나요?

2023-09-08 01:03 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
> +    private val _successUpload = MutableLiveData<Boolean>()
Pn 룰 적용하면 좋을 것 같아요!(🙏)

뽀또의 의견을 듣고 조금 생각해봤는데요, 현재 액티비티에서 _successUpload 변수가 true로 변경되면 바로 현재 뷰를 finish 하고 있어요. 그래서 이 데이터를 MutableLiveData를 사용하든, DisposableLiveData을 사용하든 크게 상관이 없을 것 같다는 생각을 했어요.  
만약 finish 시키는 것이 아니고 다른 행동을 한다면 DisposableLiveData를 사용하는 것이 더 좋을 것 같아요!  

그래서 뽀또와 상의하고 싶은 것이 생겼어요. 현재 상황에서 업로드 성공 시 유저에게 제공하는 정보 없이 finish를 시키고 있는데 이 방법 말고 어떻게 진행하는 것이 더 좋을까요?

2023-09-10 05:24 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
> +    private val _successUpload = MutableLiveData<Boolean>()
Pn 까먹었었네요..... 담부턴 꼭 달도록 하겠습니다🤣
업로드 성공 시 유저에게 어떤 이벤트를 보여지게 할까에 대해 생각해 봤는데요!
1. myPage로 이동시켜 MyPlace에 추가된 모습을 보여주게 한다
2. Toast 만 띄워준다
이렇게 2가지 정도가 생각 나네요! 이정도면 전 사용자에게 충분한 정보 제공이 될 것 같아요
위와 같은 행동을 해도 사실 크롱의 말처럼 finish를 시키게 될 것 같아서 `DisposableLiveData` 를 사용하지 않아도 된다고 생각합니다! 크롱의 의견에 공감해요~

2023-09-10 05:26 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
> +        val nameRequestBody = name.toRequestBody("text/plain".toMediaTypeOrNull())
저는 보통 가독성 보단 코드의 간결성을 위해 보통 제가 적은 리뷰 처럼 작성하곤 했는데요,,
사실 크롱의 말처럼 다른 사람들이 이해하기 쉽고 가독성을 높이는 코드는 확실히 크롱이 작성한 코드 같습니다!!👍

2023-09-10 05:29 UTC, hyunji1203 approved these changes
크롱... 리뷰 답장이 늦어져서 정말 죄송합니다🤣
그리고 다음부터는 Pn 룰도 잘 지켜 달겠습니다ㅋㅋㅋㅋㅋ
전반적으로 크롱의 의견에 대해 잘 알 수 있게 되어서 좋았습니다! 
그리고 추가적으로 더이상의 코드 수정이 필요하지 않을 것 같아 Approve도 하겠습니다!
미션도 하는 중안데 팀플까지 하다니.. 고생많으셨어요~

2023-09-10 06:04 UTC, hyunji1203 commented
수정한 코드 까지 확인했습니다! 
Merge 하겠습니다~🦖

2023-09-10 06:05 UTC, merged