[BE] refactor: GameService.endGame() 리팩토링
woowacourse-teams/2023-naaga pull request #304
Opened 2023-09-07 17:37 UTC by dooboocookie

## 📌 관련 이슈
- closed: #297 

## 🛠️ 작업 내용
PR에서 작업한 주요 내용을 적어주세요.
- [x] GameService.endGame() 리팩토링
- [x] noRollbackFor 삭제 시도 -> 실제로는 삭제하지 못함
- [x] Game과 GameResult 도메인 패키지 분리
- [x] Game.endGame()의 역할을 Game의 상태에 대해서만 처리하도록 변경
- [x] PlayerService의 Player 점수 올리는 로직 추가
- [x] GameFinishService 게임 종료 관련된 인터페이스 추가 후 GameResultService로 구현 (의존성 순환 관련)
- [x] GameResultService.createGameResult() 추가

## 🎯 작업 내용
### 목표
#### 1. 가장 주된 목표는 `noRollbackFor`제거

- GameService.endGame() 서비스 로직에 @Transactional(noRollbackFor = GameNotArrivalException.class) 옵션이 붙어있었다.
- endGame()에서 Game을 DONE으로 바꾸지 못하는 상황은 예외로 판단했기 때문이다. (ex. 시도횟수가 남아있는데 실패했을 때) 
- 트랜잭션 범위 내에서 어떤 예외는 롤백하고 어떤 에외는 롤백하지 않는 옵션이 납득 되지 않았다 (All or Nothing 원자성을 해친다 생각)
- 위 문제들의 이유를 endGame()에서 너무 많은 일과 많은 테이블을 건드리고 있어서 문제라고 판단

#### 2. Game.endGame() 메서드의 가독성 증가와 GameService.endGame() 리팩토링

- Game.endGame()에서는  크게 3가지 정도의 일을 하고 있었다.
         1. ResultType(성공 여부)를 판단한다.
         2. Game의 GameStatus, endTime, RemainingAttempts를 수정한다.
         3. Game을 종료하지 못하면 예외를 발생한다.
- GameService.endGame()에서는 정말 많은 엔티티들을 건드리고 있었다.
         1. Game의 UPDATE (GameStatus, endTime, RemainingAttempts)
         2. GameResult의 INSERT
         3. Player의 UPDATE(totalScore)
         4. 이 과정에서 GameNotArrivalException이 발생하면 1번 중 RemainingAttempts가 1개 준다.

### 해결 과정
#### 1. Game과 GameResult의 도메인 패키지 분리

[최초]
- 이 예외를 터지는 상황의 원인인 API는 수정하지 않기로하고 리팩토링을 시작했다.
- 문제를 최대한 빨리 파악하기 위해서 각 도메인 패키지의 서비스에서는 그 도메인 패키지에 있는 엔티티의 조회 및 변경만 진행하도록 했다.
- 그래서 생명주기가 크게 다른 Game과 GameResult를 분리시켰다.

---

그림 자리 (1번째 다이어그램)

---

[고침1]
- 문제점이 발생했다. Game.endGame()에서 ResultType을 반환하면서 GameResult와 도메인 제약사항을 밀접하게 공유하고 의존성 순환이 생겼다.
- Game.endGame()의 존재 의의를 최대한 Game 위주로 생각했다.
- 해당 메서드는 게임을 끝내기 위해서 존재하는 것이지 게임의 승패를 따지기 위한 것도 아니다.
- 만약 게임의 승패를 구하는 것도 Game의 역할이라면 Game의 결과 타입에 대한 필드가 존재해야할 것이다.
- 그래서 해당 메서드에서는 Game에 종료를 나타내는 필드의 상태 변경만 시키고 만약 종료가 불가능한 상황이면 예외를 발생시켰다.
- 그래서 다음과 같이 의존성을 끊을 수 있었다.

---

그림 자리 (2번쨰 다이어그램)

---

[고침2]
- 여기서 한가지 더 문제점이 발생했다. GameResult를 생성하고 저장하는 역할은 GameResultSevice에서 이루어져야한다.
- GameResultSevice는 gameResult 패키지에 존재
- 의존성 순환이 생김
- game에 추상화된 Sevice를 위치시키고 DIP로 문제 해결

---

그림 자리 (3번쨰 다이어그램)

---

[최종]
- Player의 변경사항은 PlayerService에서 처리하도록 메서드 추가
- 최종적으로는 의존성이 한방향으로만 흐르도록 도메인 패키지 변경

---

그림 자리 (최종 다이어그램)

---

---

### 2. 시도 횟수를 줄이는 로직 트랜잭션 분리
- noRollbackFor는 시도 횟수를 줄이는 로직을 트랜잭션 분리를 시키면 지울 수 있을 것이라 판단

---

그림 자리 (트랜잭션 그림)

---

- 하지만, 문제점은 이 두 과정은 트랜잭션이 완벽한 분리가 불가능하다.
- 1번(메인) 트랜잭션에서 NotArrivalException을 제외한 예기치못한 예외가 발생하면 2번(Require_new) 트랜잭션이  롤백되어야한다.
- 2번(Require_new)에서 예기치 못한 예외가 발생한다면 1번(메인) 에서 이미 한작업이 있다면 롤백 시켜야한다.
- 따라서, 이 문제는 테이블 분리, 트랜잭션 분리, 비동기로 이벤트 호출, ... 같은 문제로 해결할 수 없다고 판단했다.

## ⏳ 작업 시간
추정 시간:   3시간
실제 시간:   4시간
이유: 사실 실제로 투자한 시간이 많았습니다. 고민한 시간이 길었기 때문입니다.

2023-09-12 13:13 UTC, zillionme commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
>      }
게임 종료의 순서가
1. 종료타입이 = 도착일 때, 시도횟수를 뺄 수 있는지 확인하고, 시도횟수를 뺀다.
2. 종료한다
   - 종료된 게임인지 확인한다
   - 종료할 수 있는 상황(포기가 아니고, 시도횟수 남았는데, 실패인 경우)이 아닌지 확인한다
   - 종료 시간을 기록하고, 게임 상태를 DONE으로 바꾼다.


물론 그럴 확률이 없겠지만, "endType=도착"이어도 
이전에 게임 포기로, 시도횟수는 남았지만 이미 gameStatus가 DONE일 수도 있다고 생각합니다)

고친 순서는
1. 게임이 이미 종료되었는지 확인한다
2. 종료한다
   - 종료타입이 = 도착일 때, 시도횟수를 뺄 수 있는지 확인하고, 시도횟수를 뺀다.
   - 종료할 수있는 상황이 아닌지 확인한다.
   - 종료시간을 기록하고, 게임 상태를 DONE으로 바꾼다


따라서 코드가
```
public void endGame(final Position position,
                        final EndType endType) {
        validateInProgressing();
        setDone(position, endType);
    }
    
private void setDone(final Position position,
                         final EndType endType) {
        if (endType == ARRIVED) {
            subtractAttempts();
            return;
        }
        validateForEnd(position, endType);
        this.endTime = LocalDateTime.now();
        this.gameStatus = DONE;
    }
```
처럼 되는 건 어떤가요?

2023-09-12 13:36 UTC, kokodak requested changes
안녕하세요 아리가또.. 루카짱!

리팩터링 내용 잘 봤습니다. 이 이슈를 완수하시려고 정말 많은 고민을 하셨다는 게 느껴지는 작업물이었습니다. PR 내용 설명이 자세해서 코드를 해석하는데 많은 도움이 됐네요 ㅎㅎ 고생 많으셨어요

제 의견을 좀 남겨놨는데, 검토해주시면 감사하겠습니다 ㅎㅎ
화이팅!!!

2023-09-12 13:36 UTC, kokodak commented on backend/src/main/java/com/now/naaga/gameresult/application/GameResultService.java
> +        final AddScoreCommand addScoreCommand = new AddScoreCommand(player.getId(), score);
이곳의 Command 에서는 player 가 아닌, player 의 id 를 넘겨준 이유가 무엇인가요?

2023-09-12 14:47 UTC, zillionme reviewed
안녕하세요 루카!
pr에 대한 설명이 잘 되어있어서 감동먹었습니다. 
1. 처음 게임과 게임 결과 객체의 생명주기가 달라서 패키지 분리를 하고
2. 런타임 의존성을 분리하기 위해, 메서드를 적절히 분리하고
3. 패키지 의존성을 해결하기 위해 DIP를 사용했다.
같은 일련의 과정들이 잘 이해 되었어요.
no rollback for에 대해 왜 안되는지에 대해서도
1. 자식 객체에서 예외가 발생했을 때, 부모객체도 롤백되어야 하는데, 예외가 전파되지 않는다
2. 부모 객체에서 특정 예외 외의 예기치 못한 예외가 발생했을 때도 자식 객체에 예외가 전파가 되지 않는다.
는 두가지 이유로 깔끔하게 설명이 잘 된것 같습니다.

2023-09-12 14:47 UTC, zillionme commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +    }
개인적으로 결과 타입의 객체가 decide()메서드를 실행하는 게 자연스럽게 느껴지지 않는 부분이 조금 있습니다. 
- 게임 결과 조건(게임이 도착이고 실패이면 남은 시도횟수가 0이어야 한다, 시도횟수가 1이상이면 예외이다)도 고려해야하지 않을까요?
- 게임이 실제 진행중인지 확인 + game객체에서 getter를 통해 게임 결과를 내고 있는데
- 그렇다면 게임 객체에 일을 시키는 게 맞지 않나 생각이 듭니다. (다시 패키지 바꾸자는 말 아닙니다)
- 
```
public static ResultType decide(final Game game,
                                    final EndType endType,
                                    final Position position) {
        if(game.getGameStatus() == IN_PROGRESS) {
            throw new GameResultException(GameResultExceptionType.NOT_FINISH_GAME);
        }

        if (endType == EndType.ARRIVED) {
            if (game.getPlace().isCoordinateInsideBounds(position)) {
                return ResultType.SUCCESS;
            }
        }
        return ResultType.FAIL;
    }
```

2023-09-13 05:38 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/game/persistence/GameRepository.java
> +package com.now.naaga.game.persistence;
이제는 코코닥의 초반 설계를 할 때 왜 도메인 패키지에 Repository를 넣자고했는지 이해를 할 것 같아요.
저희가 사용하는 XxxRepository는 JpaRepository 인터페이스를 상속하고 있는 형태이고,
특정 도메인 객체를 참조하고 있습니다.
따라서 해당 Repository는 어떤 도메인의 컬렉션 정도의 역할로 생각하면 될 것 같습니다.




![IMG_6845](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/db02a4e6-4438-48ca-a77d-a615c6b05afc)

근데 제가 이 PR에서 저것을 바꾼 이유는 어떤 레이어에 대해서 고민을 했다기보단 다른 도메인 패키지와 맞추기 위함이였습니다.

일단 제가 해당 부분을 원복해놓을테니 해당 건 관련해서 다른 도메인 패키지의 구조도 변경하는 이슈를 발급해야될 것 같습니다!

2023-09-13 05:45 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
> +    private void setDone(final Position position,
제가 위와 같이 네이밍을 지은 이유는 일단 GameStatus라는 네이밍 자체가 Game객체의 필드 값으로서 의미가 중복된다는 생각이 들어서였습니다.
game.setGameStatusDone 이라는 네이밍에 너무 Game이라는 개념어가 많이 등장하는 것 같아서 였는데, 코코닥 말씀대로 처음 보는 사람 입장에서는 직관적으로 느껴지지 않을 수 있겠다는 생각이 듭니다.

코코닥 의견 적극 수용하여 변경하도록 하겠습니다

2023-09-13 06:11 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
> +        final boolean isUnfinishedCondition = remainingAttempts > 0
이 Game 도메인에 endGame이라는 메서드가 절차에 의존하는 경향이 매우 세서 중복적인 조건이라고 생각할 수 있을 것 같습니다.

```
    public void endGame(final Position position,
                        final EndType endType) {
        if (endType == ARRIVED) {
            subtractAttempts();
        }
        setGameStatusDone(position, endType);
    }
```

먼저 이 메서드를 순서대로 읽어 보면

1. 유저가 `도착`, `포기` 요청했는지 판단하여 시도 횟수를 한개 낮춘다.
2. 게임 상태를 Done으로 바꾼다.

1에서는 아래와 같은 시도횟수에 대한 검증을 합니다.
```java
    public void endGame(final Position position,
                        final EndType endType) {
        if (endType == ARRIVED) {
            subtractAttempts();
        }
        setGameStatusDone(position, endType);
    }
```
시도횟수를 1개 깎으려다가 시도 횟수가 남아있는지를 판별해서 어떤 결과를 판가름 한다기보단, 횟수 차감하기 전에 단순히 차감을 확인하는 것입니다.


2에서는 아래와 같은 시도횟수에 대한 검증을 합니다.

```java
    public void endGame(final Position position,
                        final EndType endType) {
        if (endType == ARRIVED) {
            subtractAttempts();
        }
        setGameStatusDone(position, endType);
    }
```
이는 시도횟수가 현재 유효한지 확인하는 것이아니라 지금 끝낼 수 있는 조건인지에 대한 검증입니다. 즉, 이에 대한 검증은 명확하게 한 케이스를 검증하는 것입니다. `도착 버튼을 눌렀고, 목적지 범위 밖에 있으며, 게임 시도횟수가 남아있을 때` 즉 `아직 게임 종료를 못하고 다음 도전을 누를수 있는 상황`에 대한 검증 &rarr; setGameStatusDone이 실패하는 경우에 대한 예외입니다!!

따라서 두 조건은 중복이 아닙니다.
단적인 예로 게임 유저가 시도횟수가 3번 남은 상황에서 도착 버튼을 눌렀는데 범위 밖인 상황이라면,  어템츠를 하나 줄여서 2번 예외에 도달 됐지만 저 `remainingAttempts > 0`조건이 없으면 예외에 걸리지 않아서 게임 상태가 Done으로 바뀔 것입니다.

2023-09-13 06:22 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/game/exception/GameNotFinishedException.java
> +public class GameNotFinishedException extends GameException{
일단 현재 방법을 유지하는 것도 꽤 괜찮은 방법인 것 같습니다.
특정 타입으로 핸들링되는 설정으로 인해서 더 특정할만한 자식 타입을 만들어서 필드도 동일하게 `GameExceptionType`을 갖게 한다는 점에서 좋은 점이 있을 것 같습니다.
-  대부분의 것을 `GameException`과 동일하게 가져가지만, 타입만 조금더 특정지어 가져간다.

다른 방법으로는 `GameException`을 상속하는 것이아니라 
- `BaseException`을 상속하여 게임 익셉션과 같은 레벨의 특정 객체를 만든다. 
이 방법도 좋은 방법일 수 있지만 도메인당 하나의 익셉션 타입을 만들기로 한 저희 컨벤션에는 위의 상황이 조금은 적합해보이는데 어떻게 생각하시나요??
자식 객체지만 GameException으로 퉁칠 수 있자나요?🥺

2023-09-13 06:33 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +    public static ResultType decide(final Game game,
이제는 Game의 영역이아니라 GameResult의 영역으로 넘어왔는데요.
저는 `Game에서 판단하고 싶었던 내용`은, 게임결과가 `성공했냐? 실패이냐?`가 아니라 게임을 `끝낼 수 있냐? 없냐?`였습니다.
그와 마찬가지로 `GameResult에서 판단하고 싶은 내용`은, 게임이 `끝낼 수 있냐? 없냐?`가 아니라 결과가`성공이냐? 실패이냐?`입니다.

그래서 그 성공에 대한 여부는 무조건 Game이 종료된 게임에 대해서만 진행해야하므로 이 메서드에 대한 예외상황을 규정한 것입니다.

시도 횟수가 남아있든 없든 Game 객체가 온전하다면 Done은 끝난 게임인 것이니까요!

그치만 코코닥의 의견을 들은 후에 해당 메서드의 책임에 대해서 다시 생각중인데요. 물어보고 싶은 의견이 있어서 밑에다가 남기겠습니다.

2023-09-13 07:06 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/application/GameResultService.java
> +        playerService.addScore(addScoreCommand);
제 생각의 결론 부터 이야기하자면, 이대로가 더 직관적인 흐름이라는 생각이 듭니다.

이 생각에 도달하게 된 이유를 말씀드리자면 두 가지 관점이 있는데요.

1. 플레이어가 점수가 오르는 이유는 게임이 끝났기 때문이 아니라 게임 결과에 따라서 점수가 생성되었기 때문이라서 Game보다는 GameResult에 훨씬 밀접한 연관이 있는 작업이라고 생각합니다.
2. 현재 구조에서 GameResultService에서 발생된 Score를 직접적으로 GameService에서 받을 수 없습니다 만약 GameFinishService인터페이스에서 해당 메서드의 시그니처를 GameResult를 반환하게 하면 또 의존성 사이클이 발생됩니다.

2번은 약간 좀 현실적인 사고의 번거로움 줄이기 위해서도 있긴합니다. (수정의 범위가 Score까지 번질 것 같아요)
그래서 1번 명분에 조금 더 집중해서 이야기하고 싶은데요!

일단은
> Score 도메인이 생성되는 시점에서 Player의 점수를 올려야한다. 
라는 논리로 코코닥의 의견에 반박해볼까하는데 어떻게 생각하시나요.

2023-09-13 07:09 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/exception/GameResultExceptionType.java
> +    ;
이것을 종료되지 않은 게임이라는 게임에 대한 예외로 정의해보겠습니다!! 👍
decide() 관련 피드백에 대한 의견과 조금 중첨되는 부분이 있을 것 같아서 추가적인 의견은 그쪽에 남겨보겠습니다

2023-09-13 07:10 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +            throw new GameResultException(GameResultExceptionType.NOT_FINISH_GAME);
GameExceptionType에 의견 남겨주셨던 내용에 답변달겠습니다

2023-09-13 07:50 UTC, chaewon121 reviewed
루카 의존성 분리에 대한 고민이 많았던것 같은데 좋은 방안을 생각해 낸것 같아 정말 대단하네요. 고생 많았습니다! 코멘트 남겨놓았습니다!

2023-09-13 07:50 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
>      }
위에 이레답변과 코코닥 답변도 함께 읽어본 후 생각해 보았습니다.
일단 현재 코드에서 보이는 문제점은
1. EndType이 포기일때는 validateInProgressing(), validateForEnd() 둘다 할 필요가 없습니다.
즉, EndType이 포기일때는 딱한가지 validateInProgressing() 만 체크하면 되는데요.
그래서 제가 생각한 로직은 다음과 같습니다.
```
public void endGame(final Position position,
                        final EndType endType) {
        validateInProgressing();
        if (endType == ARRIVED) {
            subtractAttempts();
            validateForEnd(position);
        }
        setDone();
    }

    private void subtractAttempts() {
        validateAvailableAttempts();
        remainingAttempts--;
    }

    private void validateAvailableAttempts() {
        if (remainingAttempts <= 0) {
            throw new GameException(GameExceptionType.NOT_REMAIN_ATTEMPTS);
        }
    }

    private void setDone() {
        this.endTime = LocalDateTime.now();
        this.gameStatus = DONE;
    }

    private void validateForEnd(final Position position) {
        final boolean isUnfinishedCondition = remainingAttempts > 0
                && !place.isCoordinateInsideBounds(position);

        if (isUnfinishedCondition) {
            throw new GameNotFinishedException(NOT_ARRIVED);
        }
    }

    private void validateInProgressing() {
        if (gameStatus == DONE) {
            throw new GameException(ALREADY_DONE);
        }
    }
```
먼저 endGame 함수의 순서가 바뀌었고,
 setDone() 안에있는 예외처리가 밖을 로 빠졌으며,
 validateForEnd() 안에있는 isUnfinishedCondition에서 && endType != GIVE_UP; 이부분 체크를 빼서 중복 체크 로직이 제거되도록 수정해보았습니다! 
 저런식으로 로직을 수정하는건 어떤가요!?

2023-09-13 07:50 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +            throw new GameResultException(GameResultExceptionType.NOT_FINISH_GAME);
여기서 검증하는 게임이 inprogress일때의 상황은 사용자 오류가 아닌 백엔드 코드상의 오류라는 판단이 드는데요. 애초에decide라는 함수가 실행되려면 게임 상태가 done일때여야 된다고 생각합니다. 그래서 decide 함수에서 inprogress예외를 검증하는 것이 아닌 애초에 done일때만 decide()가 실행될 수 있도록 코드를 수정해보는것은 어떨까요?

2023-09-13 07:50 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/player/application/PlayerService.java
> +                .orElseThrow(() -> new PlayerException(PLAYER_NOT_FOUND));
만들어진 함수를 사용해서
final Player player = findPlayerById(playerId);
로 수정하는것은 어떨까요?

2023-09-13 07:56 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/player/application/PlayerService.java
> +                .orElseThrow(() -> new PlayerException(PLAYER_NOT_FOUND));
또한 playerService에 있는 create() 메서드를 createPlayer()로 수정해보는것은 어떨까요?

2023-09-13 08:28 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +        if(game.getGameStatus() == IN_PROGRESS) {
저는 이 곳에 넘어 오게 되는 Game은 `종료된 Game여야 한다는 전제`가 무조건 필요해서 작성된 검증입니다.

근데 여기서 발생되어야하는 예외가 GameResultException이여야한다는 강박이 있었는데요.
코코닥의 리뷰를 보고 game.validateOwner()같이 GameException일 수 있게다는 생각을 했습니다. 
그래서 이 검증 과정은 Game안으로 넣도록 하겠습니다.

다만 이 검증 로직이 호출되는 위치가 Service와 이 decide() 내부중 어디서 호출되는 것이 맞을지에 대해서는 아직 확신이 들지 않습니다!!
근데 일단은 이 검증이 필요한 이유는 게임이 결과를 판별할 때 이 게임이 종료된 게임인지 확인하는 용도이므로 decide() 안에서 하는 것이 지금은 적절해보입니다.

2023-09-13 08:55 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
>      }
오 좋은 지적 감사합니다!!
제 생각에도 이 endGame 과정을 진행할 떄 제일 첫 순서로 이미 종료된 게임인지에 대해서 판별하는게 우선인것 같습니다!!
그렇게 수정하도록 하겠습니다!!

근데 다만 
```java
        if (endType == ARRIVED) {
            subtractAttempts();
            return;
        }
```
이프문 안에 return문은 잘못 쓰신게 맞으실까용? 저기서 리턴하면 종료 시 시간 기록과 Done이 기록이안되어서요

2023-09-13 08:57 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/application/GameResultService.java
> +        final AddScoreCommand addScoreCommand = new AddScoreCommand(player.getId(), score);
이게 제가 서비스에서 다른 서비스의 메서드를 호출할 떄 도메인 자체를 넘겨주는 것이 맞을지,
그에 대한 아이디를 끊어내서 주는 것이 맞을지 확신이 안들어서 혼용해서 사용했던 것 같습니다.
밑에 이레의 CreateGameCommand관련 피드백에 대해서 이어서 답변달겠습니다

2023-09-13 09:15 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +    }
이것에 대한 답장을 위에 코코닥의 decide();에 대한 피드백에 답장으로 답장이되었다고 생각합니다!! 추가적으로 의견있으시면 거기에 이어서 의견 말씀 부탁드립니다!!

2023-09-13 10:20 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
>      }
`&& endType != GIVE_UP; ` 이 부분을 중복 체크로 판단하셨군요!!
저는 약간 관점이 달랐는데요!
```java
        if (endType == ARRIVED) {
            subtractAttempts();
        }
```
이 과정에서 endType을 ARRIVED인 것을 확인하는 이유는 순수하게 시도횟수를 하나 내리기 위함입니다.

```java
    private void validateForEnd(final Position position,
                                final EndType endType) {
        final boolean isUnfinishedCondition = remainingAttempts > 0
                && !place.isCoordinateInsideBounds(position)
                && endType != GIVE_UP;

        if (isUnfinishedCondition) {
            throw new GameNotFinishedException(NOT_ARRIVED);
        }
    }
```

이 과정에서는 이 것이 끝낼 수 없는 조건인가를 따져보는 이유였습니다!
그래서 채채 말대로 이 validate 하는 부분을 저 분기 안으로 넣으면 조건 하나가 줄 수 있지만, 
각각의 private 메서드가 실행되는 논리적인 이유가 있다고 생각이 듭니다! 
채채의 의견대로 바꾼다면 위 if문의 의미가 조금 바뀔 것이고 도메인로직이 복잡해질 수록 메서드의 의미를 파악하는 것이 더 어려워질 수 있을까 우려가됩니다!!

그래서 일단은 짧은 생각은 기능적 차이가 없다면 이대로 가는 것이 좋을 것 같습니다!!

2023-09-13 10:25 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +            throw new GameResultException(GameResultExceptionType.NOT_FINISH_GAME);
채채의 의견은 Service 로직 단계에서 
1. 게임이 종료되었는지 판단한다
2. decide(game, ...)을 호출한다

이렇게 말씀하시는 것 같은데요!!
저도 아직 이에 대해서 확신이 들지는 않습니다!!

저도 decide() 안에 검증로직이 있던, service에 검증로직이 있던 동일한 동작을 하는 것은 확실한 것 같은데요.
근데 만약 decide라는 메서드의 재사용성을 생각해보면, game의 상태정검을 해주고 decide를 호출하는 상황이 없을 수도 있을것 같다는 생각이 듭니다.
그래서 게임의 결과를 판단하는데 꼭 필요한 조건인 `종료된 게임이다` 라는 판단을 resultType안에서 하는 것이 아직은 적절하다는 생각이 듭니다!ㅠㅠㅠ

2023-09-13 10:28 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
>      }
그외에 말씀해주신대로 inProgressing 정보를 제일 앞단에서 확인하는 것은 수정하였습니다!!
감사합니다

2023-09-13 10:32 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/player/application/PlayerService.java
> +                .orElseThrow(() -> new PlayerException(PLAYER_NOT_FOUND));
헉 메서드 재활용 너무 좋은 아이디어입니다. 특정 엔티티의 조회 로직을 메서드로 구성해놓고 재활용하는 것 너무 좋은것 같아요!!
근데 밑에서 주신 create() 메서드 네이밍 수정은 이 PR에서 내용이 조금 벗어난 것 같아서 너무 좋은 의견이시지만 일단은 이 PR에서 주제를 집중할 수있도록 커밋에 포함시키진 않겠습니다!!

2023-09-13 10:36 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/player/application/PlayerService.java
> +                .orElseThrow(() -> new PlayerException(PLAYER_NOT_FOUND));
앗 코드단위로 보다보니 pr단위에 없는 매서드얘기를 했군요 죄송합니다 ㅠㅠㅠ

2023-09-13 10:37 UTC, dooboocookie commented
좋은 의견 많이 남겨주셔서 감사합니다!!
코드의 의도가 잘못 전달 된 부분이나 생각이 약간은 다를 수 있는 부분은 댓글로 답변 달았습니다.
또한 다 좋은 말씀 남겨주셔서 코드 좋게 고칠 수 있었습니다!!
 
말씀해주신 내용에 대해서는 다 댓글로 답변 드려서 따로 추가적으로 드릴 말씀은 없을 것 같고

몇가지 리뷰방식에 대해서 덧붙이고 싶은게 있는데요!

1. Pn 방식 지켜주시면 좋을 것 같습니다!!
2. 동일한 주제 코드에 대해서는 새로 리뷰범위 설정하지 말고, 이전 팀원이 리뷰단 곳 밑에 댓글로 다는 것이 좋아보이는데 어떻게 생가하시나요?


(코드 자동절렬했는데, 수정 범위가 너무 커지네요. 그래서 자동정렬 부분은 푸시에 포함시키지 않았습니다! 그래서 이거 자동정렬은 따로 이슈파도 좋을 것 같아요!)

2023-09-13 15:51 UTC, kokodak commented on backend/src/main/java/com/now/naaga/game/persistence/GameRepository.java
> +package com.now.naaga.game.persistence;
좋습니다. 그림으로 그려보면서 의존성 방향까지 고려하시다니.. 대단하시네요 ㅎㅎ
추가적인 이슈 발급은 나중에 안건으로 올려보면 좋을 것 같습니다.

2023-09-13 16:44 UTC, kokodak commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
> +        final boolean isUnfinishedCondition = remainingAttempts > 0
제가 잘못 생각했었네요. 죄송합니다 ㅎㅎ..

말씀하신대로 중복되는 검증이 아닙니다. 제가 `validateAttempts()` 를 하고 `attempts--` 하는 로직을 놓쳤던 것 같습니다.

다만 말씀해주신 `시도횟수가 3번 남은 상황` 에서는 `remainingAttempts > 0` 조건이 없어도 예외가 터지기 때문에 Done으로 바뀌진 않을 것 같습니다. 중복되는 검증이 아니라는 점을 증명하는 엣지 케이스는 attempts의 값이 1 -> 0 으로 가는 경우일 것 같네요.

처음에는 `remainingAttempts > 0` 을 만족하지만, 잠시 뒤 `remainingAttempts--` 가 되면서 `remainingAttempts > 0` 가 거짓이 되는 상황이 생기기 때문에, 참/거짓이 같은 메서드 흐름에서 바뀔 수 있는 케이스가 존재하네요. 제가 이걸 놓쳐서 바보같은 리뷰를 남겨버렸습니다.. 구체적으로 봐주셔서 감사합니다!

2023-09-13 16:48 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +            throw new GameResultException(GameResultExceptionType.NOT_FINISH_GAME);
사용자의 오류가 아닌 코드의 오류를 따로 예외처리를 한다는 것이 자연스럽게 느껴지지 않지만 루카의 의견처럼 재사용성을 생각하면 루카의 의견도 맞다는 생각이 듭니다! 하지만 일단 저 매소드는 현재 여러곳에서 사용되지 않기에 재사용성보다는 부자연스러운 흐름을 해결하는 쪽이 어떤가 하여 의견을 내보았습니다..! 루카가 여러 방향을 생각했을때 더 좋다고 판단하는 코드로 가면 될것같네요~!

2023-09-13 16:50 UTC, kokodak commented on backend/src/main/java/com/now/naaga/game/exception/GameNotFinishedException.java
> +public class GameNotFinishedException extends GameException{
동의합니다. 상속을 사용한다면, BaseException을 상속하는 것 보다는 GameException을 상속하는 것이 더 적합하다고 생각되네요.
답변 감사합니다!

2023-09-13 17:01 UTC, kokodak commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +    public static ResultType decide(final Game game,
검증 로직에만 집중했는데, 그 검증으로 인해 생기는 로직 맥락은 제가 놓쳤던 것 같네요.

말씀하신대로, 게임이 끝난 상태이고, 그 게임에 대한 성공/실패 를 판단하는 것이기 때문에 시도횟수와는 무관한 로직을 가져도 문제가 없다고 생각합니다. 좋네요!

2023-09-13 17:06 UTC, kokodak commented on backend/src/main/java/com/now/naaga/gameresult/domain/ResultType.java
> +        if(game.getGameStatus() == IN_PROGRESS) {
반영해주셔서 감사합니다.

저 또한 검증 로직은 service 보단 decide() 내부에 위치하는 것이 적절하다고 생각합니다.
decide() 의 책임은 `끝난 게임에 대한 성공/실패 결과 여부 결정` 이라고 생각하고, 만약 끝나지 않은 게임이 들어왔을 때는 decide() 가 애초에 불가능한 상황이므로, 이에 대해 스스로 검증을 할 수 있는 능력은 주어지는게 적절하다고 생각합니다.

2023-09-13 17:19 UTC, kokodak commented on backend/src/main/java/com/now/naaga/gameresult/application/GameResultService.java
> +        playerService.addScore(addScoreCommand);
동의합니다. 설득이 됐습니다.

1번은 사실 약간의 관점 차이로 갈릴 수 있을 것 같긴 한데요, 루카가 말하신 것이 충분히 납득 가능하다고 생각되기에 이대로의 흐름을 유지하는 것이 좋을 것 같습니다.
2번의 이유도 사실 무시할 수 없을 것 같긴 하네요. 기술적으로 또 다른 고민이 생겨날 수 있는 지점인데, 사실 그정도의 비용을 지불하면서 1번 관점을 바꾸기에는.. 트레이드 오프가 성립되기 어렵다고 생각하긴합니다.

답변 감사합니다!

2023-09-13 17:29 UTC, kokodak approved these changes
남겨주신 답변들 모두 다 보았고, 제 답변이 필요해보이는 곳에 저의 생각들을 남겨놓았습니다.
반려하신 부분은 모두 설득이 되어서 Approve 로 수정하겠습니다!
리뷰 적용해주셔서 감사하고 고생하셨습니다 😁

+)
Pn 룰은 잘 지켜지는 것이 좋겠습니다. 또한 이미 리뷰가 있는 곳에서 비슷한 생각으로 제안하는 것이라면 댓글로 이어가는 것에 동의합니다. 그게 더 편할 것 같네요 ㅎㅎ
추가적으로, 적용이 끝난 리뷰이고 추가적으로 얘기를 남길 것이 없다면 리뷰이가 resolve conversation을 눌러주는 것도 좋을 것 같아요!

2023-09-17 05:53 UTC, zillionme commented on backend/src/main/java/com/now/naaga/game/domain/Game.java
>      }
return()을 잘 못 넣은 것이 맞습니다

2023-09-17 07:29 UTC, zillionme commented
루카 늦은 리뷰 죄송합니다.
다음부터는 더 빠른 리뷰 approve 하도록 하겠습니다.
모든 리뷰를 천천히 읽어본 결과, 루카가 오래 고민한 만큼 모두 적절한 이유가 있는 것 같다는 생각이 들었습니다.
리뷰에 대한 변경사항도 확인 했구요.
이만 여기서 approve하겠습니다.

2023-09-17 07:32 UTC, zillionme approved these changes
루카 늦은 리뷰 죄송합니다.
다음 부터는 일정을 확인해서 하루 내에 재 리뷰할 수 있도록 하겠습니다.
리뷰 남긴지 시간이 흐르고 다시 코드를 읽으려니 조금 더 시간이 걸렸네요ㅠ
루카의 답변 모두 읽어보았는데, 루카가 오래 고민해서 작성한 코드였던 만큼 설득력 있는 답변이었습니다.
더해서, 바뀐 코드에 대해서도 잘 수정이 된것 같아 이만 approve하도록 하겠습니다.

2023-09-18 16:50 UTC, chaewon121 approved these changes
루카! 어려운 내용임에도 너무 정리 잘해주셔서 코드  이해가 빨랐습니다 감사합니다..! 많은 고민이 느껴졌고 팀원들의 리뷰도 잘 반영해주셨네요! approve 하겠습니다~!
고생 많으셨습니다!

2023-09-18 16:51 UTC, merged