refactor: 로깅 구체화 하기
woowacourse-teams/2023-naaga pull request #318
Opened 2023-09-13 16:24 UTC by chaewon121

## 📌 관련 이슈
- closed: #303 

## 🛠️ 작업 내용
PR에서 작업한 주요 내용을 적어주세요.
- [x] mdc 도입하여 로깅 메세지 추가
- [x] QueryCounter 도입하여 쿼리 갯수 로그에 추가
- [x] logfilter을 도입하여 필터 시점에 로그 출력
- [x] error, warn, info 레벨로 나누어 로그 파일 분리
- [x] 로깅 전략 세우기

## 🎯 작업 내용
## 로깅 전략 세우기
### 계층별 로그

#### ERROR

개발단계에서 고려하지 못한 에러 즉, 500 에러에 대해 로그를 남긴다.

#### WARN

오류는 아니지만 향후 오류가 될 수 있는 부분에 대해 로그를 남긴다.

#### INFO

일반정인 응답 또는 의도한 오류에 대해 로그를 남긴다.

DEBUG, TRACE 는 로그로 남기지 않는다.

## 계층별 로그에 남길 내용

### ERROR

- 쓰레드 id
- `timestamp`
- 메서드
- 요청 url
- 에러 메시지
- stackTrace

```json
{
  "method" : "GET",
  "request_id" : "90401dd7-223b-4b38-8453-3706cc1cf34a",
  "uri" : "/ranks/save",
  "timestamp" : "2023/09/07 16.52.34.201000",
  "message" : "error = org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' is not supported"
  "stacktrace" : "stacktrace"
}
```

### WARN

- 쓰레드 id
- `timestamp`
- 메서드
- 요청 url
- 경고 메시지 남기기

### INFO

1. 예상한 오류가 간 경우
    - 쓰레드 id
    - 요청을 보낸 시간(`timestamp`)
    - 메서드
    - 요청 URL
    - 요청을 처리하는데에 걸린 시간
    - 실행된 쿼리문 개수
    - 오류 메세지

ex)

```json
{
  "jsonResponse" : "ExceptionResponse{code=101, message='헤더 정보가 유효하지 않습니다.'}",
  "method" : "GET",
  "queryCount" : "0",
  "time" : "9ms",
  "request_id" : "ed9a0133-31bf-4998-af44-3d8bb7d313f7",
  "uri" : "/ranks/my",
  "message" : "level: info",
  "timestamp" : "2023/09/07 16.07.06.557000"
}
```

1. 정상 응답
    - 쓰레드 id
    - 요청을 보낸 시간(`timestamp`)
    - 메서드
    - 요청 URL
    - 요청을 처리하는데에 걸린 시간
    - 실행된 쿼리문 개수

```json
{
  "queryCount" : "2",
  "time" : "9ms",
  "method" : "POST",
  "request_id" : "dc3b29f2-d36a-405b-8197-c4fa34d79849",
  "uri" : "/ranks/save",
  "timestamp" : "2023/09/07 15.33.26.803000"
}
```

- **MDC 를 이용해서 스레드 별로 고유한 식별자를 추가하여 쓰레드 별 로그를 구분한다.**

- **가독성을 고려하여 json으로 로그를 생성한다.**

- **filter을 도입하여 쿼리문 개수, 요청에 걸린 시간, 요청을 보낸 시간을 계산한다.**

### 프로필 별 로그 관리

#### 로컬에서

- 지금처럼 콘솔로 로그를 남기고 파일로는 관리하지 않는다.

#### 데브 서버와 운영 서버에서

- 로그를 콘솔로 남기지 않고 파일로 관리한다.

### 로그 주기 관리

- 30일 주기로 파일을 초기화 한다.
- 5gb로 주기로 파일을 초기화 한다.

# 코드 설명

## MDC를 도입

### 이유:

mdc는 스레드 별로 로깅 컨테스트를 유지하기 때문에 스레드별로 로그를 관리하기가 편합니다. 또한 mdc를 사용하면 로그 출력 포멧을 지정할 수 있기때문에 원하는 메세지를 출력하고 관리하기에 매우 편리하기에 도입하게 되었습니다.

또한 mdc는 map으로 관리가 되기 때문에 키, 값에 대한 로그 출력이 자유롭습니다.

```java
MDC.put(TIME.getKey(), String.valueOf(time) + "ms");
MDC.put(QUERYCOUNT.getKey(), String.valueOf(queryCount));
```

위와 같이 mdc map에 값을 담고

```xml
info-appender.xml
<mdc>
                    <fieldNames>
                        <request_id>request_id</request_id>
                        <uri>uri</uri>
                        <method>method</method>
                        <time>time</time>
                        <queryCount>queryCount</queryCount>
                        <jsonResponse>jsonResponse</jsonResponse>
                    </fieldNames>
                </mdc>
```

로그를 출력하는 xml파일에서 위와 같이 출력할 수 있습니다.

## filter 도입

```java
@Override
    public void doFilter(ServletRequest request,
                         ServletResponse response,
                         FilterChain chain)
            throws IOException, ServletException {
        queryCounter.init();
        final long start = System.currentTimeMillis();

        chain.doFilter(request, response);

        log(response, start);
        queryCounter.close();
    }

    private void log(final ServletResponse response,
                     final long start) {
        final int queryCount = queryCounter.count();
        final long end = System.currentTimeMillis();
        final long time = end - start;
        MDC.put(TIME.getKey(), String.valueOf(time) + "ms");
        MDC.put(QUERYCOUNT.getKey(), String.valueOf(queryCount));
        log.info("level: {}", "info");
    }
```

필터를 시작할때 queryCounter를  초기화 하고 요청 시작 시간을 저장합니다.

요청이 무사히 마무리 된다면(오류없이) log() 함수를 실행하게 됩니다.

이과정에서 요청이 끝난시간과 앞에서 저장해 놓았던 요청시작시간을 비교하여 걸린 시간을 측정합니다. 또한 요청이 끝났을때 쿼리가 몇개 실행되었는지도 계산합니다.

이렇게 계산된 값을 mdc에 넣습니다.

mdc에 들어있는 값들은 xml 파일 설정에 따라 출력합니다.

mdcFilter클래스는 여러 코드를 참고하다가 넣게되었는데..mdc에 대한 추가 관리가 필요하지 않아 현재로서는 없어도 될것같아 이부분에 대해서 같이 생각해봅시다..!

필터를 빈으로 관리하여 순서를 지정할 수 있습니다.

```java
@Bean
    FilterRegistrationBean<MdcFilter> mdcFilter() {
        MdcFilter mdcFilter = new MdcFilter();
        FilterRegistrationBean<MdcFilter> registrationBean = new FilterRegistrationBean<>(mdcFilter);
        registrationBean.setOrder(FIRST);
        return registrationBean;
    }

    @Bean
    FilterRegistrationBean<LogFilter> logFilter() {
        LogFilter logFilter = new LogFilter(queryCounter);
        FilterRegistrationBean<LogFilter> registrationBean = new FilterRegistrationBean<>(logFilter);
        registrationBean.setOrder(SECOND);
        return registrationBean;
    }
```

`FilterConfig` 파일에서 setOrder 함수를 사용하여 필터의 진행 순서를 지정해 줍니다.

로깅 전략에서 예측 가능한 에러(커스텀한 에러) 에 대해서는 info레벨로 출력하기로 했기 때문에

```java
@ExceptionHandler(BaseException.class)
    public ResponseEntity<ExceptionResponse> handleBaseException(final BaseException e) {
        final BaseExceptionType baseExceptionType = e.exceptionType();
        final ExceptionResponse exceptionResponse = new ExceptionResponse(baseExceptionType.errorCode(), baseExceptionType.errorMessage());

        MDC.put("jsonResponse", exceptionResponse.toString());
        return ResponseEntity.status(baseExceptionType.httpStatus()).body(exceptionResponse);
    }
```

`ControllerExceptionHandler` 에서 warn으로 처리하지 않고 mdc에 값을 담아 filter에서 로그를 출력하도록 구현하였습니다.

### 논의하고 싶은 부분들

- 환경 별(local, dev, prod) 로그를 다르게 관리하고 싶은데 계속 실패하였습니다.. 함께 논의해 주시면 감사하겠습니다..!
- 성공 로그에서 responseBody를 넣어주고 싶었는데 filter에서 `ServletResponse` 를 이용하여 구현해보려 했으나 실패했습니다..
- 로깅 전략에 대해서 각자의 생각이 있을 것 같아 전략에 대해 수정할 부분을 함께 논의하고 싶습니다.

2023-09-17 08:49 UTC, dooboocookie requested changes
안녕하세요 채채! 
고민 열심히 해주신 만큼 PR 보면서 많이 배웠습니다!!
전반적인 수정사항이랑 의견은 리뷰로 남겼고 같이 고민해봤으면 좋겠다 하신 내용에 대해서 따로 적어보겠습니다!!

### 환경 별(local, dev, prod) 로그를 다르게 관리하고 싶은데 계속 실패하였습니다.. 함께 논의해 주시면 감사하겠습니다..!

- 제가 이부분에 대한 지식은 많이 없어서 정확하게 설명은 못드리겠습니다.
- 근데 좀 찾아 본 결과 로그에도 프로필 전략이 통하던데, 혹시 시도해보셨는지요!!
- https://rutgo-letsgo.tistory.com/118

### 성공 로그에서 responseBody를 넣어주고 싶었는데 filter에서 ServletResponse 를 이용하여 구현해보려 했으나 실패했습니다..

- 일단 ServletResponse에서는 해당 바디가 PrintWriter 객체에 써진다고 합니다.
- 그래서 이미 써진 값을 String으로 다시 변환하긴 힘들고,
- Response를 래핑해서 값이 써질 때 캡쳐를 해야된다고 하더라구요.
- 아직 명확한 방법에 대해서 고안하지는 않았지만 가능은 할 것 같은데, 응답을 로깅할 필요가 있는지부터 한번 살펴볼까용??

### 로깅 전략에 대해서 각자의 생각이 있을 것 같아 전략에 대해 수정할 부분을 함께 논의하고 싶습니다.
- 일단 저는 info(보편적 로그) 로그들의 가독성을 높여야할 것 같습니다.
- 제가 생각하는 보통 수준의 로그는 이렇습니다.
  - 각 요청별로 시작과 끝이 명화해야한다.
  - 그 요청에 대한 MDC로 집계한 정보가 마지막에 표시되어야한다.
- 그래서 꼭 info레벨만 찍을 필욘 없을 것 같기도합니다.

```
[쓰레드 식별자] [로그레벨] [시간]: =시작=
[쓰레드 식별자] [로그레벨] [시간]: 메세지...
[쓰레드 식별자] [로그레벨] [시간]: 쿼리문
[쓰레드 식별자] [로그레벨] [시간]: 메세지...
MDC 출력
[쓰레드 식별자] [로그레벨] [시간]: =종료=
```
이런식이였으면 좋을 것 같은데, 채채 생각은 어떠신가용?
그래서 현재 INFO 레벨의 로그는
```
{
  message:...
  timestamp:...
}
```
이런식의 출력이 약간은 가독성이 떨어지는 것 같습니다!

저는 모르는 개념이 많아서 이것저것 찾아보면서 리뷰했더니 리뷰가 약간 오래걸렸네요 ㅠㅠㅠ

2023-09-17 11:50 UTC, dooboocookie requested changes
추가 리뷰가 있습니당

2023-09-17 11:50 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/LogFilter.java
> +public class LogFilter implements Filter {
P2:
일단 이번 피알에서 구현된 필터들이 전역적으로 사용되는 필터들이라 common에 위치한 것은 매우 동의합니다.

하지만 common 패키지 바로 밑 레벨에 있는 것은 한번 더 생각해주셨으면 좋겠습니다.

![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/3c175f3b-1f79-46e1-b37d-edb82a3c1e02)

제 생각엔 어쩌면 presentation 레이어 영역이에 해당이 될 것 같은데 혹시 채채는 어떻게 생각하시나요??

2023-09-17 11:50 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/config/FilterConfig.java
> +    FilterRegistrationBean<LogFilter> logFilter() {
P2:
메서드의 접근 지정자 설정 부탁드립니다

2023-09-17 15:25 UTC, kokodak requested changes
안녕하세요 채채! 고생하셨습니다.

코드 리뷰를 통해 개선하면 좋아보이는 점과 궁금한 점들을 남겨놓았어요.

다만 아직 이 PR이 불완전한 내용을 담고 있어서(로그백 관련), 제 코멘트에 대한 답이 모두 달려도 아직까지는 Merge가 되면 안될 것 같네요.

채채가 PR 마지막에 남겨주신, 논의할 부분들은 같이 얘기 나눠보는 것으로 하죠!

MDC 같은 좋은 내용 가져와주셔서 감사하고, 얼른 PR의 내용이 보강되어서 좋은 로깅 기능이 들어왔으면 좋겠네요!

2023-09-17 15:25 UTC, kokodak commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +        log.warn("error = {}", exceptionResponse);
이런 친구들은 MDC에 넣지 않는 이유는 무엇인가요?

2023-09-24 04:48 UTC, zillionme reviewed
채채 늦은 코드리뷰 미안합니다
전반적으로 이해하기 쉬운 코드였던 것 같습니다.
mdc가 적용된 xml파일이 없는 것을 보니 실제로 동작하는 로깅은 아닌가요?(파일로 저장되거나 하는 등으로요)
그리고 responseBody관련해서는 ContentCachingResponseWrapper를 사용해서 chain.doFIlter하기전에 response를 캐싱해놓고, 응답을 처리할 때, 캐싱해둔 response를 활용하는 방법도 있을 것 같습니다.

2023-09-24 04:48 UTC, zillionme commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +        log.warn("error = {}", exceptionResponse);
같은 부분이 궁금합니다

2023-09-24 04:48 UTC, zillionme commented on backend/src/main/java/com/now/naaga/common/LogFilter.java
> +    }
P4: 동일하게 MDC필터와 LOG필터가 하는 일의 차이점이 뭔지 잘 모르겠습니다.
MDC필터로 모든 문제를 해결해도 될 것 같습니다.

2023-09-24 05:26 UTC, zillionme requested changes
루카, 코코닥의 리뷰와 공통된 부분이 많아서, 공통된 리뷰는 달지 않았습니다.
해당 리뷰에 대한 변경이 완료되면 approve하겠습니다.

2023-09-25 07:27 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/LogFilter.java
> +            throws IOException, ServletException {
앗 수정하겠습니다~!

2023-09-26 06:51 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/LogFilter.java
> +    }
음 일단 로그가 찍힐때 그동안 mdc 에 담겨있었떤 값이 출력되게 됩니다. 로그를 따로 찍지 않고 mdc 만 출력하는 방법이 없어서 (제가 모르는거일수도..)mdc에 담고 로그로 값을 하나 넣어서 출력하는 식으로 구현했습니다..ㅜㅜ 혹시 로그로 찍는것이 아닌 mdc 로만 값을 담아서 로그로 출력하는 방법 을 아신다면 알려주세요..!

2023-09-26 06:54 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/QueryInspector.java
> +    }
db 로그에 대해서도 고민해보았는데 또 고민이 필요할것같아서 일단 이번 pr 에서는 진행하지 않고 다음 pr 에서 리팩토링 하는것은 어떨까요? 지금 pr 이 너무 길어지고 있어서 새로운것을 도전하기가 사실 두려운 상태입니다만..ㅠ,ㅠ

2023-09-26 06:55 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/config/FilterConfig.java
> +    }
꼼꼼스 감사합니다

2023-09-26 06:56 UTC, chaewon121 commented on backend/src/main/resources/info-appender.xml
> +            <timestampPattern>yyyy/MM/dd HH.mm.ss.SSSSSS</timestampPattern>
좋은 의견이네요 반영하겠습니다!

2023-09-26 06:57 UTC, chaewon121 commented on backend/src/main/resources/info-appender.xml
> +            <totalSizeCap>5GB</totalSizeCap>
음 그럼 루카는 어느정다 적당하다고 판단이 되시나요!? 메모리 관련 부분에선 전 전혀 감이 안와서..ㅠㅠ 현재 저희 어플의 사용량과 서버 상태를 고려해서 수정해야할 부분이라고 생각하긴 하다만.. 함께 고민해주시면 감사하겠습니다!

2023-09-26 06:57 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/MdcFilter.java
> +    }
인정합니다..! 반영했었는데 이것저것 만지다가 지웠나봐요 ㅠㅠ 바로 반영하겠습니다~!

2023-09-26 07:43 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +        log.warn("error = {}", exceptionResponse);
음 일단 로그가 찍힐때 그동안 mdc 에 담겨있었떤 값이 출력되게 됩니다. 로그를 따로 찍지 않고 mdc 만 출력하는 방법이 없어서 (제가 모르는거일수도..)mdc에 담고 로그로 값을 하나 넣어서 출력하는 식으로 구현했습니다..ㅜㅜ 혹시 로그로 찍는것이 아닌 mdc 로만 값을 담아서 로그로 출력하는 방법 을 아신다면 알려주세요..!

2023-09-26 07:51 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +    }
없습니다 삭제하겠습니다!

2023-09-26 07:58 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/QueryCounter.java
> +public class QueryCounter {
석사따러 대학원갑니다

2023-09-26 08:00 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
> +            System.out.println("sortBy: " + sortBy);
지우는걸 잊었네요.. 지우겠씁니답 ㅠㅠ

2023-09-27 06:20 UTC, chaewon121 reviewed
## 변경사항

### 의견 반영 사항

1. 컨벤션 및 final 적용(여러가지를 시도해보면서 제대로 지키지 못했던 부분 사과드립니다..ㅠㅠ)
2. mdc 필터 제거
3. MDC.clear() 추가하여 스레드 환경 비워주기
4. TimePattern 수정

### 전략 변경 사항

1. 공통 의견으로 mdc로 출력하는것과 log로 출력하는 것의 차이를 모르겠다는 의견이 많았습니다.</br>
   일단 제가 mdc로 값을 담고 그 값중 하나를 log로 출력하게된 이유는 mdc에 담긴 값을 로그로 출력하기 위해서는</br>
   로그안에 메세지 하나를 추가해서 출력하는 부분이 있어야 mdc에 담긴 값과 함께 출력이 되기때문에 반강제로 그렇게 코드가 구현되었습니다..</br>
   (로그 출력시 반드시 메세지를 입력해야함)</br>
   그래서 이부분에 대해서 전략을 다음과 같이 변경하였습니다.</br>

#### 기존 info 전략:</br>

```json
   {
  "jsonResponse": "ExceptionResponse{code=101, message='헤더 정보가 유효하지 않습니다.'}",
  "method": "GET",
  "queryCount": "0",
  "time": "9ms",
  "request_id": "ed9a0133-31bf-4998-af44-3d8bb7d313f7",
  "uri": "/ranks/my",
  "message": "level: info",
  "timestamp": "2023/09/07 16.07.06.557000"
}
```

#### 변경된 info 전략: (성공 응답)</br>

```json
{
      "request_id": "9abac258-6fb4-4c6b-be36-f8a274e93a8a",
      "level": "INFO",
      "message": "uri: /ranks/save, method: POST, time: 339ms, queryCount: 2",
      "timestamp": "2023/09/27 15:17:56.876000"
}
```

#### 변경된 info 전략: (실패 응답)</br>

```json
{
      "request_id" : "51328cf9-c70e-4b73-b152-28d3a93301c5",
      "jsonResponse" : "ExceptionResponse{code=215, message='파일 저장하다 문제가 발생했습니다.'}",
      "level" : "INFO",
      "message" : "uri: /places, method: POST, time: 238ms, queryCount: 3",
      "timestamp" : "2023/09/27 15:18:50.157000"
}
```
-> 실패응답은 추가로 jsonResponse로 실패응답을 담습니다. </br>
- 원래는 request_id, uri, method, time, queryCount 를 모두 mdc값에 담아서 출력하는 식으로 하였지만 위의 문제로 인하여</br>
  저 값을 하나의 문자열로 만들어서 log의 메세지로 출력하고 request_id 하나만 mdc로 관리하는 방안으로 수정하였습니다.</br>
  request_id는 요청이 들어오면 바로 생성되어 그 스레드동안 유지가 되어야하는 값이기 때문에 이 부분은 mdc로 관리가 되는것이</br>
  맞다고 판단하였습니다!</br>
- 각 레벨을 출력하는 요소도 추가되었습니다.

2. 환경 분리
   local 에서는 콘솔로, dev와 prod환경에서는 각레벨의 파일로 관리가 되도록 환경 분리 설정을 하였습니다.</br>
   콘솔이나 파일에서 출력되는 로그의 패턴은 동일하게 하였습니다.</br>

### 주신 전략의견에 대한 답변

로깅 전략에 대해서 좋은 의견을 주셨습니다..! </br>
함께 고민해주셔서 감사합니다.. </br>
하지만 제 역량으로는 원하는데로 로깅을 커스텀하기가 쉽지 않더군요.. </br>
로그로 출력하는것과 mdc로 출력할때의 순서조차 잘 컨트롤이 되지 않습니다..</br>
그래서 일단 주신의견을 반영하지는 못하였습니다.</br>
일단 현재 pr이 오래된 이슈이기도하고 하는일이 많은 pr이라는 생각이 들어서</br>
추가적으로 수정하고싶은 부분이 있다면 새로 이슈를 파서 리팩토링하는 방안을 제안하고 싶습니다..!</br>

2023-09-28 11:05 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/QueryCounter.java
> +public class QueryCounter {
그건 안됩니다...

2023-09-28 11:08 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +        log.warn("error = {}", exceptionResponse);
저도 채채 의견이랑 비슷한데요 모든 것을 mdc에 담아서 관리할 필요는 없다고 생각해요.
에러같은 것은 발생 시점에 로그를 찍는게 조금 더 직관적인 것 같아요. 에러 같은 경우에는 로그 레벨도 다를 수 있으니까요!

2023-09-28 11:40 UTC, dooboocookie commented on backend/src/main/resources/info-appender.xml
> +            <timestampPattern>yyyy/MM/dd HH.mm.ss.SSSSSS</timestampPattern>
이부분이 적용이 안되어있는 xml이  존재하는데 혹시 추가 적용 가능하실까요?

2023-09-28 11:41 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/LogFilter.java
> +public class LogFilter implements Filter {
이 리뷰에 대해서 어떻게 생각하시나요? ㅠㅠ

2023-09-28 11:42 UTC, dooboocookie approved these changes
채채 정말 고생 많으셨어요.
로깅관련해서 팀의 전반적인 이해도가 낮았는데, 채채 PR로 다들 이해를 끌어올릴 수 있었던 것 같아요.

몇가지 리뷰가 적용이나 답변이 안달려있긴한데요.
이미 해당 이슈에 대한 저희팀의 집중력이나 수명이 다 된 것 같아서 저는 approve 하겠습니다.

채채가 너무 고생 많으셨고, 앞으로 개발 해나가면서 개선할 사항이 있으면 같이 고민해봐용

2023-09-28 16:42 UTC, kokodak requested changes
안녕하세요 채채!

먼저 리뷰 반영해주시고, 프로필 환경에 따른 로깅 분리까지 멋지게 완수해주셔서 감사합니다.

워낙 고생해주셔서, 웬만하면 빠른 Approve 를 하려했지만, 몇가지 결정적인 문제점이 보여서 다시 한번 RC 요청을 보냅니다 🥲

MDC에 값이 들어있다고해서, 짜잔하고 자동으로 나오는게 아니더라구요. 이 부분에 대해서 리뷰를 좀 남겼고, 확인 부탁드립니다!

2023-09-28 16:42 UTC, kokodak commented on backend/src/main/resources/warn-appender.xml
> -                </mdc>
P1:

채채 혹시 현재 warn 레벨과 error 레벨에서 MDC에 담겨있는 값들을 전혀 사용하고 있지 않다는 사실을 아셨나요? 🥲

MDC를 도입한 가장 중요한 이유는, **각 요청에 고유 ID를 부여해서 로그를 묶어볼 수 있다는 것이라 생각하는데요.**

그러한 입장에서 봤을때, 지금의 로그 appender는 MDC를 도입한 이유가 사라지는 것 같아서, 수정 요청 드립니다.

2023-09-28 16:42 UTC, kokodak commented on backend/src/main/resources/error-appender.xml
>                          "stacktrace": "%exception{full}"
P2:

> {
>   "level" : "ERROR",
>   "timestamp" : "2023/09/29 00.40.27.305000",
>   "message" : "error = org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'sort-by' for method parameter type String is not present, stacktrace = org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'sort-by' for method parameter type String is not present\n\tat org.springframework.web.method.annotation.RequestParamMethodArgumentResolver.handleMissingValueInternal(RequestParamMethodArgumentResolver.java:218)\n\tat org.springframework.web.method.annotation.RequestParamMethodArgumentResolver.handleMissingValue(RequestParamMethodArgumentResolver.java:193)\n\tat org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:114)\n\tat org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:181)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:148)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat com.now.naaga.common.LogFilter.doFilter(LogFilter.java:36)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n",
>   "stacktrace" : ""
> }

제가 error를 고의로 발생시켜서 찍힌 로그를 수집해봤는데요. 위 내용이 error 레벨에 찍힌 로그 내용입니다.

message 부분을 보시면 아시겠지만, 현재 모든 스택 트래이싱 내용이 message 내부로 들어가고, stacktrace 에는 빈 문자열만이 들어가는 상황이네요.

`"stacktrace": "%exception{full}"` 이 xml 코드가 수정이 되어야할 것 같아요. 의도하는 동작을 하지 못하는 상황이라, 수정 부탁드립니다!!

2023-09-28 18:42 UTC, zillionme commented on backend/src/main/resources/info-appender.xml
>                  </mdc>
```
<mdc>
                    <fieldNames>
                        <request_id>request_id</request_id>
                        <uri>uri</uri>
                        <method>method</method>
                        <time>time</time>
                        <queryCount>queryCount</queryCount>
                        <jsonResponse>jsonResponse</jsonResponse>
                    </fieldNames>
</mdc>
```
부분은 삭제해도 될 것 같아요.
`<mdc/>`태그만 있어도 mdc 에 저장된 값들을 가져와서 로깅해준다는 게 코코닥 말 인 것 같습니다

2023-09-28 19:31 UTC, zillionme commented on backend/src/main/resources/error-appender.xml
>                          "stacktrace": "%exception{full}"
P1: 
위의 코코닥 문제를 해결해 봤는데요
1.
ControllerExceptionHandler에서
```
    private String getStackTraceAsString(Exception e) {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        e.printStackTrace(pw);
        return sw.toString();
    }
```
와
`        e.printStackTrace();
`
메서드를 삭제해주세요

2. 
```
log.error("error = {}\nstacktrace = {}",
                e.toString(), getStackTraceAsString(e));
```
부분을

`log.error(e.getMessage(), e);`로 바꿔주세요

3.
`"stacktrace": "%exception{full}"`
위의 코드는 작동하지 않는 것 같아요. 
` "stacktrace": "%throwable"` 또는 `"stacktrace": "%rEx"`

아래 로그백 공식문서의 Patterns 파트를 보면, 나와있습니다!
https://logging.apache.org/log4j/log4j-2.8.2/manual/layouts.html

4.
```
log.error("error = {} \n stacktrace = {}",
                e.toString(), getStackTraceAsString(e))
```
기존 코드는 
`public void error(String msg);`
는 Log a message at the ERROR level according to the specified format and arguments. 
로그백의 message패턴과 연결되고,


`log.error(e.getMessage(), e);` 로그의 메서드를 보면, 
```
     Log an exception (throwable) at the ERROR level with an
     accompanying message.
     @param msg the message accompanying the exception
     @param t   the exception (throwable) to log

    public void error(String msg, Throwable t);
```
로그백의 stacktrace 패턴과 연결되는 것 같습니다.

2023-09-29 06:46 UTC, dooboocookie commented on backend/src/main/resources/info-appender.xml
>                  </mdc>
# P2:
제 생각엔`<MDC/>` 태그도 크게 필요는 없을 것 같아요.

## 일단 저희가 MDC를 왜 사용하냐 라는 질문을 먼저 해야될 것 같은데요.

> mdc는 스레드 별로 로깅 컨테스트를 유지하기 때문에 스레드별로 로그를 관리하기가 편합니다. 또한 mdc를 사용하면 로그 출력 포멧을 지정할 수 있기때문에 원하는 메세지를 출력하고 관리하기에 매우 편리하기에 도입하게 되었습니다.

채채는 이렇게 말씀해주셨어요.
저는 여기서 ` 스레드별로 로그를 관리하기가 편합니다.` 이 말이 매우 공감이 됩니다. 
두번째 문장은 의미를 명확히 파악하기 힘들지만, 제 생각엔 로그백 인코더에서 패턴으로 MCD 키값을 사용할 수 있기에 편한 것 같습니다.

## 어떤 값을 MDC에 담아야 할까?

위의 목적과 같기 스레드별로 로그를 관리하기 위한 값만 담으면 될 것 같습니다.
현재로서는 저는 그 값이 `request_id`가 유일한 것 같아요.
다른 값들은 딱히 쓰레드 별로 할당할만한 값이라기 보단 특정 프로세스나 연산이 끝났을 때 그 순간 로그를 찍으면 되는 것 같습니다.

## 어떻게 출력해야 할까?

채채는 json을 가독성 떄문에 사용하셨다고 했는데, 일단 저는 저한테 좀 익숙한 형태로 테스트를 해봤습니다.
```xml
<included>
    <appender name="INFO_CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <file>./logs/info.log</file>
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>INFO</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
        <encoder>
            <charset>utf8</charset>
            <pattern>
                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %message %n
            </pattern>
        </encoder>
    </appender>
</included>
```
위와 같은 설정을 하면

![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/30ca8bd4-f8f6-4f2b-a70e-b5a17386a01c)

`%X`를 활용하여 request_id 즉 mdc에 할당된 값을 원하는 패턴화 채채가 원하는 위치에 사용할 수 있습니다.

일단 json형식으로 파싱해주는 여러 태그들을 포함해서 <mdc> 태그들에 대해서 채채도 별다른 설명이 없었고 팀원들도 즉각 이해하기 힘드러서 `%X`를 활용해보는 것이 어떨까요?

2023-09-29 06:48 UTC, dooboocookie commented on backend/src/main/resources/warn-appender.xml
> -                </mdc>
이 내용 관련해서는 위에서 언급한 바와 같습니다.
https://github.com/woowacourse-teams/2023-naaga/pull/318#discussion_r1340956727

2023-09-29 06:50 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +    }
# P1:

만약 StackTrace를 메세지에 넣고 싶으시다면`e.printStackTrace`사용하지 않는 방법을 찾아보시는것이 더 좋을 것 같아요.

2023-09-29 07:21 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/LogFilter.java
> +    private final static String LOG_FORMAT = "uri: {}, method: {}, time: {}ms, queryCount: {}";
수정 완료!

2023-09-29 07:32 UTC, dooboocookie commented on backend/src/main/resources/error-appender.xml
>                          "stacktrace": "%exception{full}"
# P3:

이레가 잘 정리해주신 것 같은데, 위 두 리뷰와 다르게 생각하는게 조금 있어서 리뷰를 더하자면
일단 고려를 해야될 것이 조금 있을 것 같습니다.

## 언제 ERROR 레벨의 로그가 나가나?
2가지 경우가 있을 것 같아요.
1. 예외를 핸들링하여 로그를 개발자가 작성한 경우
2. 예외가 핸들링 되지 않고 터진 경우

제 생각엔 저희가 지금 테스트 하는 경우가 1번 경우여서 로그 메세지에 getMessage를 담거나 getStackTrace를 담거나 이런식으로 해서 message 부분에 출력이 되는 것 같습니다.

해당 로그는 에러가 발생하므로서 터진 예외가 아니라 
`예외가 터지고` ->  `핸들링 돼서` -> `로그로 기록`
이런 상황인 것 같습니다.

## 예시
- 세팅
```xml
        <encoder>
            <pattern>
                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %throwable %n
            </pattern>
        </encoder>
```
### 1. 예외를 핸들링한 경우
![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/25e60951-ea69-49e1-99f7-0936985b3c27)

아무것도 찍히지 않음. 
핸들러에서 ` log.error("error = {} %n message = {}", e, e.getMessage())`를 해줘도
`%message`가 없어서 안찍히는거에요. 

### 2. 예외를 핸들링하지 않은 경우

![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/4d8051aa-7234-4496-9e3d-c4e3afa53a4b)

`%throwable`로 스택트레이스가 발생되는 것을 알 수 있죠.


## 어떻게 해야될까?

제 생각엔 현재 상태도 그렇게 이상해보이진 않아요.
왜냐하면 ERROR 레벨의 로그에 exception만 넘겨준다고 저희가 아직 정하게 없기 떄문에 stacktrace도 출력하고 메세지도 출력하는 것은 그럴 듯해보입니다. (그냥 아직 결정하지 못한 문제같아요)

`log.error(e.getMessage(), e);`
이레가 말씀하신대로 이렇게만 해도 해결이 돼요
![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/a044cc32-55cd-4509-89c3-2ed4d3072c6f)

이레가 보여주신 대로 logger.error()메서드에 익셉션을 두번쨰 인자로 받는 메서드가 정의가 되어있더라구요.

![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/598b30ca-5519-4b17-ae46-03e78402bdbb)

위 공식문서 자료에 따르면
일단 이레가 말씀해준 `%throwable` 과 `%exception` 둘 다 정상적으로 작동합니다.

# 결론
그래서 이 문제는 
에러로그를 `log.error(e.getMessage(), e);` 이렇게만 하면 해결될 문제 같습니다.
그 후에 error 레벨의 출력을 `%message`로 할 것인지 `%throwble`로 할 것인지 결정하면 될 것 같아요.

2023-09-29 07:37 UTC, dooboocookie requested changes
저는 앞전에 approve를 했는데, 
코코닥과 이레의 제보로 문제점을 발견했답니다.
그래서 추가적인 내용을 드릴게 있을 것 같아서 리뷰 추가하였습니다.

일단 책임감 없이 무지성 approve 한 점 모두에게 죄송합니다.

그래서 일단 체크리스트를 좀 만들어보겠습니다.

- [ ] 모든 로그에 request_id가 찍히도록 하였는가.
- [ ] 에러 로그에 stacktrace가 잘 찍히도록 하였는가.
- [ ] 모든 printStackTrace를 지웠는가
- [ ] 컨벤션을 모두 지켰는가
- [ ] common 패키지 내 패키지 정리 하였는가
- [ ] mdc의 저장하는 값들을 기준을 가지고 잘 짰는가? (제 의견은 request_id만 필요하다 생각)

2023-10-01 17:01 UTC, zillionme commented on backend/src/main/resources/info-appender.xml
>                  </mdc>
루카의 리뷰에
Outputs the Thread Context Map (also known as the Mapped Diagnostic Context or MDC) associated with the thread that generated the logging event. The X conversion character can be followed by one or more keys for the map placed between braces, as in %X{clientNumber} where clientNumber is the key. The value in the MDC corresponding to the key will be output.

If a list of keys are provided, such as %X{name, number}, then each key that is present in the ThreadContext will be output using the format {name=val1, number=val2}. The key/value pairs will be printed in the order they appear in the list.

If no sub-options are specified then the entire contents of the MDC key value pair set is output using a format {key1=val1, key2=val2}. The key/value pairs will be printed in sorted order.

See the [ThreadContext](https://logging.apache.org/log4j/log4j-2.8.2/log4j-api/apidocs/org/apache/logging/log4j/ThreadContext.html) class for more details.
해당 글을 참고하면 좋을 것 같습니다


[해석본]
로깅 이벤트를 생성한 스레드와 연관된 스레드 컨텍스트 맵(매핑된 진단 컨텍스트 또는 MDC라고도 함)을 출력합니다. X 변환 문자 뒤에는 중괄호 사이에 배치된 맵의 키가 하나 이상 올 수 있습니다(예: %X{clientNumber}에서 clientNumber가 키인 경우). 키에 해당하는 MDC의 값이 출력됩니다.

X{이름, 번호}와 같이 키 목록이 제공된 경우 ThreadContext에 있는 각 키는 {이름=val1, 번호=val2} 형식을 사용하여 출력됩니다. 키/값 쌍은 목록에 표시된 순서대로 인쇄됩니다.

하위 옵션이 지정되지 않은 경우 MDC 키 값 쌍 세트의 전체 내용이 {key1=val1, key2=val2} 형식을 사용하여 출력됩니다. 키/값 쌍은 정렬된 순서로 인쇄됩니다.

자세한 내용은 ThreadContext 클래스를 참조하세요.

2023-10-01 17:12 UTC, zillionme commented on backend/src/main/resources/error-appender.xml
>                          "stacktrace": "%exception{full}"
루카! 
**예외를 handling하기 때문에, 로그백의 %message 패턴에 예외 내용이 찍히지 않는다는 말이 무슨 뜻인지 잘 이해가 가지 않습니다ㅜ**
Handler에서 발생한 예외를 핸들링할 때, 예외 객체가 그대로 핸들러로 넘어오기 때문에,
핸들링하기 때문에 예외가 기록되지 않는다는 의견에 대해서는 이해가 어렵습니다.

다만, 
1. log.info(String str)를 통해 발생한 에러의 메시지를 찍으면, %message에 정상적으로 로깅한 문자열이 저장되는 것으로 알고 있습니다.
2. log.info(String message, Throwable throwable)에서 에러 객체 자체를 넘겨줌으로써, 로그백 패턴의 stacktrace= %throwable혹은 %exception에 에러 객체의 스택트레이스를 출력할 수 있는 것으로 이해했습니다.

추가적으로, 
> error 레벨의 출력을 %message로 할 것인지 %throwble로 할 것인지 결정하면 될 것 같아요.
라는 말은 굳이 스택트레이스를 로깅할 필요성을 느끼지 못하기 때문에, 둘다 출력할 것인지 message만 출력할 것인지 결정하자는 말씀이신가요?

2023-10-02 04:48 UTC, dooboocookie commented on backend/src/main/resources/error-appender.xml
>                          "stacktrace": "%exception{full}"
> 예외를 handling하기 때문에, 로그백의 %message 패턴에 예외 내용이 찍히지 않는다는 말이 무슨 뜻인지 잘 이해가 가지 않습니다

```xml
        <encoder>
            <pattern>
                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %throwable %n
            </pattern>
        </encoder>
```
이때  로그를 메세지에 넘겨주는 식으로 찍었기 때문에 %throwable %exception 이렇게 해도 안찍힌다는 이야기였습니당

>Handler에서 발생한 예외를 핸들링할 때, 예외 객체가 그대로 핸들러로 넘어오기 때문에,
핸들링하기 때문에 예외가 기록되지 않는다는 의견에 대해서는 이해가 어렵습니다.

이것도 위 답변과 마찬가지로
예외가 터진 것에 대한 로그가 아니라
터진 것에 대한 핸들링에서 개발자가 직접 작성한 `메세지`의 에러기 때문에 `%message`를 써야 찍힌다는 이야기였습니다.

> log.info(String str)를 통해 발생한 에러의 메시지를 찍으면, %message에 정상적으로 로깅한 문자열이 저장되는 것으로 알고 있습니다.

네 맞습니다.

> log.info(String message, Throwable throwable)에서 에러 객체 자체를 넘겨줌으로써, 로그백 패턴의 stacktrace= %throwable혹은 %exception에 에러 객체의 스택트레이스를 출력할 수 있는 것으로 이해했습니다.

네 맞습니다.

>> error 레벨의 출력을 %message로 할 것인지 %throwble로 할 것인지 결정하면 될 것 같아요.

>라는 말은 굳이 스택트레이스를 로깅할 필요성을 느끼지 못하기 때문에, 둘다 출력할 것인지 message만 출력할 것인지 결정하자는 말씀이신가요?

스택 트레이스의 제가 필요성을 못느낀게 아니라,
팀적으로 어떻게 찍을지 정하자는 말이였어요.
error 레벨의 로그는 전부 어떤식으로라도 에러를 매개변수로 넣어줄 건지,
아니면 메세지도 보여줄 수 있게 만들것인지
예를 들면 밑에와 같이 찍을 수 있겠죠?
```xml
        <encoder>
            <pattern>
                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %message %n %throwable %n
            </pattern>
        </encoder>
```

2023-10-02 09:34 UTC, zillionme commented on backend/src/main/resources/error-appender.xml
>                          "stacktrace": "%exception{full}"
완벽한 정리네요 감동좔좔

2023-10-03 13:18 UTC, chaewon121 commented on backend/src/main/resources/error-appender.xml
>                          "stacktrace": "%exception{full}"
log.error(e.getMessage(), e); 이렇게 수정하고 추후에 논의 후 수정해봅시다!

2023-10-03 13:46 UTC, chaewon121 commented on backend/src/main/resources/info-appender.xml
>                  </mdc>
request_id만 mdc가 관리하도록 수정하였습니다!

2023-10-03 14:09 UTC, chaewon121 reviewed
여러분 안녕하세요! 3번째 pr작성입니다! 변경사항 위주로 작성하였습니다.

먼저 위 댓글에서 남겨준 체크리스트에 모두 체크가 되도록 수정하였습니다.

- [x] 모든 로그에 request_id가 찍히도록 하였는가.
- [x] 에러 로그에 stacktrace가 잘 찍히도록 하였는가.
- [x] 모든 printStackTrace를 지웠는가
- [x] 컨벤션을 모두 지켰는가
- [x] common 패키지 내 패키지 정리 하였는가
- [x] mdc의 저장하는 값들을 기준을 가지고 잘 짰는가? (제 의견은 request_id만 필요하다 생각)

1. json 방식 제거
- 제거 이유: 일단 어렵습니다.. 제이슨 컨밴션을 지키기 위해 mdc에 값을 담기도 하고 등등 하였는데
여러분들한테 익숙하지도 않고 (저 또한) 하다보니 굳이 라는 생각이 들더군요..? 그래서 제거하였습니다!

2. 로깅 전략 수정
- info 같은 경우는 제가 담고싶었던 queryCount,time,uri 등등을 스트링으로 만들어 메세지로 출력하였습니다.
- 저희가 예상한 오류에 대해서 mdc에 값을 담기만 하였는데 그 코드는 삭제되었고 info로 예외 메세지를 출력하였습니다.
  - 즉, 예상한 오류는 info가 두번찍히게 되는것!
- warn, error, info의 로그 출력 로직을 통일하였습니다! 

3. mdc에서는 request_id 만 관리하게 하였습니다!
4. 에러로그에 대해서 log.error(e.getMessage(), e); 로 수정하였습니다!


### info 로그(정상 응답)
```xml
[2023-10-03 23:01:15.532] [INFO ] [69df0afb-b99c-485d-80ac-80e29e7d96db] [LogFilter] - uri: /ranks/save, method: POST, time: 108ms, queryCount: 2 
```

### info 로그(예외 응답)
```xml
[2023-10-03 23:02:12.798] [INFO ] [7253ff43-a2e6-4541-a2e9-12cbd8257d35] [ControllerExceptionHandler] - error = ExceptionResponse{code=215, message='파일 저장하다 문제가 발생했습니다.'}
[2023-10-03 23:02:12.807] [INFO ] [7253ff43-a2e6-4541-a2e9-12cbd8257d35] [LogFilter] - uri: /places, method: POST, time: 139ms, queryCount: 2 
```

### error 로그 (핸들링 못하는 에러)
```xml
[2023-10-03 23:04:22.570] [ERROR] [4eaa2c71-22c0-4638-a6d3-977b04810558] [o.a.c.c.C.[.[.[.[dispatcherServlet]] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: com.now.naaga.auth.exception.AuthException] with root cause
com.now.naaga.auth.exception.AuthException: null 어쩌고 등등
```


### error 로그 (1000 에러)
```xml
[2023-10-03 23:05:28.086] [ERROR] [d58d50a3-ad03-4e60-8a7f-c58efa5e4904] [ControllerExceptionHandler] - Required request parameter 'email' for methodparameter type String is not present
```

2023-10-03 16:25 UTC, dooboocookie approved these changes
위 두 의견 남겼는데 강한 주장은 아니고 약한 주장입니다!!
전 진짜 이젠 어프루브

2023-10-03 16:25 UTC, dooboocookie commented on backend/src/main/resources/error-console.xml
> +                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %message %n
P5:
```suggestion
                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %exception %n
```
error레벨의 로그는 앞으로 에러만 찍을 것 같긴해서 이렇게 해보시는건 어떤가요??
지금도 로깅은 매우 잘찍혀요 현재 채채가 한것과 같이 `%message`를 찍으면
`log.error(e.getMessage(), e)`이 부분에서 `%mesage`에 대해서는 1번쨰 매개변수가 찍히고 스택트레이스가 뒤따라 찍히더라구요.

그래서 `log.error("내용~~")`이런식으로 메세지를 직접 찍는 방식에도 대응이 가능한 방식같아서 지금도 매우 만족합니다!!
<img width="1380" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/79090478/acab71b1-8ff4-42a5-b58c-a3bbe8752b4e">

2023-10-03 16:25 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +        log.warn("error = {}", exceptionResponse);
P4:

이부분을 따로 warn레벨로 설정하신 이유가 있으실까요?
이것또한 사용자의 요청이 잘못돼서 바인딩이 실패한 에러들이 대부분인데요.

인포로 내리고 어떤 예왼지 스택트레이스를 보여주는 것은 어떠신가요??

강한 주장은 아닙니다. 충분히 응답만 보고도 어떤 예왼지 알 수 있을 거에요.
```suggestion
        log.info(exceptionResponse, e);
```

2023-10-03 18:52 UTC, kokodak approved these changes
고생 많으셨습니다 채채 🥲

로깅이 상당히 어려운 주제였을텐데, 잘 마무리 해주신 것 같아요!!

최대한 양질의 코드리뷰를 남기려고 꼼꼼하게 보려다보니, 의도치않게 채채를 너무 힘들게 한 것 같기도해서 죄송스럽네요 ㅠㅠ..

그래도 잘 반영해주시고 PR 코멘트에 작업 내용들을 함께 남겨주셔서 정말 감사합니다!!

저도 위에 루카랑 비슷한 의견이라 따로 리뷰를 남기진 않을게요!

이제 더이상의 문제점은 보이지 않아서 저는 이만 Approve 하겠습니다!! 정말 고생 많으셨어요 👏👏👏

2023-10-04 04:08 UTC, zillionme approved these changes
고생하셨어요 채채. 두가지 고치면 좋을 점 남겨두었으니 한번 확인해보시면 좋을 것 같아요!
이만 저도 approve하도록 하겠습니다

2023-10-04 04:08 UTC, zillionme commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +        log.warn("error = {}", exceptionResponse);
루카 말에 동의합니다
log.info(exceptionResponse, e);
가 좋은 것 같습니다

2023-10-04 04:08 UTC, zillionme commented on backend/src/main/resources/error-console.xml
> +                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %message %n
```suggestion
                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %message %throwable %n
```
로 바꾸는 것은 별로인가요?
이렇게 하면
`log.error(e.getMessage(), e);`
의 e.getMessage()부분은 %message로 들어가고,
e부분은 %throwable
로 들어가게 됩니다

2023-10-04 05:57 UTC, dooboocookie commented on backend/src/main/resources/error-console.xml
> +                [%date{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%X{request_id}] [%logger{1}] - %message %n
저도 이거 좋은 것 같아요. 
예외 상황의 경우 메세지가 두번 찍히긴 하겠지만 보기엔 이게 편할 것 같긴해요

2023-10-04 09:00 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +        log.warn("error = {}", exceptionResponse);
저부분도 우리가 잡은 에러이군요 warn이 아니라 info 레벨이 맞는것같네요! 이부분으 수정 후 머지하겠습니다!

2023-10-04 09:07 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +        log.warn("error = {}", exceptionResponse);
log.info(exceptionResponse, e); 이렇게는 동작하지 않습니다 string, 그리고 그안에 값을 담는 형태여야하는데 "error = {}", exceptionResponse 이 형태는 마음에 안드시는것인지..!?

2023-10-04 09:09 UTC, merged