feat: 로그아웃 기능 구현
woowacourse-teams/2023-naaga pull request #341
Opened 2023-09-16 10:56 UTC by krrong

## 📌 관련 이슈
- closed: #327 

## 🛠️ 작업 내용
로그아웃 기능 구현

## 🎯 리뷰 포인트
### 다이얼로그
로그아웃 버튼을 클릭하면 다이얼로그가 뜨면서 로그아웃 확인을 진행합니다. 이 때 사용하는 다이얼로그는 인게임의 힌트, 포기 에서 사용하는 다이얼로그와 같아요.

### 액티비티 이동 흐름
로그아웃이 성공적으로 된 경우 아래 코드를 통해 이전에 백스택에 들어가있던 액티비티들을 모두 없애주도록 했고, 로그인 화면에서 뒤로가기를 클릭하면 앱이 종료됩니다.
```kotlin
fun getIntentWithTop(context: Context): Intent {
    return Intent(context, LoginActivity::class.java).apply {
        addFlags(FLAG_ACTIVITY_NEW_TASK)
        addFlags(FLAG_ACTIVITY_CLEAR_TASK)
    }
}
```

### Body가 null인 경우
현재 보낸 요청이 DELETE 요청인지 확인한 뒤 DELETE 요청일 때 body가 null인 경우는 정상적으로 반환되게 했어요.  
code가 204임을 확인하지 않고 DELETE 요청인지 확인한 이유는 돌아오는 상태코드에 의존적이고 싶지 않아서 입니다.  
만약 반환되는 상태 코드가 바뀌게 되면(그럴 일은 거의 없겠지만) 처리로직이 변경되어야 하니까요. 하지만 현재 코드도 DELETE요청이 아닌 다른 요청으로 바뀌게 된다면 똑같이 바뀌어야 하는 것은 마찬가지입니다. 

## ⏳ 작업 시간
추정 시간: 2h  
실제 시간: 4h  

body가 Null인 요청을 어떻게 처리할까, 로그아웃 시 어떻게 하면 UX가 좋아질까에 대해 고민을 많이 했습니다.

2023-09-16 16:11 UTC, hyunji1203 requested changes
크롱🦖 고생많았어요~!!!
로그아웃 잘 구현해주셨네요~
null처리랑 액티비티 이동 흐름에 대해 많이 고민한게 느껴져서 너무 좋았습니다!
리뷰를 하면서 오히려 제가 꿀팁 많이 얻어가네요ㅎㅎ
자잘한 리뷰 몇개 남겼으니 확인 부탁드려요~!!

2023-09-16 16:11 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
> +        return withContext(dispatcher) {
##### P3
`return`이 없어도 될 것 같아요! 혹시 return을 넣은 이유가 있을까요?

2023-09-16 16:11 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/util/ResponseUtil.kt
> +        if (this.isDelete()) { return Unit as T }
null처리👍

2023-09-16 17:55 UTC, krrong commented on android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
> +        return withContext(dispatcher) {
위 코드를 보고 그대로 따라 쓴 것 같아요! 삭제했습니다~!

2023-09-16 17:56 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
> +            title = getString(R.string.logout_dialog_title),
원래 '로그아웃' 만 있었는데 언제 저렇게 들어갔는지 모르겠네요..!ㅋㅋㅋㅋ  
반영했습니다! 🤠

2023-09-17 08:30 UTC, hyunji1203 commented
크rrr뤙 리뷰 반영 확인했습니다🦖
고생많으셨고 그럼 이만 머지하도록 하겠습니다~!!!

2023-09-17 08:30 UTC, hyunji1203 approved these changes
크rrr뤙 리뷰 반영 확인했습니다🦖
고생많으셨고 그럼 이만 머지하도록 하겠습니다~!!!

2023-09-17 08:31 UTC, merged