feat: 장소 좋아요 기능 도메인 설계 및 뼈대코드 작성
woowacourse-teams/2023-naaga pull request #344
Opened 2023-09-16 13:43 UTC by kokodak

## 📌 관련 이슈
- closed: #325

## 🛠️ 작업 내용
- [x] 좋아요 관련 도메인 설계
- [x] 좋아요 관련 뼈대 코드 작성
- [x] 좋아요 테스트 픽스쳐와 테스트용 빌더 생성

## 🎯 리뷰 포인트

### 최종 ERD
![image](https://github.com/woowacourse-teams/2023-naaga/assets/45879491/611f9098-2d30-46e4-ba6b-56380d7c3945)

- ERD와 동일한 도메인 구조를 가져갔습니다.

### 초반 ERD
![image](https://github.com/woowacourse-teams/2023-naaga/assets/45879491/0aa4548c-af58-40df-9fca-9a986bf4f227)

- 처음에는 위와 같이 테이블 설계를 진행하였습니다.
- `어떤 플레이어`가 `어떤 장소`에 좋아요를 눌렀는지 나타내는 테이블을 추가하였습니다.
- 장소 입장에서는 이 장소에 좋아요가 `몇개`눌렸는지가 매우 중요하고 자주 조회되는 정보입니다.
- 그럴 때 마다 밑의 집계 쿼리를 날려서 찾아야 합니다.
```sql
SELCET count(*) FROM place_like WHERE place_id = ?;
```
- 하지만, 좋아요의 `모든 유저`가 `모든 장소`에 대해서 누른 정보들을 갖고 있기 때문에 데이터량이 매우 많을 것으로 예상됩니다.
- 따라서 조회 부분에서 상당한 성능의 문제가 우려되어 역정규화를 진행하였습니다.

### 개선 ERD
![image](https://github.com/woowacourse-teams/2023-naaga/assets/45879491/34e4872b-7269-4058-ba00-9ced8d404be2)

- 따라서 좋아요를 등록하거나 취소하는 과정에 통계 테이블에도 `+1`,`-1`과정이 포함되게 됩니다.

## ⏳ 작업 시간
추정 시간:   3시간
실제 시간:   3시간

2023-09-28 02:06 UTC, chaewon121 reviewed
루카 코코닥 안녕하세요~!테이블 설계 어려우셨을텐데 잘 짜주셨네요~! 궁금한 점이 있어 이부분에 대한 답변을 받으면 바로 approve 누르겠습니다~! 고생하셨습니다~! 테스트 빌더까지 꼼꼼하시군요

2023-09-28 02:06 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/placestatistics/PlaceStatistics.java
> +
likeCount를 place 테이블에 두지 않고 따로 테이블을 뺀 이유가 궁금합니다!

2023-09-28 02:06 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/common/builder/PlaceLikeBuilder.java
> +
불필요한 개행 삭제 부탁드립니당!

2023-09-28 02:06 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/common/builder/PlaceLikeBuilder.java
> +    private PlaceLikeRepository placeLikeRepository;
코코닥의 명작..!

2023-09-30 09:38 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/placestatistics/PlaceStatistics.java
> +
역정규화로 집계를 나타내는 컬럼이 빠졌다는 것은 위에서 설명이 되어있으니 왜 테이블로 뒀는지 설명드리겠습니다!!

2가지 관점에서 볼 수 있을 것 같은데요.
1. Place 테이블에 좋아요 집계까지 둔다면, Place 테이블의 수정이 좋아요가 한번 눌릴 때마다 일어나는데요. 이러면 각종 수정에서 조건문등으로 인해서 테이블의 락이 발생할 수 있을 것으로 우려되어 집계를 나타내는 테이블을 분리하였습니다
2. 현재로서는 place의 통계를 나타내는 컬럼이 `likeCount`만 있습니다.
하지만 통계를 나타내는 컬럼이 많아질 수록 순수하게 Place 정보를 나타내는 테이블과 통계를 나타내는 테이블로 분리를 할 수 있으므로 조금 더 확장성 있다고 볼 수 있을 것 같습니다.

2023-09-30 09:38 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/common/builder/PlaceLikeBuilder.java
> +
수정하겠습니다!!

2023-09-30 09:46 UTC, dooboocookie commented
채채 리뷰 감사합니다!!
잘 살펴봐주셔서 컨벤션 잘 지킬 수 있었어요!!👍

(추가로 Pn규칙 토대로 리뷰 부탁드리고 리뷰 완료 후 Approve나 Request Change 부탁드릴게요)

2023-09-30 09:47 UTC, dooboocookie approved these changes
채채 리뷰 감사합니다!!
잘 살펴봐주셔서 컨벤션 잘 지킬 수 있었어요!!👍

(페어로 작업한 결과라 저는 바로 Approve 눌렀습니다)
(추가로 Pn규칙 토대로 리뷰 부탁드리고 리뷰 완료 후 Approve나 Request Change 부탁드릴게요)

2023-10-01 08:30 UTC, zillionme requested changes
루카 코코닥 늦은 리뷰 죄송합니다.
오늘부터 D-n룰을 잘 지키도록 하겠습니다.
뼈대 코드가 깔끔하게 잘 짜여졌다고 생각하는데요, 그저 개인적인 궁금증을 두 개 남겨놓았습니다.
바로 머지해도 될 것 같습니다.

2023-10-01 08:30 UTC, zillionme commented on backend/src/main/java/com/now/naaga/placestatistics/PlaceStatistics.java
> +
특정 장소에 대한 좋아요 요청이 오면, 
1. placeId로 장소를 찾고
2. placeId와 좋아요를 누른 플레이어의 id로 playerlike 객체를 만들고 저장
3. placeId로 적합한 placestatistics를 조회한 후, 개수 update를 하는 흐름이 맞나요?

---
만약 위의 흐름대로 진행된다면
PlaceStatistics 테이블의 좋아요 수 객체는 PlaceLike테이블과 논리적인 연관관계는 있지만 직접적인 연관관계는 존재하지 않네요.
PlaceStatiscs의 좋아요 개수와 PlaceLike에 저장된 실제 좋아요 개수에 차이가 날 수도 있을까요?
= 데이터 정합성의 문제가 발생할 수도 있을까요?

또,  
placeLike에서 placeId를 인덱스로 달면, 쉽게 count를 조회해 올 수도 있을 것 같은데요.
이러한 문제들로 PlaceStatistics 테이블이 없다면, 장소 통계에서 좋아요 개수를 조회해올 때, 
placeStatisticsService.findPlaceStatisticsByPlaceId()라는 메서드가
내부적으로 PlaceLikeService.findPlaceLikeCountByPlaceId()라는 메서드를 사용할 것 같은데요.
여기서 성능적인 문제가 발생하나요?

정리하자면
1. 정합성 문제가 발생할 가능성이 있는지? (PlaceLike와 PlaceStatistics의 likeCount는 아무런 프로그래밍적인 관계가 없다)
2. PlaceStatistics 테이블을 없앴을 때, 발생하는 성능문제가 뭐가 있는지? 

가 궁금합니다.

2023-10-02 05:54 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/placestatistics/PlaceStatistics.java
> +
## 1번
트랜잭션을 잘 짜놓지 않으면 정합성 문제가 발생할 수 있습니다.
## 2번
PlaceStatistics를 제거하면 PlaceLike의 FK만으로는 인덱싱이 불가합니다.
PlaceLike에는 싫어요 타입도 담기기 떄문에
(FK, Type)으로 인덱스가 걸릴테고 Type은 일단 좋아요 싫어요 두 상태가 골고루 퍼져있는 값입니다. 인덱싱의 효율이 안나오는것으로 알고있어요.(확실하지 않음 리마큐참고)
그리고 원래는 없어도 될 인덱스 때문에 쓰기 성능도 저하될 수 있겠죠? 좋아요는 쓰기가 매우 빈번하게 일어날 수 있는 작업입니다
스태티스틱스를 하나올리는 작업이 더 간결할 것 같습니다.

2023-10-02 05:55 UTC, dooboocookie commented
이레!
Pn룰에 맞춰서 수정사항을 작성해주시거나 혹은 괜찮다 싶으면 어프루브로 해주세용!
RC인데 변경 요청사항이 없어서요!!

2023-10-02 07:29 UTC, chaewon121 approved these changes

2023-10-02 15:10 UTC, zillionme approved these changes
이만 approve 하겠습니다~

2023-10-02 21:47 UTC, merged