feat: 자동로그인 기능 구현 및 스플래시 분리
woowacourse-teams/2023-naaga pull request #346
Opened 2023-09-18 06:43 UTC by briandr97

## 📌 관련 이슈
- closed #321 

## 🛠️ 작업 내용
- [x] 인터셉터 로직 수정

## 🎯 리뷰 포인트
인터셉터에서 모든 요청을 가로채서 토큰을 넣어줍니다.
그리고 요청의 응답 또한 인터셉터에서 받아서 http 상태코드로 성공여부를 확인합니다.
401 실패시 리프래시 요청을 보내고 리프래시 요청을 통해 받아온 토큰을 다시 삽입하여 기존의 요청을 보냅니다.

여기까지는 기존의 제 설계와 현재 구현이 같습니다. 이 다음부터 달라지게 됩니다.
원래는 리프래시 토큰의 만료는 인터셉터에서 신경 쓰지 않으려고 했습니다.
스플래시에서 매번 앱을 실행할 때마다 강제로 리프래시를 시켜서 리프래시가 만료되는 경우를 만들지 않는 방법으로 생각했습니다.
이렇게 생각했던 이유는 인터셉터에서 LoginActivity를 실행시키는 것이 굉장히 부자연스럽다고 느꼈고 구현 또한 더 복잡해집니다.

위에서 설명한 것처럼 구현했었는데 백엔드의 api를 붙여보니 오류가 났고 오류가 났던 이유는, 서버에서 만료되지 않은 accessToken에 대한 리프래시 요청은 accessToken이 탈취당했다고 여겨 에러를 내려주기 때문입니다.
그래서 스플래시에서 매번 강제로 리프래시를 시키는 것이 불가능해졌습니다.

그래서 현재는 리프래시 api 호출에 대해서 성공하지 못하면 인터셉터에서 로그인 액티비티로 보내고 있습니다.
다만 `Intercepter`의 `intercept()`함수는 무조건적으로 `Response` 를 반환해야하기 때문에 로그인 액티비티로 보내더라도 실패한 response를 반환하는 형태입니다.

현재는 잘 작동하는 것을 확인했지만 앱 사용 중에 refresh토큰까지 만료되는 상황에 대해서는 테스트 가능한 상황을 만들기가 어려워 아직 여러번 테스트해보지는 못했습니다. 

## ⏳ 작업 시간
추정 시간:   1h
실제 시간:   5h
백엔드가 토큰을 관리하는 로직이 내 예상과 달라서 난관을 겪음.

2023-09-18 17:52 UTC, hyunji1203 requested changes
빅스! 고생 진짜 많으셨어요~~!
기존 구상했던 로직과 실제 구현 로직이 달라 힘드셨겠군요... 진짜 바쁜 와중에 다시 로직 바꾸느라 고생했습니다
몇가지 궁금증과 리뷰를 남겼으니 확인해주세요!

<img width="600" alt="KakaoTalk_Photo_2023-09-19-02-49-04" src="https://github.com/woowacourse-teams/2023-naaga/assets/83613106/bc343b10-22ed-49ee-9d01-542b341913a8">

<br> 그리고 현재 앱을 실행시켰을 때 <br>
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?  <br>
라는 에러 문구가 뜨면서 앱이 실행되지 않은 이슈가 발생하고 있어요🥲 <br>
바쁘시겠지만...이것도 확인해주면 감사드리겠슴다!!

2023-09-18 17:52 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
> +class AuthInterceptor() : Interceptor {
[P5]
아주 사소하지만ㅎㅎ `()` 은 지워도 될 것 같아요~

2023-09-18 17:52 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
> +
[P4]
해당 `startLoginActivity`로직이 `Interceptor` 클래스 내에 들어가 있어서 `NaagaApplication.context`를 받아와야만 하는 상황인 것 같아요! 그래서 이 때 `applicationcontext`를 받아오기 위해 `NaagaApplication`에 `context`를 `companion object`로 선언하였는데, 이 부분에서 `StaticFieldLeak` 경고가 뜨네요😂 
그렇다면 `startLoginActivity`을 `Application`의 함수로 뺴는 방법은 어떨까 생각을 해보았는데 맞는 방법인지 정말 모르겠네요..
이 부분에 대해서 빅스는 어떻게 생각하고 계신가요? 궁금합니다!

2023-09-18 17:52 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
> +            startLoginActivity()
`rankRepository.getMyRank()`를 실행 시킨 이유가 토큰이 유효한지 테스트 해보는 용도인가요? (정말 궁금해서 물어봄)

2023-09-20 18:24 UTC, briandr97 commented
수정이 조금 있었습니다. 설명드리겠습니다.

원래는 Interceptor에서 로그인 화면으로 보내는 작업까지 수행했습니다.
그런데 그럴 필요가 없다는 것을 깨달았습니다.
다음은 refreshToken의 만료가 일어나는 시점에 대한 설명입니다.

accessToken을 갱신하면 refreshToken도 함께 갱신됩니다.
우리는 accessToken을 짧은 주기로 갱신하는데 이 말은 즉슨 refreshToken도 짧은 주기로 갱신된다는 뜻이죠.
앱 사용중에 refreshToken의 만료가 발생하려면 사용자가 앱을 켜놓고 어떠한 서버통신도 하지 않고 refreshToken의 주기 동안 기다려야합니다.
이는 불가능에 가까우므로 사실상 refreshToken의 만료를 체크하고 로그인 화면으로 보내는 작업은 스플래시에서만 해도 충분하다고 판단했습니다.

그래서 뽀또가 리뷰로 남겨주었던 context를 사용하는 부분이나 앱을 켰을 떄 발생하는 오류는 모두 사라졌습니다.
* ()는 지워주었습니다.
* 스플래시에서 호출하는 api는 accessToken과 refreshToken의 만료를 체크하여 로그인 화면으로 보낼지 비긴 어드밴처 화면으로 보낼지에 대해 판단하기 위함입니다. 오늘 rank에 대한 api 통신이 오래걸리는 것으로 보여 statistics에 관한 요청으로 바꾸었습니다.

2023-09-20 21:03 UTC, hyunji1203 approved these changes
빅스~~~~~ 고생많으셨어요!!
로직 변경 부분이랑 자동 로그인 잘 동작 되는 것 까지 확인했습니다!
그리고 얘기해주신 refresh 갱신 관련 부분에 대해선 저도 공감합니다!
추가 리뷰에 남겼듯이 `NaagaApplication`에 대한 간단한 수정사항 말고는 더 이상 수정할 부분이 없는 것 같아 Approve 하겠습니다!
빅스가 `NaagaApplication` 부분 수정하시고 바로 merge 해주시면 됩니다~

2023-09-20 21:03 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/NaagaApplication.kt
> +        lateinit var context: Context
[P3]
현재는 쓰지 않는 함수와 변수인 것 같아 지워주시면 좋을 것 같습니다!ㅎㅎ

2023-09-23 06:28 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/NaagaApplication.kt
> +        lateinit var context: Context
지웠습니다!

2023-09-23 06:34 UTC, merged