fix: 나의 통계 조회 시 성능 저하 문제 해결
woowacourse-teams/2023-naaga pull request #364
Opened 2023-09-21 18:24 UTC by chaewon121

## 📌 관련 이슈
- closed: #356 

## 🛠️ 작업 내용
- [x] 문제 파악 후 DB에 날라가 횟수 수정
- [x] 가능하면 해당 로직의 개선점 정리

## 🎯 리뷰 포인트
### 상황
1. List<Game>을 PlayerId 로 조회 : 쿼리 1번
2. List<Game>에 대한 GameResult를 각각 조회 : 쿼리 N번
3. GameResult -> GameRecord 변환 과정에서 Game의 힌트 조회 : 쿼리 N번 (GameRecord에서 힌트의 정보가 필요하기 때문)

- 예시
  - 플레이어가 10번의 게임을 마쳤을때, </br> 1번의 상황으로 쿼리 1번, </br>2번의 상황으로 쿼리 10번, </br>3번의 상황으로 쿼리 10번이 발생하여</br>총 21개의 쿼리가 발생함
  
### 해결 방안
  - 두번의 조인 쿼리문을 작성하여 게임 결과를 가져올때 게임의 대한 모든 정보(힌트까지) 모두 조회하도록 쿼리를 작성하였습니다.

## ⏳ 작업 시간
추정 시간:   1시간
실제 시간:   1시간

2023-09-25 08:28 UTC, dooboocookie approved these changes
리뷰 포인트가 적은 PR이여서 빨리 리뷰할 수 있었습니다.
저는 해당 이슈에 대해서는 확실히 개선된 것 같아서 approve 하겠습니다

2023-09-25 08:28 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    List<GameResult> findByPlayerId(@Param("playerId") Long playerId);
P4:

좋은 것 같습니다.
`GameResult`<-> `Game`은 @OneToOne 연관관계이고
` Game`<-> `List<Hint>는 @OneToMany 연관계여서
다중 fetch join 문제도 딱히 없을 것 같습니다.

다만 jsql 가독성을 위해서 r.game 즉 Game에도 앨리어스를 주는 것은 어떨까요?
```suggestion
    @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints Where g.player.id = :playerId")
    List<GameResult> findByPlayerId(@Param("playerId") Long playerId);
```

2023-09-25 08:28 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    List<GameResult> findByPlayerId(@Param("playerId") Long playerId);
P3:

리뷰를 달 곳이 없어서 이곳에 달자면,
현재는 PR 변경사항에는 큰 영향은 끼치지 않지만,
전반적인 Game과 GameResult에 대해서 수정을 하면서 지연로딩을 걸어야할 것 같은데 어떻게 생각하시나요?

2023-09-26 02:53 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    List<GameResult> findByPlayerId(@Param("playerId") Long playerId);
가독성 수정 좋네요..! 반영하겠습니다~!
현재는 fetch join 으로 게임결과 조회시 게임과 힌트들을 모두 가져오고 있는데 그거와 별개로 게임결과를 조회할때 게임의 대한 정보가 필요 없는 상황이 있을 수 있으니 지연로딩을 거는것이 맞는것같네요! 의견 반영하겠습니다~!

2023-09-27 08:41 UTC, kokodak approved these changes
안녕하세요 채채! 리뷰가 늦어져서 죄송합니다.

리뷰하기 전에 N+1 과 관련된 다양한 개념들을 학습하고 본다는 게, 여러가지 일에 우선순위가 밀려서 제대로 리뷰를 하지 못했네요 😭

루카가 전에 말했던 것 처럼, 현재로서는 다중 Fetch Join 이 문제가 될 것 같지 않아서, 바로 Approve 적용하겠습니다. 

코멘트에서 궁금한 점 하나 남겨두었는데 확인해주시면 감사하겠습니다!

고생하셨어요 채채!!

2023-09-27 08:41 UTC, kokodak commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints Where g.player.id = :playerId")
제가 잘 몰라서 그런데, LEFT JOIN 을 사용하는 이유가 무엇인가요!

2023-09-27 08:41 UTC, kokodak commented on backend/src/test/java/com/now/naaga/gameresult/repository/GameResultRepositoryTest.java
> +class GameResultRepositoryTest {
테스트 좋네요 😁

2023-10-02 22:26 UTC, zillionme requested changes
채채... 2주만에 리뷰를 달다니 난 쓰레기야... 앞으로 Dn룰을 잘 지키도록 하겠습니다!!
P5 리뷰 하나 정도 있는데(모든 n+1문제를 해결한 건 아니라 최종적으로 쿼리가 2개 날라가더라고), 아래 궁금증과 제안할 내용도 함께 읽어줬으면 좋겠어.

1. 궁금한 점 : 해당 문제를 어떻게 발견하게 되었는지 궁금합니다! 
     인덱스 성능 향상 실험을 하다가 여러번의 쿼리가 발생되는 것을 발견한 건가요?
2. 현재 변경한 gameService.findStatistic()메서드 뿐만 아니라, GameResult를 GameRecord로 변경해서 반환하는 모든 쿼리에서 n+1문제가 발생하더라고

findAllGameResult()메서드에서는
-  game-place, game-player간의 n+1문제 때문에 게임 조회할 때, 게임 조회 쿼리+ 장소조회쿼리+플레이어 조회쿼리 발생
- 채채가 해결하려고 했던 문제(게임result를 개수만큼 조회 +  각 게임의 힌트 조회) 도 똑같이 발생함

findGameResult()메서드에서도 비슷한 문제가 발생하고.

2주나 된 pr이라 일단 이 pr은 머지하고, 내가 의견 낸 문제는 슬랙에 공유하고 새로 이슈를 파서 고치는 것도 좋을 것 같아.

2023-10-02 22:26 UTC, zillionme commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints Where g.player.id = :playerId")
P5:
실행을 해봤는데
GameRecord에서 gameResult.getGame().getPlace().getPosition()라는 부분이 있더라고
이때, game-place간에도 n+1문제가 발생하고 place-player는 즉시 로딩돼서, 아래와같은 쿼리가 추가적으로 전송돼
<img width="321" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/100172683/63625a58-7fa1-4b48-86b7-a1939408924f">

해당 문제가 큰 문제라고 생각하지 않으면 넘어가도 좋지만, 
만약, 한번에 Game객체 내의 필요한 정보를 가져오는 것이 목적이라면, 
1. Place객체의 Player를 지연 로딩으로 변경하고 
2. game-place간의 n+1문제를 해결하기 위해 아래와 같은 쿼리를 사용하는 것도 좋을 것 같아.

```suggestion
        @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints JOIN FETCH g.place Where g.player.id = :playerId")
```

2023-10-03 07:45 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/gameresult/domain/GameResult.java
>      private Game game;
위에 루카와 대화한 부분을 보시면 될것같습니다!
https://github.com/woowacourse-teams/2023-naaga/pull/364#discussion_r1335556198

2023-10-03 08:22 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints Where g.player.id = :playerId")
이레 천재? GameRecord에서 목적지 정보를 사용하기때문에 쿼리가 한번 더 날아가는 거였구나...바로 수정하겠습니다!

2023-10-03 08:22 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints Where g.player.id = :playerId")
이레 천재? GameRecord에서 목적지 정보를 사용하기때문에 쿼리가 한번 더 날아가는 거였구나...바로 수정하겠습니다!

2023-10-03 08:31 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints Where g.player.id = :playerId")
또한 힌트가 존재하지 않을때 힌트를 출력해보니 null이 아닌 빈 리스트를 갖게되는데요..! 이래생각은 어떠신가요!?

2023-10-03 08:41 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints Where g.player.id = :playerId")
pr에 남겨주신 글에 대한 답변은..! 이레 말씀처럼 게임 결과를 조회하는 모든 부분에 현재 수정이 필요한 것이 맞습니다. 하지만 이 부분은 현재 통계조회를 수정하는 pr 범위에 벗어난다고 생각하여 수정하지 않았습니다!

2023-10-03 10:04 UTC, zillionme commented on backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
> +    @Query("SELECT r FROM GameResult r JOIN FETCH r.game g LEFT JOIN FETCH g.hints Where g.player.id = :playerId")
> 또한 힌트가 존재하지 않을때 힌트를 출력해보니 null이 아닌 빈 리스트를 갖게되는데요..! 이래생각은 어떠신가요!?
Game객체에서 힌트를 출력할 때는 빈 리스트를 갖는 게 맞지 않을까요?
사실 질문의 내용을 정확히 파악하지 못했숩니다!

> pr에 남겨주신 글에 대한 답변은..! 이레 말씀처럼 게임 결과를 조회하는 모든 부분에 현재 수정이 필요한 것이 맞습니다. 하지만 이 부분은 현재 통계조회를 수정하는 pr 범위에 벗어난다고 생각하여 수정하지 않았습니다!
넵 제가 해당 내용 슬랙에 공유하고 빠른시일 내에 이슈 파도록 하겠습니다

2023-10-03 14:13 UTC, merged