feat: 장소 등록 검수 관리자 페이지 제작 및 인가 인터셉터 추가
woowacourse-teams/2023-naaga pull request #374
Opened 2023-09-30 17:30 UTC by dooboocookie

## 📌 관련 이슈
- closed: #365 

## 🛠️ 작업 내용
PR에서 작업한 주요 내용을 적어주세요.
 - [X} 관리자 페이지 구현
  - [X] 플레이어가 장소 등록 시, 검수중 상태로 등록
  - [X] 관리자가 approve 해준 장소는 게임에 사용될 수 있는 상태로 등록
- [X] 관리자 페이지에서 접속할 수 있도록 CORS 설정 추가
- [X] HttpMethod 별로 Interceptor 매칭되도록 설정
- [X] 관리자 통과시키는 인가 Interceptor 추가

## 🎯 리뷰 포인트

### 0. 해결하고자 하는 문제

장소에 검증 로직이 추가로 인해서
관리자 페이지 및 그에 대한 CORS 설정
또는 해당 API들의 인가처리를 하는 인터셉터가 필요로 하다.

### 1. 관리자 페이지
- 현재 관리자 페이지를 배포 ec2에서 정적 페이지로 배포해놓은 상태입니다.
- 해당 html의 주소는 슬랙에 공유 드렸습니다(공개되면 안됨)

<img width="1493" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/79090478/97bc5b0d-08c6-4fc2-a379-63c8e9af0464">

다음과 같은 컬럼으로 임시 등록 되어있는 리스트들이 조회하고 수락, 거절을 할 수 있습니다.
관리자 페이지에 대한 코드는 저희가 공개적이 장소에 올리지 않기로 하였으므로 자세한 코드나 내용에 대해서는 직접 설명드리겠습니다.
 js 로 html 동적으로 태그 만들도록 하였고 버튼 누를떄마다 `수락`, `거절` 작업 후 새로고침하여 새로이 목록 받아오는(이것도 js) 형식입니다.

### 2. RequestMatcherInterceptor

[문제]
<img width="874" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/79090478/e8ac3344-3a1d-43d1-8e78-6a6bdc0c9c8b">

- GET /places : 유저가 조회
- POST /places : 관리자가 등록
- GET /temporary-places : 관리자가 조회
- POST /temporary-places : 유저가 등록
- DELETE /temporary-places : 관리자가 삭제

위의 요청들은 `패스는 같은데` `http 메서드들이 달라서`다른 인가처리(인터셉터)를 타야하는 상황입니다.

그래서 인터셉터를 한번 감싸주는 `RequestMatcherInterceptor`를 추가하였습니다.

1. 인터셉터 등록
```java
    @Override
    public void addInterceptors(final InterceptorRegistry registry) {
        registry.addInterceptor(new RequestMatcherInterceptor(authInterceptor, pathMatcher));
    }
```
실질적으로 `WebMvcConfigurer`에 등록되는 인터셉터는 `실제 수행하는 interceptor를 주입받은 RequestMatcherInterceptor`입니다.

2. 매핑 등록
```java
new RequestMatcherInterceptor(authInterceptor, pathMatcher)
                .includeRequestPattern("/**")
                .excludeRequestPattern("/h2-console/**")
                .excludeRequestPattern("/auth/**")
                .excludeRequestPattern("/**/*.png")
                .excludeRequestPattern("/**/*.jpg")
                .excludeRequestPattern("/**/*.jpeg")
                .excludeRequestPattern("/**/*.gif")
                .excludeRequestPattern("/**/*.ico")
                .excludeRequestPattern("/ranks")
                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
```
요청 매핑은 RequestMatcherInterceptor에 구현되어있는 `includeRequestPattern()`, `excludeRequestPattern()`로 할 수 있습니다.
인자로  다음 값을 받습니다. 
1. `String pathPattern` : AntPathMatcher로 매칭할 수 있는 패턴
2. `HttpMethod... httpMethods` : HttpMthod를 가변인자로 받습니다. 0개 들어오면 모든 메소드에 대해서 등록합니다.

3. 실행

```java
public class RequestMatcherInterceptor implements HandlerInterceptor {
    // ...
    @Override
    public boolean preHandle(final HttpServletRequest request,
                             final HttpServletResponse response,
                             final Object handler) throws Exception {
        if (isIncludedRequestPattern(request)) {
            return handlerInterceptor.preHandle(request, response, handler);
        }
        return true;
    }
    // ...
}
```
- 만약 2번에서 매핑된 요청이라면 1번에서 등록했던 인터셉터가 실행되게 됩니다!
- 아니라면 그냥 다음 인터셉터로 넘어가는 것이라 아무일도 일어나지 않습니다.

### 3. CORS 설정
- CORS 설정을 위해 origins을 제가 관리자 페이지 배포한 주소로 하였습니다.
- 제가 서브모듈에 추가해뒀는데, 지금 이 CORS 는 어떤 테스트도 안돼서 잘 되는지는 확실하진 않지만, 서브모듈 수정으로 해결할 수 있는 문제일 것이라 일단 기본 설정만하고 PR 보냅니다.

## ⏳ 작업 시간
추정 시간:   4시간
실제 시간:   5시간
이유: 인터셉터 설정이 오래거렸습니다.

2023-09-30 20:13 UTC, kokodak requested changes
안녕하세요 루카루카짱

관리자 페이지 만들기 꽤나 어렵고 CORS 설정 등등 때문에 상당히 건드릴 것이 많았을텐데... 만드시느라 정말 고생 많으셨어요!!

백엔드 사람이 만든거라고 믿기 힘들 정도로 UI가 예쁘네요 ㅎㅎ

프록시 패턴 사용하셔서 인터셉터 구현해주신 부분도 정말 인상깊게 봤는데요..

같은 Path 여도 Method 종류에 따라 다른 인터셉터를 타야한다는게 생각보다 골치아픈 문제였을텐데, 이에 대한 문제 해결을 아름답게 풀어내주신 것 같네요.

루카 덕분에 앞으로 저희가 사용할 인터셉터 기능이 더욱 풍부해진 것 같아서 기부니 좋습니다 ㅎㅎ..

몇가지 변경점이 있으면 좋을 것 같은 부분들을 리뷰로 남겨두었는데, 확인해주시면 감사하겠습니다~!

(+
[프록시를 사용해서 인터셉터 개선에 관한 글](https://jujeol-jujeol.github.io/2021/08/07/%ED%94%84%EB%A1%9D%EC%8B%9C-%ED%8C%A8%ED%84%B4%EC%9C%BC%EB%A1%9C-%EC%9D%B8%ED%84%B0%EC%85%89%ED%84%B0-Path%EC%99%80-Method-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0/)을 하나 찾아서 공유해봅니다. 이 글이랑 루카 PR 작업물이랑 같이 보면서 하면 더 이해가 잘 될거같아요!)

2023-09-30 20:39 UTC, kokodak commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +        final String inputPassword = idAndPassword[1].trim();
아 근데 이건 제가 해도 될듯합니다

2023-10-01 03:12 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +        final String inputPassword = idAndPassword[1].trim();
아입니다 인터셉터 건든 김에 예외 상황 확실히 컨트롤 하겠습니다

2023-10-01 05:53 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +public class RequestMatcherInterceptor implements HandlerInterceptor {
예스!!! 그겁니다!! 그래서 PathMatcher도 빈으로 주입이 불가능해요. ㅠㅠㅠ

2023-10-01 08:00 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +        final String inputPassword = idAndPassword[1].trim();
검증 로직 추가했습니다.
헤더의 `Basic`없을 때와 
`id:password`안들어왔을 때와 
로그인 실패했을 떄
예외 발생하도록 수정했습니다!!

2023-10-01 08:31 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +public class ManagerAuthInterceptor implements HandlerInterceptor {
해당 인터셉터를 빈으로 관리하는 이유는
@Value어노테이션 사용해서 
매니저의 아이디와 비밀번호를 프로퍼티 변수로 관리하기 때문입니다.
현재는 매니저에 대한 정보가 DB에 저장되지 않아서 이렇게 해뒀는데,
만약 DB에 저장된다고 하더라도 DB에서 값을 가져와야하므로 컴포넌트로 관리를 해야될 것 같아요!!

2023-10-01 10:27 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +        final String inputPassword = idAndPassword[1].trim();
테스트도 추가하였습니다!

2023-10-01 10:28 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +        final List<HttpMethod> httpMethods = Arrays.stream(requestMethods).collect(Collectors.toList());
넵 바로 적용하겠습니다!!!!!!!!!!!!

2023-10-01 10:29 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +    private static final List<HttpMethod> ALL_HTTP_METHODS = Arrays.stream(HttpMethod.values()).toList();
넵 바로 적용하겠습니다!!!!!!!!!!!!!!!!!!!

2023-10-01 10:52 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +    private final PathMatcher pathMatcher;
해당 객체를 빈객체로 사용한 이유는
1. 해당 객체는 상태를 갖지 않기 때문에 싱글턴으로 사용되도 된다.
2. 스프링에서 제공하는 객체이므로 생성 및 주입을 스프링에 의존적으로 해도 좋다.
이 정도가 있었습니다.

근데 코코닥 의견을 듣고 나니까 정적 객체로 빼도 좋을 것 같네요.
1. 객체를 여러번 생성하면 비효율이다.
2. `WebConfig`와 `RequestMatcherInterceptor`가 책임을 벗어난 필드를 들고있지 않아도 된다.
3. @Configuration에서 직접 new연산자로 생성해주기 때문에 전략을 바꿔주는 확장성 측면에서도 큰 메리트가 없다.

라는 관점에서 정적 클래스로 관리하는 것이 좋을 것 같아요!!

좋은데요👍

2023-10-01 11:09 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/config/BeanConfig.java
> +    }
https://github.com/woowacourse-teams/2023-naaga/pull/374#discussion_r1342116638

현재는 유틸 클래스로 변경하였습니다

2023-10-01 11:16 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +        final List<HttpMethod> httpMethods = Arrays.stream(requestMethods).collect(Collectors.toList());
하려고 하였으나 asList()로 반환되는 ArrayList는 
![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/9018e6c6-4fd5-4a7b-80a2-822bdd264199)
arrays에서 정의해놓은 다른 구현체여서 배열의 크기가 이미 정해져 있어서 추가가 안되더라구요.
그래서 이부분은 유지하였습니다.

2023-10-01 11:21 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptorTest.java
> +    static Stream<Arguments> includeRequestPatternDummy() {
추가 하겠습니다.👍

2023-10-01 11:51 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +    private boolean isIncludedRequestPattern(final HttpServletRequest request) {
>어떤것을 정렬하라는 것인지 이해가 되지 않아요 😭😭😭😭😭😭😭😭😭
일단 정렬할만한 자료구조는 `includedRequestPatterns`와 `excludedRequestPatterns`이 거 두개 있는데, 이 두 리스트를 정렬한다고 어떤 것이 달라질까요?????????

라고까지 적었던 거 아세요???
그냥 호출순서에 맞게 선언하라는 말이군요...

코코닥 몇살에세요?

2023-10-02 00:41 UTC, zillionme requested changes
안녕하세요 루카!
관리자 페이지까지 예쁘게 만들다니 루카의 능력치👍🏻👍🏻  
사실 리뷰라기보다 코멘트를 하기 전 질문들에 가까운데요. 루카의 코드를 제대로 이해하지 못한 부분이 있어서요. 따라서 Pn룰을 적용하지 않았습니다.
여러 질문에 대한 답변 주시면  이해하고 다시 리뷰 달도록 하겠습니다.

2023-10-02 00:41 UTC, zillionme commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +public class RequestMatcherInterceptor implements HandlerInterceptor {
이해가 안가는 점이 RequestMatcherInterceptor에 어떤 상태값이 존재하는 건가요?
includedRequestPatterns의 값을 WebConfig에서 직접 넣어주기 때문인가요?
객체의 사용자체는 싱글턴인 것 같은데, 항상 new 로 인스턴스를 만들어서 다른 Interceptor 를 직접 주입시켜줘야하는 이유를 모르겠습니다.
+)
PathMatcher도 마찬가지로 어떤 상태값이 존재하기 때문에 빈으로 관리하면 안되는 건가요?

2023-10-02 00:41 UTC, zillionme commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +        final List<HttpMethod> httpMethods = Arrays.stream(requestMethods).collect(Collectors.toList());
P5:
AsList를 쓰실 생각이 있으셨다면(내부적으로 ArrayList를 사용하는)
```suggestion
        final List<HttpMethod> httpMethods = new ArrayList<>(requestMethods);
```
를 사용하지 않는 이유는 뭔가용?

2023-10-02 00:41 UTC, zillionme commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
모든 path에 대해 options 메서드를 제외하는 이유는 뭔가요?

2023-10-02 00:41 UTC, zillionme commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
RequestMatcherInterceptor를 스프링 빈으로 관리하지 않는 이유는 위와 같은 특정 패턴들의 주입이 필요해서 인가요?

2023-10-02 00:41 UTC, zillionme commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +public class ManagerAuthInterceptor implements HandlerInterceptor {
는 어떻게 적용되는 건가요?
WebConfig에 등록이 안되어있는데, 어떻게 이 인터셉터를 특정 path(GET /temporary-places 등)에 대해 사용할 수 있는지 궁금합니다

2023-10-02 00:54 UTC, zillionme requested changes
test관련 질문

2023-10-02 00:54 UTC, zillionme commented on backend/src/test/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptorTest.java
> +        };
Controller를 Mock 객체로 사용하지 않으신 이유가 있나용?

2023-10-02 00:54 UTC, zillionme commented on backend/src/test/java/com/now/naaga/common/presentation/interceptor/RequestPatternTest.java
> +class RequestPatternTest {
테스트 코드 깔끔하고 이해하기 쉽네요👍🏻👍🏻

2023-10-02 05:04 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
CORS설정 때문인데요. CORS의 프리플라이트 요청(OPTIONS)가 인가 인터셉터를 타서 예외가 발생하는 이슈가 있었습니다.

2023-10-02 05:11 UTC, kokodak commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +public class ManagerAuthInterceptor implements HandlerInterceptor {
아 `@Value` 어노테이션이 있었군요.. 제가 착각했습니다 🥲

2023-10-02 05:12 UTC, kokodak commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +    private boolean isIncludedRequestPattern(final HttpServletRequest request) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

제가 너무 MZ 스럽게 코멘트를 남겨서 혼선을 야기했네요.. 죄송합니다

2023-10-02 05:19 UTC, kokodak commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
[CORS 개념](https://evan-moon.github.io/2020/05/21/about-cors/)

CORS 정책에 의해서, 브라우저가 서버와 API 통신을 할 때는 예비 요청과 본 요청으로 나눠서 통신이 이루어집니다. (물론 상황에 따라 다르지만, 대부분의 경우에 대해서)

이때 예비 요청으로 날라가는 HTTP Method 가 Options 메서드예요!

현재 저희 관리자 페이지의 Origin 과 서버의 Origin 이 서로 다르기 때문에, CORS 정책을 준수해야하는 상황입니다.

2023-10-02 05:19 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +public class RequestMatcherInterceptor implements HandlerInterceptor {
# RequestMatcherInterceptor의 상태
1. 본 로직이 돌아가는 HandlerInterceptor 구현체
2. 1번의 인터셉터가 발동 되어야하는 요청 패턴들과 메서드들
3. 1번의 인터셉터가 발동 안되어야할 요청 패턴들과 메서드들

# PathMatcher는 상태
PatchMatcher는 이전에도 Bean으로 관리했고,
현재는 유틸 클래스로 관리합니다.
이 객체는 상태를 갖지 않아서 한번만 생성하고 재활용해도 좋습니다.
위에서 한말은 RequestMatcherInterceptor가 빈으로 등록이 불가능하기 때문에 PathMatcher를 빈주입 못한다는 말입니다.

2023-10-02 05:20 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +        final List<HttpMethod> httpMethods = Arrays.stream(requestMethods).collect(Collectors.toList());
이렇게 좋은 방법이???

2023-10-02 05:21 UTC, kokodak commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +public class ManagerAuthInterceptor implements HandlerInterceptor {
이건 루카가 그냥 저희를 위해 미리 만들어준 선물 같은 것이에요

나중에 저희가 직접 API 구현할때 붙이면 될듯?

2023-10-02 05:25 UTC, kokodak commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
`RequestMatcherInterceptor` 는, 저희가 실제로 사용할 Interceptor(예를 들면 `authInterceptor`) 에 대한 프록시 객체예요.

따라서, `RequestMatcherInterceptor` 는 다양한 대상 객체(subject)를 프록시할 수 있어야해서, 싱글턴으로 관리가 불가능한 친구입니다!

물론 이레가 말씀해주신 특정 패턴들 또한 상태 값이기 때문에, 그 이유도 맞겠네요

2023-10-02 05:26 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
RequestMatcherInterceptor는 본 로직이 돌아가는 Interceptor를 감싸주는 프록시 객체 입니다.
지금은 제가 ManagerAuthInterceptor를 만들어 놓고 등록을 안해놨는데,
이제 API 만드신 후에 ManagerAuthInterceptor를 등록할 떄 새로운 RequestMatcherInterceptor를 등록해야겠쬬?

# RequestMatcherInterceptor 도입전
![IMG_0387](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/58c94bc3-5caf-4c8d-949f-5162e94a1469)
원래는 이렇게 본로직이 들어가는 인터셉터를 메서드에 상관없이 요청 패턴으로만 등록해놨는데요,

# RequestMatcherInterceptor 도입 후

![IMG_0388](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/4bb8ae86-814c-4a18-a972-c43dec58c177)

이렇게 본로직을 상태로 갖고 그 본 로직이 돌아가야 하는 요청들을 List 상태로 갖고있는 RequestMatcherInterceptor들이 계속 등록되는 형식입니다.

2023-10-02 05:27 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +public class ManagerAuthInterceptor implements HandlerInterceptor {
아직 등록이 안된 앱니다! 저것으로 등록될 API가 없어서요
이제 이레랑 코닥이 API 만드시고 등록하시면됩니다

2023-10-02 05:27 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptorTest.java
> +        };
목으로 변경해볼게요 ㅠㅠ 몰라써요

2023-10-02 05:33 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +public class RequestMatcherInterceptor implements HandlerInterceptor {
밑에서 RequestMatcherInterceptor의 동작에 대해서 다시 설명드릴게용

2023-10-02 05:44 UTC, dooboocookie commented
이레가 말씀해주신 내용 다 적용하였고,
RequestMatcherInterceptor의 동작 원리에 대해서도 리뷰로 설명 드렸습니다!!

2023-10-02 05:45 UTC, kokodak approved these changes
피드백 적극 반영해주셔서 감사합니다!!

테스트도 견고하고, 무엇보다 코드가 참신해서 많이 배울 수 있었네요. 감사합니다 😁

제가 건의드렸던 피드백들은 모두 해결된 것 같아서, 저는 이만 Approve 하도록 하겠습니다!

2023-10-02 05:45 UTC, kokodak commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcher.java
> +public class RequestMatcher {
굿!! 반영해주셔서 감사합니다

PathMatcher 들이 사라져서 보기가 좋네요

2023-10-02 05:45 UTC, kokodak commented on backend/src/test/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptorTest.java
> +                Arguments.arguments("/places", "POST", "/places/**", new HttpMethod[]{GET}, 0),
반영 감사합니다

2023-10-02 14:02 UTC, chaewon121 approved these changes
루카~! 코드 잘봤습니다!인터셉터 로직과 cors를 이해하는것이 어려웠네요..ㅠㅠ 위에 이레와 코코닥과 나눈 대화들도 읽으면서 이해가 좀더 수월했던것같네요..! 수정이 필요한 부분은 못찾았고 궁금한 점을 남겨놓았습니다~! 코드들이 예술이던데요..고생 많으셨습니다~!

2023-10-02 17:47 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +        final String inputPassword = idAndPassword.get(1).trim();
https://hianna.tistory.com/526

오 java 11이후에 등장한 strip()이란 메서드가 있군요.
유니코드의 모든 공백문자를 제거하는 strip()함수 좋네요!! 적용하겠습니다!!

2023-10-02 17:48 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +    }
맞아요!!
ManageAuthInterceptor는 아직 API 구현이 안돼서 적용된 요청이 없지만
인터셉터는 인가처리를하고,
위는 CORS 설정을 해서 해당 오리진에서는 요청을 받겠다는 뜻입니다!!

2023-10-02 17:56 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestPattern.java
> +}
기본적으로 위 과정은 2가지를 검증하는 단계입니다.

## 1. 패스(or 패턴) 이 일치하는가
- `/**` 는 `/a`와 일치합니다
- `/a/**` 는 `/a`와 일치합니다
- `/a` 는 `/a`와 일치합니다
- `/b/**` 는 `/a`와 불일치합니다
- `/b` 는 `/a`와 불일치합니다

## 2. HttpMethod가 일치하는가
스프링에서 제공하는 HttpMethod (enum)이 일치하는가 입니다.
- `HttpMethod.GET`은 `HttpMethod.GET은 일치합니다.
- `HttpMethod.GET`은 `HttpMethod.POST은 불일치합니다.

위 1과 2가 다 일치해야 true를 반환하는 메서드입니다.
ReuqestMatcher를 타고 들어가면 `AntPathMatcher`가 있는데 해당 객체는 스프링에서 제공하고 1번을 해주는 역할입니다.

그리고 대문자 변환과정은 
String의 "GET"을   HttpMethod.GET로 변경하기 위한 확실한 대문자 처리일 뿐입니다

2023-10-02 17:59 UTC, dooboocookie commented
채채 리뷰 감사합니다!!
이제 이레만 어프루브 하면 머지하겠습니다!!

2023-10-03 08:23 UTC, zillionme approved these changes
루카 CORS에 대한 설명 감사합니다.
이미 코코닥과 채채의 리뷰로 깔끔해진 코드라서 리뷰할 게 없었네요ㅠ 
다음부터는 일찍 코드리뷰를 하도록 하겠습니다.
+ 몇가지 질문을 더 추가했는데, 루카가 꼭 답변하지 않아도 괜찮습니다!!!

수고하셨어요 루카... 
프록시 객체를 사용한 인터셉터 처음 보는 거라 많이 배워갑니다!

2023-10-03 08:23 UTC, zillionme commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
루선생님의 CORS 강의를 듣고 코드 이해가 잘 되는 것 같습니다. 감사합니다.
+ 직접 그림까지 그려주셔서 감사해용
하나 더 궁금한 점은 
```
private HandlerInterceptor mapAuthInterceptor() {
        return new RequestMatcherInterceptor(authInterceptor)
                .includeRequestPattern("/**")
                **.excludeRequestPattern("/places", HttpMethod.POST)**
                .excludeRequestPattern("/h2-console/**")
                .excludeRequestPattern("/auth/**")
                .excludeRequestPattern("/**/*.png")
                .excludeRequestPattern("/**/*.jpg")
                .excludeRequestPattern("/**/*.jpeg")
                .excludeRequestPattern("/**/*.gif")
                .excludeRequestPattern("/**/*.ico")
                .excludeRequestPattern("/ranks")
                .excludeRequestPattern("/**", HttpMethod.OPTIONS);

private HandlerInterceptor mapAuthInterceptor() {
        return new RequestMatcherInterceptor(managerAuthInterceptor)
                **.includeRequestPattern("/places", HttpMethod.POST)**
```
와 같이 코드를 중복으로 추가해야 할까요?
혹은,authInterceptor와 managerAuthInterceptor에 매핑된 url을 모두 확인한다면 두 인터셉터에서 모두 prehandle() true를 반환해야할 것 같아서요

2023-10-03 13:08 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
`POST /places`요청은 관리자가 장소를 수락하는 행위 이므로 위와 같이 exclude 하는게 맞고 
ManagerAuthInterceptor에서는 include 해야돼요!!

2023-10-03 13:10 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestPattern.java
> +        return RequestMatcher.match(this, inputRequestPattern);
RequestPattern은 상태가 있고 여러 객체가 생성될 수 있는 값입니다.
다음과 같이 각 리케스트 패턴 인스턴스마다  매쳐 인스턴스를 새로 만들어주면 매쳐가 여러개 만들어져서 비효율이라고 느껴서
유틸 클래스에서 하나의 객체만 생성해서 관리하는 것입니다.

2023-10-03 13:14 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/config/WebConfig.java
> +                .excludeRequestPattern("/**", HttpMethod.OPTIONS);
CORS 적용은 모든 메서드 요청에 대해서 한것이 맞습니다.
그리고, 이유가 조금 다른데요. 프리플라이트 요청은 브라우저의 SOP 원칙에 의해서 나가는 것이므로 OPTIONS는 푸는게 맞는 것 같아요!

2023-10-03 13:16 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
> +public class RequestMatcherInterceptor implements HandlerInterceptor {
RequestMatcher는 유틸 클래스나 싱글턴으로 관리하기 좋다. 왜냐하면 상태를 갖지 않기 때문이다.
RequestMatcher가 필요한 객체들은 상태를 갖고 있기 때문에 싱클턴(빈)으로 관리하기 보다는 유틸 클래스로 관리하겠다.

이런 의미입니다.

2023-10-03 13:17 UTC, merged