refactor: 업로드 뷰 디자인 변경
woowacourse-teams/2023-naaga pull request #381
Opened 2023-10-02 16:16 UTC by krrong

## 📌 관련 이슈
- closed: #379

## 🛠️ 작업 내용
업로드 뷰 디자인을 변경했습니다!

- 테마에서 전체 텍스트의 색상을 흰색으로 지정해줬어요!
```kotlin
<item name="android:textColor">@color/white</item>
```

## 🎯 리뷰 포인트
현재 위치가 잡히기 전까지 로티가 도는 것은 같습니다! 그런데 전체적인 색상이 어두워지니까 로티 도는게 좀 자연스럽더라구요?  
각설하고, 완성한 디자인은 다음과 같아요🤠  
<img src="https://github.com/woowacourse-teams/2023-naaga/assets/84285337/a28cbf36-17ad-4413-b2ad-30a5806fe7fb" width=300>
<img src="https://github.com/woowacourse-teams/2023-naaga/assets/84285337/34103e3e-88c5-4ede-8605-a889b7da557e" width=300>

## ⏳ 작업 시간
추정 시간: 1h  
실제 시간: 1h

2023-10-03 23:47 UTC, hyunji1203 requested changes
크롱 고생많았어요!!🦖
아주 빠른속도로 디자인 바꿔주시다니.. 역시 크롱..
몇가지 단순 제안 코멘트만 달아놨으니, 크롱이 보고 바꾸고 싶으면 바꾸고 아니면 안바꾸고 머지해달라고 하면 됩니다! 정말 고생 많았어요~~👍

2023-10-03 23:47 UTC, hyunji1203 commented on android/app/src/main/res/layout/activity_upload.xml
> +            android:backgroundTint="@color/main_yellow"
[P2]
버튼이 이제 확정되었으니, 확정된 버튼 이미지를 추출해서 background에 넣으면 될 것 같아요! 
저도 모험 결과 뷰에 해당 작업을 해놔서 참고를 위한 [링크](https://github.com/woowacourse-teams/2023-naaga/issues/394) 첨부할게요!

2023-10-03 23:47 UTC, hyunji1203 commented on android/app/src/main/res/layout/activity_upload.xml
>          <EditText
[P5]
`android:background="@null"` 를 추가해서 EditText의 밑줄을 없애는 건 어떻게 생각하시나요?!
밑줄을 없애면 아래의 그림처럼 보인답니다! 이건 단순 제 제안이니 크롱이 원하는 걸로 하시면 됩니다!
<img width="315" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/83613106/021ace4a-d4dd-4a22-960f-1f0141903f82">

2023-10-03 23:47 UTC, hyunji1203 commented on android/app/src/main/res/layout/activity_upload.xml
>              android:layout_marginTop="@dimen/space_default_medium"
[P5]
지금은 너무 위의 선과 붙어있는 것 같은데 좀만 더 간격을 띄우면 어떨까요?!
이것도 위의 리뷰와 마찬가지로 제안일 뿐이니 크롱이 원하는 대로 하면 됩니다!😎

2023-10-03 23:47 UTC, hyunji1203 commented on android/app/src/main/res/layout/activity_upload.xml
> +            android:layout_marginTop="@dimen/space_default_medium"
[P5]
여기도 좀 간격이 더 띄워지면 좋을 것 같아요! 
이건 단순 제 제안(완전 갠취의 영역)이니 크롱이 원하는 걸로 하시면 됩니다!👍

2023-10-03 23:47 UTC, hyunji1203 commented on android/app/src/main/res/values/themes.xml
> +        <item name="android:textColor">@color/white</item>
오 좋은데요?!👍

2023-10-04 04:59 UTC, krrong commented on android/app/src/main/res/layout/activity_upload.xml
> +            android:backgroundTint="@color/main_yellow"
반영했습니다! 버튼이 게임틱하니 예쁘네요~

2023-10-04 05:02 UTC, krrong commented on android/app/src/main/res/layout/activity_upload.xml
>          <EditText
반영했어요!  
다만, 유저가 글자를 입력하는 곳이 어디인지 모르지는 않을까.. 조금 걱정이긴합니다! 그래서 hint를 조금 수정했어요  
사용자 유치를 열심히 해서 피드백을 반영해보도록 하죠!

2023-10-04 05:04 UTC, krrong commented on android/app/src/main/res/layout/activity_upload.xml
>              android:layout_marginTop="@dimen/space_default_medium"
`space_default_large`로 반영했어요!

2023-10-04 05:05 UTC, krrong commented on android/app/src/main/res/layout/activity_upload.xml
> +            android:layout_marginTop="@dimen/space_default_medium"
`space_default_large`로 반영했어요!

2023-10-04 05:14 UTC, hyunji1203 requested changes
크롱 고생했어요! 리뷰 반영한 것 잘 봤습니다!
xml id에 오타 들어간거 수정이랑
UploadAcitivity에 아래와 같은 사용안하는 함수만 지우면 될 것 같아요!
```
private fun Coordinate.toText(): String {
        return "$latitude, $longitude"
    }
```
혹시 몰라 함수를 남겨놓은건가요? 그러면 냅둬도 됩니다!ㅋㅋ
고생많았어요!🦖

2023-10-04 05:14 UTC, hyunji1203 commented on android/app/src/main/res/layout/activity_upload.xml
> +            android:id="@+id/btn_upload_su경bmit"
경 친구가 저 사이에 들어가 버렸어요!

2023-10-04 05:16 UTC, krrong commented on android/app/src/main/res/layout/activity_upload.xml
> +            android:id="@+id/btn_upload_su경bmit"
맥 고질병인가요...😢

2023-10-04 05:20 UTC, hyunji1203 approved these changes
구욷 아주 죠습니다.
approve 하겠습니다! 고생했어요 크뤙🦖

2023-10-04 05:23 UTC, merged