feat: 쪽지 기능 뼈대코드 설계 및 구현
woowacourse-teams/2023-naaga pull request #389
Opened 2023-10-03 02:56 UTC by zillionme

## 📌 관련 이슈
- closed: #386 
 
## 🛠️ 작업 내용
- [x] 쪽지 기능 뼈대코드 설계
- [x] 쪽지 관련 엔티티 구현
- [x] 쪽지 관련 컨트롤러 구현
- [x] 쪽지 관련 레포지토리 구현

## 🎯 리뷰 포인트
쪽지 관련해서 기획적으로 완료되지 않은 부분이 많아서 아주 간단한 뼈대코드가 완성되었는데요. Letter라는 이름의 테이블이 추가될 것 같습니다.
![제목 없는 다이어그램 drawio](https://github.com/woowacourse-teams/2023-naaga/assets/100172683/22af840a-5b59-4854-b043-78122fbfcbc9)

### 쪽지 기획 관련해 논의해볼 점
- 게임 중 플레이어가 등록한 쪽지
- 게임 중 플레이어가 발견한 쪽지
와 같이, 게임 중에 쪽지와 관련된 기록을 남길 것인지 고려를 해봐야할 것 같은데요. 게임이 종료 후, 게임 중에 봤던 쪽지나 등록한 쪽지를 볼 수 있도록 로그처럼 남겨놔야 할지요.
또는 게임과 관련없이 내가 모은 총 쪽지들 또는 등록한 쪽지들을 기록해 두는 것도 의미가 있다고 생각합니다.

### 궁금한 점
Builder를 만들다 보니 궁금한 점이 생겼는데요.
테스트 패키지의 Builder 클래스들은 모두 @Component어노테이션을 가지고 있더라구요.
@SpringBootTest로 실행시킬때 해당 어노테이션들이 어떻게 가져와지는지 궁금합니다. 
@SpringBootTest는 main패키지의 @SpringBootApplication어노테이션이 붙은 클래스를 찾아 해당 패키지와 하위패키지의 빈들을 애플리케이션 컨텍스트에 등록하는 것으로만 알고 있었는데, 테스트 패키지 내의 빈들도 등록이 되는 건가요?

## ⏳ 작업 시간
추정 시간:  2시간
실제 시간:  1시간

2023-10-04 00:25 UTC, dooboocookie requested changes
이레!! 채채랑 같이 멋진 뼈대 코드를 작성해주셨네요!!

>게임 중 플레이어가 등록한 쪽지
>게임 중 플레이어가 발견한 쪽지

쪽지와 게임의 연관 관계 부분은 아직 기회적으로 정해진 내용이 없으므로 추후에 팀원들과 이야기해보아요.

>테스트 패키지의 Builder 클래스들은 모두 https://github.com/component어노테이션을 가지고 있더라구요.
https://github.com/SpringBootTest로 실행시킬때 해당 어노테이션들이 어떻게 가져와지는지 궁금합니다.
https://github.com/SpringBootTest는 main패키지의 @SpringBootApplication어노테이션이 붙은 클래스를 찾아 해당 패키지와 하위패키지의 빈들을 애플리케이션 컨텍스트에 등록하는 것으로만 알고 있었는데, 테스트 패키지 내의 빈들도 등록이 되는 건가요?

<img width="743" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/79090478/6872bb0d-b1cf-4a52-a538-1649b769ae6d">

저도 ComponentScacn의 기본 범위가 베이스패키지 즉, com.now 밑으로 알고 있는데, 테스트가 되다니 신가하네요.
아마, @SpringBootTest라서 그런거 아닐까요?
알쏭달쏭 스프링 세계

---

구조적으로는 큰 문제점은 느끼지 못했습니다.
다만 컨벤션이나 몇가지 추가할 것이 있어서 RC 남깁니다.

2023-10-04 00:25 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    private Long id;
P2:

컨벤션에 맞게 아이디 어노테이션을 필드선언부테 가깝게 붙여쥬세요

2023-10-04 00:25 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    }
(해당 PR의 변경 요구사항 아님)

저희 포지션이 정말 이곳저곳에서 많이 쓰이네요.
그렇다면 저희 포지션을 이제는 place 패키지 안에 두기는 힘들것 같아요!!

2023-10-04 00:25 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/common/builder/LetterBuilder.java
> +
P2:

불필요한 개행은 삭제해주세요

2023-10-04 00:25 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    private Player registeredPlayer;
P2:

지연로딩이 필요하지 않을까요?
findAll() 하면 player에 대한 N + 1문제가 발생할 것 같습니다.
지연로딩을 한다고 해당 문제가 해결되는 것은 아니지만 
조회 시 무조건적으로 발생시키기 보다는 필요할 때 player를 조회하는 쿼리가 나가도록 일단 지연 로딩하고
만약 plaeyr에 대한 조회가 자주 일어난다면 그때 fetch join 이나 batch select를 해오면 될 것 같아요!!

2023-10-04 00:25 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +public class Letter extends BaseEntity {
P5:

저희가 게임 같은 경우에는
BaseEntity는 DB관리 차원에서 등록일 수정일을 관리하는 것이고,
따로 게임 시작 시간을 기록하기 위해서 startTime 이라는 컬럼을 두었는데요.
해당 쪽지에서도 등록일이 유의미한 데이터인 것 같아서, 혹시 등록일을 따로 컬럼으로 하나 더 넣을 필요는 없겠쬬?

2023-10-04 09:25 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +public class Letter extends BaseEntity {
게임에서는 db 관리 차원에서의 시간과 게임 시작시간이 따로 있어야 하는 것이 맞는데 쪽지는..제 의견으로는 굳이 없어도 될것같아요! 쪽지 생성시간이 곧 쪽지 등록시간이라서..!

2023-10-06 13:01 UTC, krrong commented
클래스 다이어그램을 어떤 기능으로 그렸을지 모르겠지만 혹시나 도움이 될까하여 mermaid로도 그릴 수 있다고 알려드리러 침범했습니다 🦖
[왕초보용 참고링크](https://www.jeong-min.com/47-mermaid/)

2023-10-06 17:33 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    private Long id;
넵 자꾸 컨벤션 실수하네요 수정했습니다

2023-10-06 17:34 UTC, zillionme commented on backend/src/test/java/com/now/naaga/common/builder/LetterBuilder.java
> +
수정했습니다

2023-10-06 17:35 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    }
특히 포지션 관련 dto가 여기저기서 쓰이는 것을 보고 저도 그런 생각을 했는데, 이유가 명확하지 않아서요. place 패키지가 아니라면 개별적인 패키지로 분리를 생각하시는 건가여>?

2023-10-06 17:39 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    private Player registeredPlayer;
letter을 조회해올 때, player은 무조건적으로 조회되는 객체라고 생각했는데, 생각해보니 반경 100m 내의 쪽지를 조회해올 때는 id만 반환하므로 위와같은 지연로딩이 필요하겠네요.

n+1문제 같은 경우에는 조회 쿼리를 담당하는 팀원이, n+1문제를 해결하기에 적절한 방법을 적용하는 것이 맞다고 생각합니다!

2023-10-06 17:44 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +public class Letter extends BaseEntity {
쪽지를] 조회할 때 항상 등록시간을 보내줄 예정인데요. 하지만 저도 startTime이라는 컬럼을 따로 만들어야할 이유는 잘 모르겠습니다.
game 객체에서는 endTime이라는 필드가 있기 때문에 그에 상응하는 startTime이라는  필드가 있다고 생각했는데, 쪽지의 경우 굳이 컬럼을 추가할 필요가 있을까? 하는 생각이 듭니다

2023-10-07 12:39 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    }
네!
Position이 개별적인 도메인 패키지로 존재해도 될 것 같습니다!!

2023-10-07 12:44 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    private Player registeredPlayer;
좋습니다.
더 나아가 레이지 로딩 같은 것은 엔티티 설계 단계의 역할도 맞는 것 같긴 합니다.
대부분의 X대1 관계에서는 지연로딩을 걸어주는 편이 좋을 것 같습니다.
그것이 조회에서 많이 필요해서 fetch join을 걸지 말지는 그 조회하는 사람이 작성하더라두요!

2023-10-07 12:44 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +public class Letter extends BaseEntity {
네넵!! 저도 동의합니다!!

2023-10-07 12:45 UTC, dooboocookie approved these changes
이레 답변 잘 달아주셔서 감사해요!
가능하시다면 레이지로딩은 건 상태로 머지 부탁드립니다.
하지만 이것만으로도 충분히 머지될만하다고 생각하여 어프루브 하겠습니다!

2023-10-08 10:19 UTC, merged

2023-10-30 11:04 UTC, kpeel5839 commented
approve 가 하나인데요!!