Refactor/#391 모험 기록 뷰 디자인 변경
woowacourse-teams/2023-naaga pull request #396
Opened 2023-10-03 15:36 UTC by hyunji1203

## 📌 관련 이슈
- closed: #391 

## 🛠️ 작업 내용
- [X] 모험 기록 뷰 디자인 변경
<img width="315" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/83613106/0abdc00f-f5f8-49ac-b118-9273c7693aea">

## 🎯 리뷰 포인트
날짜의 color를 colors 리소스에 추가했는데, 네이밍 괜찮은지 궁금합니다... 구린 것 같은 느낌이 나서 찝찝하네요... 

## ⏳ 작업 시간
추정 시간:  1h 
실제 시간:  1h

2023-10-03 16:01 UTC, krrong requested changes
뽀또🍪 디자인에 뷰 작업까지 늦은 시간까지 고생이 많네요!  
뽀또가 판단하여 바로 반영할 수 있는 리뷰 2개를 남겼습니다! 확인해주시고 다시 요청해주세요!

2023-10-04 01:30 UTC, krrong requested changes

2023-10-04 01:30 UTC, krrong commented on android/app/src/main/res/values/colors.xml
> +    <color name="main_black_gray">#616161</color>
[P4]  
우리가 사용하는 컬러는 모두 main_xx 네요 ㅋㅋㅋㅋㅋㅋ 나중에 변경을 고려해도 좋겠네요!
현재 main_gray색상을 지우고 뽀또가 추가한 main_black_gray를 main_gray로 사용하면 더 좋을 것 같아요!  
만약 반영한다면 item_history.xml 에서도 변경해야 합니다! 🙃

2023-10-04 04:08 UTC, hyunji1203 commented on android/app/src/main/res/values/colors.xml
> +    <color name="main_black_gray">#616161</color>
크롱 말처럼 main_gray로 변경하였습니다!

2023-10-04 04:17 UTC, krrong approved these changes
고생했어요 뽀또🍪  
잘 반영해주셔서 머지하도록 할게요~

2023-10-04 04:18 UTC, merged