feat: 검수 중인 장소에 대한 장소 등록 허가 API 구현
woowacourse-teams/2023-naaga pull request #398
Opened 2023-10-03 16:36 UTC by kokodak

## 📌 관련 이슈
- closed: #376 

## 🛠️ 작업 내용
- [x] 장소 등록 허가 API 설계 및 구현

## 🎯 리뷰 포인트
관리자 페이지에서 사용할 검수 장소 등록 허가 API 를 구현하였습니다!

먼저, 대부분의 장소 API 엔드포인트는 사용자가 주체이지만, 등록 허가에 대한 API 는 사용자가 아닌 관리자가 주체입니다.

여기서 중요한 점은, `사용자가 주체인 API 의 인가 장치는 jwt 토큰 방식`이지만, `관리자가 주체인 API 의 인가 장치는 basic 인증 방식`입니다.

따라서, 같은 엔드포인트에 대해서 서로 다른 HTTP 메서드에 따라 인터셉터도 달라져야 했습니다.

이 부분에 대한 기술적 해결 방안은 [루카 박사님의 논문](https://github.com/woowacourse-teams/2023-naaga/pull/374) 을 통해 확인하실 수 있고, 이를 이용해 서로 다른 인터셉터를 타도록 설정해두었습니다.

또한, 결정된 서비스 비즈니스 시나리오에 의하면, 관리자 페이지에서 등록 허가 버튼을 눌렀을 때 `인게임 장소에 데이터 등록 + 검수 장소에서 데이터 삭제` 라는 행위가 한번에 이루어져야합니다.

따라서 이를 구현하기 위해 하나의 트랜잭션으로 묶어 처리했습니다.

+)
ManagerAuthInterceptor 에서 Base64 디코딩하는 과정에서 로직 오류가 있어서, 이 부분을 함께 수정했습니다.

또한, 아직 검수 장소 삭제에 대한 로직이 구현되지 않은 관계로, 임시적으로 동작하지 않는 메서드를 구현해놓았습니다. 양해 부탁드립니다!

## ⏳ 작업 시간
추정 시간:   4시간
실제 시간:   4시간

2023-10-04 04:59 UTC, dooboocookie requested changes
코선생님 역시 코드 깔끔하게 잘 짜주셨네요!!

일단 코드 매우 읽기 좋아서 잘 봤습니다!!

몇까지 의견이 있어서 RC 남기겠습니다!!

그리고 조금 추가적인 말씀 드리고 싶은게 있는데요.
약간 제가 코드를 읽으면서 느낀 점은 이 PR은 완성된 PR은 아닌것 같다는 느낌이 들었어요.
`feat: 검수 중인 장소에 대한 장소 등록 허가 API 구현` 이 피쳐를 구성하기 위해서 필요한 모든 기능이 있다기 보단,
뒤에 추가할 `거절 APi`에서 구현할 내용까지 미리 생각해서 그 PR로 업무를 조금 분배하신 느낌이 들더라구요.
진짜 극단적으로 생각하면 해당 `거절 기능에 대한 PR`은 closed 될 수 있지 않을까요?
그렇다면 해당 PR로 머지되는 커밋은 이 허가 관련 기능에 대해서 완전해야된다고 생각합니다!

이번에는 너무 연관성 있는 두 기능을 구현하다보니까 이렇게 된 것 같으니 충분히 이해합니다.

2023-10-04 04:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
> +        final String[] idAndPassword = decodedHeader.split(":");
저의 실수를 잘 수정해주셔서 감사합니다 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

2023-10-04 04:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/place/application/PlaceService.java
> +        temporaryPlaceService.deleteById(createPlaceCommand.temporaryPlaceId());
P1 or P5:
저희 사진 저장관련해서 `임시 장소`와 `진짜 장소`의 사진 자료 디렉토리를 따로 두기로 했던 것 같은데요.
혹시 그에 대한 고려는 다른 PR에서 하면될까요?

2023-10-04 04:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/place/application/PlaceService.java
> +                        final TemporaryPlaceService temporaryPlaceService,
P1:
슬랙에서도 대화 나눴던 것 처럼 (기획적인 고려는 따로 하는것으로 하면)
임시 장소를 진짜 장소로 전환할 때도 주변 위치에 대한 검증이 필요하지 않을까요?
(그리고 만약 검증이 필요없다고 생각 드신다면 밑의 주석처리 부분과 함께 없어져야될 부분 같은데, 주석처리를 부탁드립니다)

그리고 임시 장소 자체를 등록할 떄도 거리에 대한 검증이 필요할 것 같긴 합니다.
그렇다면 이 공통 검증 로직은 `temporaryplace`나 `place` 둘 중에 한 군데 존재할텐데요.

현재 `place` &rarr; `temporaryplace`이렇게 의존성이 흐르고 있는데요.
검증 로직 때문에 `temporaryplace` &rarr; `place` 이렇게도 흐를 수 있지 않을까요?

두 도메인은 매우 밀접한 연관이 있어서 서로 이것저것 맞물릴것 같은데,
도메인의 관점에서 논리적으로 어디가 어디를 의존하면 좋을지 정하고 가는것도 좋을것 같아요.

2023-10-04 04:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
> +    public ResponseEntity<PlaceResponse> createPlace(@RequestBody final CreatePlaceRequest createPlaceRequest) {
P3:

`@RequestBody`어노테이션을 붙이신 이유가 있으신가요?
저희가 지금까지 요청 바디로 받는 json은 어노테이션을 안붙였던 것 같아서요.

2023-10-04 04:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +    }
아마 뒤의 PR에서 수정하시려는 것이겠죠??????????? 
일단 가만히 있겠습니다

2023-10-04 04:59 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptorTest.java
> +        request.addHeader("Authorization", "Basic " + authHeader);
다시 한번 제 실수를 보안해주셔서 감사합니다

2023-10-04 04:59 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +    private TemporaryPlaceService temporaryPlaceService;
P2:
저희 서비스 테스트 슬라이스 테스트에서 통합 테스트로 변경하자는 의견으로 통합된 것으로 아는데요! (라임입니다)
그래서 Repository도 모킹 안하는 것이구요.

근데 따로 이 서비스만 목킹하신 이유가 있으실까요??

그리고 현재 모킹을 믿기에는 해당 클래스에 대한 테스트가 작성되어있지 않습니다.
(이것도 뒤 PR에서 적용하시려는 것이겠쬬?)

2023-10-04 04:59 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/place/presentation/PlaceControllerTest.java
> +    void 장소_등록_요청이_성공하면_201_상태코드와_생성된_장소를_응답한다() {
P2:

해당 엔드 포인트에 대해서도 
임시 장소에 대한 not found 같은 예외 상황이 존재할 것 같은데요.
혹시 이와 같은 예외 상황에 대한 테스트는 불가할까요?

2023-10-04 05:51 UTC, kokodak commented on backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
> +    public ResponseEntity<PlaceResponse> createPlace(@RequestBody final CreatePlaceRequest createPlaceRequest) {
`@RequestBody` 는 생략이 불가능한 것으로 알고있습니다. 아마 `@ModelAttribute` 와 헷갈리신걸까요?

저희는 지금까지 모든 컨트롤러 파라미터에 어노테이션을 붙여서 명시적으로 알려주고 있기도 합니다.

2023-10-04 05:56 UTC, kokodak commented on backend/src/main/java/com/now/naaga/place/application/PlaceService.java
> +        temporaryPlaceService.deleteById(createPlaceCommand.temporaryPlaceId());
저도 고민하긴 했는데.. 아직 이에 대한 기획이 확정나지 않았다고 생각해서 일단 패스해뒀습니다! (아마 그 자리에 채채가 없었던 것으로 알아서..)

2023-10-04 06:11 UTC, kokodak commented on backend/src/main/java/com/now/naaga/place/application/PlaceService.java
> +                        final TemporaryPlaceService temporaryPlaceService,
> 임시 장소를 진짜 장소로 전환할 때도 주변 위치에 대한 검증이 필요하지 않을까요?

맞습니다. 현재 시나리오 상에서는 그런 상태인데 제가 고려를 안했네요. 일단 추가해놓도록 하겠습니다!

> 도메인의 관점에서 논리적으로 어디가 어디를 의존하면 좋을지 정하고 가는것도 좋을것 같아요.

동의합니다. 말씀하신대로 두 도메인이 매우 밀접한 관계라서, 어떤 방향으로 의존성을 흘려보낼지 정해야할 것 같아요.

말씀주신 `공통 검증 로직`때문에 양방향이 걸릴 수 있는 상황이긴 합니다. 다만 이점은 중간 객체를 넣거나, DIP 를 사용해서 해결 할 수 있는 문제라고 생각하기 때문에, 의존성 방향이 중요할 것 같네요.

2023-10-04 06:26 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
> +    public ResponseEntity<PlaceResponse> createPlace(@RequestBody final CreatePlaceRequest createPlaceRequest) {
어쩌라구요.
몰랐어용..

2023-10-04 06:43 UTC, kokodak commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +    private TemporaryPlaceService temporaryPlaceService;
P2 를 붙이신 이유는 `@MockBean` 을 떼고 실제 서비스로 테스트했으면 좋겠다는 의미 맞을까용?

일단 여기에서 mocking 을 진행한 이유에는, 통합 테스트인지 슬라이스 테스트인지에 대한 여부로 결정하지 않았습니다.

중요한 점은, 이 PR을 작업하는 시점에서 삭제 API 구현은 저의 담당이 아니었기 때문에, 삭제에 대한 API 내부 구현을 고려하지 않았다는 점인데요.

제 입장에서는 삭제 로직이 어떻게 이루어질지 전혀 모르는 상황입니다. 이 상황에서 저에게 중요한 점은, `TemporaryPlaceService` 에서 `deleteById()` 메서드가 가지는 의도 혹은 의미였습니다.

내부 구현 사항을 모르기 때문에 상태 검증은 애초에 할 수 없는 상황이었고, `deleteById() 메서드를 호출하면 삭제가 된다더라` 정도의 의미만 알고있었기 때문에, 이에 대한 행위 검증을 하려고 mocking 을 하게 되었네요. (현재 시점에서는 상태보단 행위의 검증이 더 중요하기 때문에)

> 그리고 현재 모킹을 믿기에는 해당 클래스에 대한 테스트가 작성되어있지 않습니다.

아마 루카가 말씀하시려던 점은 mocking 보다는 stubbing 에 가까운 것 같네요. 관점이 다른 것 같습니다.

전 내부 구현이 어떻게 일어날지도 모르고, 루카 말씀대로 해당 메서드가 검증이 잘 되었는지도 모릅니다. 그래서 stub 을 전혀 사용하지 않았습니다.

mocking 해서 행위 검증을 하는 것은, `mocking 된 클래스가 제대로 된 동작을 하는가?` 보다는, `mocking 된 클래스를 호출하는 쪽에서 적절한 의미의 메서드를 잘 호출하였는가?` 가 중요한 것 같습니다! 제가 테스트하려고 했던 점도 후자이구요. 따라서 해당 mocking 클래스에 대한 테스트 여부는 여기서 중요하진 않은 것 같네요.

2023-10-04 08:00 UTC, kokodak commented
> 그리고 조금 추가적인 말씀 드리고 싶은게 있는데요.
약간 제가 코드를 읽으면서 느낀 점은 이 PR은 완성된 PR은 아닌것 같다는 느낌이 들었어요.
feat: 검수 중인 장소에 대한 장소 등록 허가 API 구현 이 피쳐를 구성하기 위해서 필요한 모든 기능이 있다기 보단,
뒤에 추가할 거절 APi에서 구현할 내용까지 미리 생각해서 그 PR로 업무를 조금 분배하신 느낌이 들더라구요.
진짜 극단적으로 생각하면 해당 거절 기능에 대한 PR은 closed 될 수 있지 않을까요?
그렇다면 해당 PR로 머지되는 커밋은 이 허가 관련 기능에 대해서 완전해야된다고 생각합니다!

이점에 대해서는 개인적인 의견이 있습니다. 일단 전반적인 맥락을 말씀드리고, 루카와 반대되는 의견을 주장해볼게요.

첫번째!

> feat: 검수 중인 장소에 대한 장소 등록 허가 API 구현 이 피쳐를 구성하기 위해서 필요한 모든 기능이 있다기 보단,
뒤에 추가할 거절 APi에서 구현할 내용까지 미리 생각해서 그 PR로 업무를 조금 분배하신 느낌이 들더라구요.

아마 루카가 이런 생각을 하신 이유는, 아무일도 하지 않는 임시방편의 코드 때문이겠죠?!

결론부터 말씀드리자면, 해당 API 구현 내용은 전혀 생각하지 않고 작업했습니다. 이 PR을 작업할 시점에서 삭제 API 의 원래 담당자는 제가 아닌 이레였는데요, 이 PR을 작업하다보니 삭제에 대한 로직이 필수로 필요했었습니다.

저도 이 PR 이 나올때, 등록 허가에 대한 모든 기능이 포함되어서 나왔으면 좋았겠지만, 만약 포함시켰다면 이는 하나의 일을 하는 PR 이 아닙니다. (물론 ManagerAuthInterceptor 를 이 PR에서 고쳐서 할 말이 없긴 합니다만...)

API 를 뚫는 행위는 코드량으로는 적을 수 있지만, 의미적으로는 큰 태스크라고 생각합니다. 한 PR 안에서 등록 허가 API 와 삭제 API 로직 구현을 모두 하고 싶지는 않았습니다. 또한, 그것을 나누는 것이 코드 리뷰를 하는 사람 입장에서도 따라가기 수월할 거라고 생각했습니다.

다만, 제가 이 PR 코멘트에 전반적인 맥락을 담지 않았었기 때문에(임시방편의 코드가 왜 있는건지 등등).. 코드리뷰하는 사람에게 혼란을 줄 수도 있었겠다고 생각되네요. 이 부분은 반성하겠습니다 ㅠㅠ

말씀드리고 싶었던 점은, 당시 담당자였던 이레와 미리 의논하면서, 삭제에 대한 메서드 스펙을 미리 맞추어놓았고, 해당 메서드가 어떤 서비스에서 가질지도 미리 맞추어놓다보니, 저는 해당 의논 내용을 토대로 임시방편의 코드를 넣게 되었습니다. (이렇게 해야 merge conflict 범위가 최소화될 것이라 생각했습니다)

두번째!

> 진짜 극단적으로 생각하면 해당 거절 기능에 대한 PR은 closed 될 수 있지 않을까요?

말씀하신대로, 정말 극단적으로 생각한다면 거절 기능 PR은 closed 되고, 이에 대한 기능이 등록 허가 PR 내부로 흡수될 수도 있다고는 생각합니다.

다만 이것은 저희 팀의 규모가 충분히 작다는 점, 그리고 거절 기능에 대한 작업량이 많지 않았다는 점들이 복합적으로 맞물려서 이와 같은 생각이 드는 것 같아요.

만약 저희 팀의 규모가 더 커서 업무 부서가 다 찢어져있거나, 거절 기능에 대한 작업량이 많아서 한 PR에 합쳐질 규모가 아니라면.. 이때는 서로 깊은 연관성이 있는 PR 이더라도 분리시켜서 작업하는 것이 맞다고 생각합니다.

저는 보다 일관적이고 일반적인 방법론을 적용하는 것을 선호하는데요. 팀의 규모 크던 작던, 그 PR의 작업량이 많던 적던, 그것에 신경쓰지 않고 적용할 수 있는 방법론은 `PR의 연관성이 짙던 얕던, 의미적으로 혹은 작업량적으로 큰 작업들은 한개이상의 PR로 적절히 분리되어 찢어져야한다` 라고 생각합니다.

세번째!

> 그렇다면 해당 PR로 머지되는 커밋은 이 허가 관련 기능에 대해서 완전해야된다고 생각합니다!

전 이 부분에 동의하지 않아요 (루카형이 싫어서 그런게 아닙니다 알죠?)

저희 팀이 모두 동의했었던, `PR을 작게 유지하자!` 룰이 도입된 순간부터, 항상 PR의 작업 커밋들의 모음이 하나의 완전한 기능을 의미한다는 것을 보장할 순 없습니다.

중요한 점은, 현재 이 PR이 merge 되고 싶어하는 브랜치는 운영 브랜치가 아닌 개발 브랜치라는 점이라고 생각해요. 운영 브랜치에 나가는 코드들은 모두 완전한 기능을 갖춘 상태로 나가야한다 생각하지만, 개발 브랜치는 그렇지 않습니다. 저는 개발 브랜치에 있는 코드들이 모두 완전한 기능을 하진 않아도 된다고 생각해요.

개발 브랜치에 올라와있는 어떤 API 코드는 실제로 동작하진 않지만, 그 기능을 완수하기 위해 공사중인 코드일 수도 있구요. 완전하지 않지만 PR을 작게 유지하면서 dev 브랜치에 꾸준히 merge가 되는 것이, 훗날 팀원들의 merge conflict 비용을 줄여주는 행위이고, 이것이 진짜 지속적 통합이라고 생각합니다.

이와 관련해서 [이 글](https://blog.banksalad.com/tech/banksalad-code-review-culture/)에 좋은 내용이 담겨있는데요!

여기서 있는 사진을 보시면 이해가 되실거라 생각합니다.

<img width="669" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/45879491/6febe0ee-03ac-49ba-9a56-67a55da2c6d8">

이런 관점에서, 장소 등록 허가 PR은 이번 PR 한번으로 완성이 될 수 없는 작업물이라고 생각합니다.

장소 등록 허가 API 에서 사용할 삭제 로직이 아직 완전하지 않아서, 이번 PR이 merge 된다해도 장소 등록 허가 API 기능이 동작할 순 없겠지만.. 

여러번에 걸쳐서 하나의 기능이 완성될 수 있다고 생각하고, 그게 팀적으로 좋은 방향이라 믿고 있습니다.

2023-10-04 11:50 UTC, dooboocookie approved these changes
파일 저장 관련 해서는 앞으로 기능 개발 하고 S3붙여나가면서 추가적으로 배워나가면 될 것 같구,
PR 단위 관련해서는 팀끼리 이야기 해보아요

2023-10-04 11:50 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +    }
테스트 잘 짜셨네요! 훌륭합니다!

2023-10-04 11:53 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +    private TemporaryPlaceService temporaryPlaceService;
P2를 단 이유는 기능 TemporyPlaceService를 구현해야될 담당자가 `이 PR의 코코닥`라고 생각했어요.
해당 메서드에 대한 단위테스트가 진행되지 않은 상황에서
그 메서드를 사용하는 테스트를 통합으로 하지 않고 모킹해서 사용한다는 것을 지적한것이였습니다.
하지만 코코닥께서 PR 단위에 대해서 언급을 하셨으니, 이것은 팀끼리 차차 이야기해나가보아요

2023-10-04 16:47 UTC, chaewon121 approved these changes
코코닥 안녕하세요~! 깔끔하게 잘 구현해 주셨군요. 다만 살짝 아쉬운 점이 있다면 해당 pr은 삭제 기능이 먼저 만들어 진 후에 이뤄져야 했던 pr이었나 하는 생각이 듭니다! 일단 완성되지 않은 temporaryPlaceService.deleteById(createPlaceCommand.temporaryPlaceId()); 기능이 매서드만 존재할 뿐더러 테스트에서도 존재하지 않는 기능때문에 강제(?) 로 모킹 한 부분에 대해서 아쉬운 부분이 있네요..! 이부분에 대해서는 추후에 백엔드 끼리 논의해 보면 좋을 것 같습니다! 
고생 많으셨고 저는 auth파트가 매우 어렵게 느껴지는데 루카의 코드에 이어서 잘 작성해 주셨군요 굳~!

2023-10-04 16:47 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +}
저도 가만히 있겠습니다

2023-10-04 16:47 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +                                                                             "이곳은 루터회관이다 알겠냐",
화 잔뜩난 코닥선생..

2023-10-04 17:06 UTC, kokodak commented
채채 리뷰 감사합니다!

확실히 삭제 기능을 먼저 만들고 이번 PR 작업을 했으면 훨씬 매끄러웠을 것 같아요.. 🥲

추가적으로 채채가 언급해주신 주석은 모두 삭제하였습니다!! 같이 작업했던 이레가 혹시나 참고할 수 있게 남겨두려고 주석 처리를 해놨었는데, 이제 관리자 API 가 다 올라온 것 같아서 주석은 전부 지웠습니다! 언급 안해주셨으면 깜빡할뻔했네요.. 감사합니다!!!

2023-10-05 00:38 UTC, zillionme approved these changes
코선생... 제가 삭제 API를 만들지 않아 많은 고초를 겪으셨군요...
저 대신 삭제 API까지 만들어주셔서 감사합니다.
크게 리뷰할 점이 보이지 않아서 어프루브 하도록 하겠숩니다.
저는 PR을 나누는 기준에 대해 코코닥의 의견에 전적으로 동의해서 그 부분에 관해서도 얘기할 게 없네요.

다만 나중에 임시 장소 사진 디렉토리와 진짜 장소 사진 디렉토리를 어떻게 나누고, 플로우는 어떻게 짤지 얘기해보아요
수고하셨습니다😇

2023-10-05 00:38 UTC, zillionme commented on backend/src/main/java/com/now/naaga/place/application/PlaceService.java
> +        temporaryPlaceService.deleteById(createPlaceCommand.temporaryPlaceId());
`placeCheckService.checkOtherPlaceNearby(createPlaceCommand.position());
`이 부분은 제외 되는 건가요?
+) 루카 말대로 후에 image 위치 변경 작업이 일어난다면 임시 장소 사진 디렉토리에서 진짜 장소 사진 디렉토리로 파일 복사 후, 임시 장소 사진이 삭제되는 플로우가 될까요?

2023-10-05 00:38 UTC, zillionme commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +    }
테스트 👍🏻
assertSoftly의 사용 이유가 뭔가용?

2023-10-05 01:07 UTC, zillionme commented on backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
>                              String name,
placeResponse에 player 정보는 들어가지 않나요?
누가 등록했는지 전달해주기로했던 것 같아서요

2023-10-05 01:09 UTC, kokodak commented on backend/src/main/java/com/now/naaga/place/application/PlaceService.java
> +        temporaryPlaceService.deleteById(createPlaceCommand.temporaryPlaceId());
> placeCheckService.checkOtherPlaceNearby(createPlaceCommand.position()); 이 부분은 제외 되는 건가요?

앞으로 제외될 것이냐고 물어보시는건지, 지금 제외되어있어서 추가해달라는 말씀이신지 헷갈리네요 🥹

앞으로 제외될 것인가에 대해서는, 그럴 수 있다고 생각합니다!!

지금 제외되어있냐고 물어보신거라면, 현재 존재하는 로직입니다!!

> 루카 말대로 후에 image 위치 변경 작업이 일어난다면 임시 장소 사진 디렉토리에서 진짜 장소 사진 디렉토리로 파일 복사 후, 임시 장소 사진이 삭제되는 플로우가 될까요?

맞아용!

2023-10-05 01:15 UTC, kokodak commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +    }
assertSoftly 를 통한 검증을 했을 때 테스트가 실패하면, 기존 assertAll 보다 친절한 문구가 제공됩니다.

2023-10-05 01:17 UTC, kokodak commented on backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
>                              String name,
Place 응답 DTO 는 시나리오상 player 정보가 필요 없습니다!

2023-10-05 01:31 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
>                              String name,
```java
{
	"id": 1,
	"name": "루터회관",
	"description": "이곳은 루터회관이다",
	"coordinate": {
		"latitude": 37.123456,
		"longitude": 127.123456
	},
        "imageUrl": "image.path/123.png",
        "registeredPlayer: {
		"id": 1,
		"nickname": "뽀또",
		"totalScore": 1
        }
}
```

2023-10-05 01:54 UTC, merged