feat: 검수 중인 장소에 대한 등록 승인 거절 API 구현
woowacourse-teams/2023-naaga pull request #401
Opened 2023-10-03 18:36 UTC by kokodak

## 📌 관련 이슈
- closed: #388 

## 🛠️ 작업 내용
- [x] 검수 장소에 대한 삭제 API 구현

## 🎯 리뷰 포인트
[이 PR](https://github.com/woowacourse-teams/2023-naaga/pull/398) 에 대한 연장선인 작업물입니다.

따라서, PR의 내용에 대한 맥락은 위 PR 과 같습니다. 참고해주세요!

관리자 페이지에서 사용할 승인 거절은 결국 DB 단에서의 단순 삭제 로직이라서, 크게 어려운 점은 없었던 것 같습니다.

그나마 고민했던 지점은, 검수 장소 삭제에 대해 soft delete 할 것인지, hard delete 할 것인지였는데요!

검수 장소 엔티티가 복잡한 연관관계를 가지는 것도 아니고, 검수 승인 거절을 하였는데 DB 단에 굳이 남겨서 리소스를 낭비할 필요는 없을 것 같아 hard delete 로 구현하게 되었습니다!

+)

# [작업 커밋 범위](https://github.com/woowacourse-teams/2023-naaga/pull/401/files/23814c18af6365d808a192fdfdd8d821f5768c6d..6581ef9d65cc16e409b179770cfbe07790455131)

이전 PR 브랜치에 리베이스해서 작업했더니, 커밋 내역이 같이 딸려와서 위에 커밋 범위를 남겨놓겠습니다!!

참고해서 리뷰해주시면 감사하겠습니다 😁

## ⏳ 작업 시간
추정 시간:   2시간
실제 시간:   2시간

2023-10-04 05:45 UTC, dooboocookie requested changes
안녕하세요 코코닥!

이 PR 코드 변경사항에 해당되지 않아서 이곳에서 리뷰할 것이 2가지 있는데요.

# 1. `TemporaryPlace` 도메인 엔티티의 소프트 딜리트 여부
- 해당 도메인 엔티티는 웬만하면 `Place`로 이동되는 데이터라 굳이 소프트 딜리트가 필요 없을 수도 있을것 같습니다.
- 만약, 유저에게 거절 사유에 대해서 공지해주는 시나리오가 나오면 어떻게 될까요? 일단 그때는 삭제 시나리오가 아닐 것 같긴하지만 거절 당한 레코드는 소프트 딜리트하는 것도 좋아보이는데요.
- 그렇다면 소프트 딜리트를 도입하는 것이 좋아보이지 않나요?

# 2. Player 필드의 지연로딩
- 이것은 조회에 대한 것이기 때문에 문제만 제시하겠습니다.
- 기본적으로 `@ManyToOne`은 즉시 로딩이 디폴트이기 떄문에 `임시 장소 전체 목록을 조회`할 때, `Player를 각각 가져오게` 됩니다. 이것이 바로 `N+1`문제겠지요?
- 제가 보기엔 일단 전체 조회할 때 Player에 대한 정보가 필요 없기 떄문에 `지연로딩`만 걸어놓고, 만약 전체 조회에서 Player 정보를 꼭 필요로 할 때, Fetch Join이나 Batch 셀렉트를 도입하면 되겠죠?

이전 PR과 연장선에 있는 PR 이라서 따로 떼어놓고 리뷰하는 것이 쉽지 않네요.

파이팅

2023-10-04 05:45 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +        temporaryPlaceRepository.deleteById(id);
P2:
삭제를 하려고 했는데, 해당 `임시 장소`가 없으면 어떻게 되어야할까요?
현재로서는 아무 예외도 뱉지 않고 204 정상 응답을 해주는데요.
의도하신 바 같기도 합니다. 왜냐면 결국엔 이 API 를 사용한 유저가 원하는 상태로 서버가 되었으니까요.
제 생각엔 NOT FOUND를 응답해주는 것이 맞다는 생각이 있는데 어떻게 생각하세요?

2023-10-04 05:45 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/temporaryplace/application/TemporaryPlaceServiceTest.java
> +    private TemporaryPlaceRepository temporaryPlaceRepository;
P2:

이번에도 마찬가지로 모킹하신 이유가 따로 있으신가요??

2023-10-04 05:45 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +        temporaryPlaceRepository.deleteById(id);
P1:
삭제하고 나서 해당 사진 파일을 삭제하는 과정이 필요해보입니다

2023-10-04 13:06 UTC, kokodak commented on backend/src/test/java/com/now/naaga/temporaryplace/application/TemporaryPlaceServiceTest.java
> +    private TemporaryPlaceRepository temporaryPlaceRepository;
다시 상태 검증 테스트로 변경하였습니다!

추후에 팀적으로 서비스 테스트에 대해 얘기하고 싶은 점들이 있어서, 이점은 슬랙이나 구두로 말씀드리겠스빈다

2023-10-04 13:40 UTC, kokodak commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +        temporaryPlaceRepository.deleteById(id);
`삭제 시점에 리소스가 존재하지 않는다면 404 반환` 을 거치기 위해선, 리소스가 없을 때 개발자가 알 수 있는 장치가 있어야 합니다.

이때 `deleteById()` 내부적으로 `findById()` 가 일어나고, 존재하지 않는다면 `EmptyResultDataAccessException` 예외를 던져주는 것으로 알고 있었는데, 이에 관련된 [Spring Data JPA issue](https://github.com/spring-projects/spring-data-commons/issues/2651) 에 따르면, 더 이상 예외를 던져주지 않는다고 하네요...

그렇다면 삭제 전에 `findById()` 를 직접 호출하고, Optional 처리를 통해 예외를 직접 던져주어야겠는데요! 이에 대해 괜찮다고 생각하시나요?

또한, 루카가 말씀하신 DELETE 메서드의 멱등성을 고민해봤는데요!

응답을 받는 클라이언트 입장에서의 멱등성이라 한다면, 해당 리소스가 있던 없던, 항상 같은 204 응답을 내려주는 것도 괜찮을 것 같아요.

서버 리소스에서의 멱등성이라 한다면, 리소스를 삭제하는 행위를 반복하더라도 서버의 상태는 변하지 않기 때문에, 클라이언트한테는 상황마다 다른 응답을 내려주는 것 또한 괜찮을 것 같네요.

2023-10-04 13:42 UTC, kokodak commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +        temporaryPlaceRepository.deleteById(id);
> P1:
삭제하고 나서 해당 사진 파일을 삭제하는 과정이 필요해보입니다

슈퍼 인정합니다. 다만 해당 작업은 FileManager 를 건드려서 추가적인 메서드를 뽑아내야하는 작업이기때문에... 이는 다른 PR 작업으로 분리하는게 어떨까요??

2023-10-04 13:43 UTC, kokodak commented
소프트 딜리트 같은 경우에는, 루카랑 저랑 오늘 나눈 이야기를 따로 정리해서 올려보겠습니다!

2023-10-04 17:11 UTC, kokodak commented
아이고.. 제가 이전 PR과 동기화 시킨다고 rebase로 끌고왔다가 커밋 해시 값이 바뀌어서 커밋 범위가 안떴나보네요 🥲 수정해놓겠습니다!

2023-10-05 00:48 UTC, dooboocookie approved these changes

2023-10-05 00:51 UTC, zillionme approved these changes
코코닥 저의 삭제 API구현을 가져가 주셔서 감사합니다
코드

2023-10-05 00:51 UTC, zillionme commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +        temporaryPlaceRepository.deleteById(id);
멱등성을 지키기 위해, 자료가 존재하지 않더라도 204응답을 내려주는 것 배워갑니다👍🏻👍🏻

> findById() 를 직접 호출하고, Optional 처리를 통해 예외를 직접 던져주어야겠는데요

그런데 예외를 던져주게 되면 204 상태코드를 내려줄 수 없지 않나요?

2023-10-05 00:51 UTC, zillionme commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +    void 장소를_등록한_뒤_기존의_검수_장소_데이터는_삭제한다() {
P5:
임시 장소 삭제까지가 createPlace의 플로우라면 이 또한 같이 테스트 해야하지 않을까요?
@MockBean을 @Autowired로 고치고 실제로 임시 장소가 삭제되었는지 확인해야 테스트의 완성도가 높아질것 같습니다.

2023-10-05 00:51 UTC, zillionme commented on backend/src/test/java/com/now/naaga/place/presentation/PlaceControllerTest.java
> +                .body(createPlaceRequest)
깔끔한 테스트네요 👍🏻

2023-10-05 01:38 UTC, kokodak commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +        temporaryPlaceRepository.deleteById(id);
맞습니다! 예외를 던지면 204 를 못내려주겠죵?

만약 응답에 대한 멱등성을 지키고자한다면, 예외를 터뜨리지 않는 방향으로 구현하게 될 것 같습니다!

2023-10-05 01:49 UTC, kokodak commented on backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
> +    void 장소를_등록한_뒤_기존의_검수_장소_데이터는_삭제한다() {
반영했습니다

2023-10-05 02:11 UTC, merged