feat: 검수할 장소 등록/ 조회 API 구현
woowacourse-teams/2023-naaga pull request #404
Opened 2023-10-04 03:58 UTC by zillionme

## 📌 관련 이슈
- closed: #387 

## 🛠️ 작업 내용
- [x] 검수할 장소 등록/ 조회 API 구현

## 🎯 리뷰 포인트
기획적인 문제 : 주변 장소 20m안에 다른 장소 있으면 등록 못하게 막는것을 유지할것인가
에 대해서 유저에게 빠른 피드백을 주기 위해 장소 검수를 등록하는 시점에 확인해야한다고 생각했습니다.
따라서 처음에는 검수 할 장소 등록 시점에 20m내에 다른 장소가 있으면 등록 자체를 막았는데요. 안드로이드의 뷰 구현 문제도 있고 해서 최종적으로 삭제하게 되었습니다.

루카의 장소 등록 기능을 거의 그대로 가져왔기 때문에 구현에 오랜시간이 걸리지는 않았습니다.

### 궁금한점
루카에게 기술적인 질문인데요 : 
1. FileManager 클래스에서 
File(savedDirectory) = 입력값으로 넣어준 경로에 실제 디렉토리 생성, 
Fille(savedDirectory, savedFilename) = 특정 경로에 특정 파일명을 가진 파일 생성이 맞나요?
2. 이때, 저장되는 savedFilename(파일명)이 난수가 되는데,
유저가 Place를 불러올 때, 이 안에 저장되는 imageUrl은 http;//나아가~/난수.png가 되는 건가요?

## ⏳ 작업 시간
추정 시간:   2시간
실제 시간:   4시간

2023-10-04 07:14 UTC, dooboocookie requested changes
이레 꼼꼼하게 코드 작성 잘 해주셨네요!!

일단 중요한 변경사항이 있어서, RC남기겠습니다!
**지연로딩은 꼭 걸어야할 것 같습니다.**

그리고 이레 작업 단위는 명확하게 나눠 주세요.
지금 
GET /places -> GET /temp로 바꾸는 작업과
POST 작업이 
PR에 섞여 있어서 리뷰 포인트를 잡기가 쉽지 않네요!!

# 이 밑은 질문 내용

>File(savedDirectory) = 입력값으로 넣어준 경로에 실제 디렉토리 생성,

조금 더 명확하게 저부분에선 그냥 자바의 File 인스턴스를 만드는 것 뿐입니다.
실제 디렉토리 생성은 
```java
if (directory.mkdirs()) { ... }
```
이 이프문 조건식인 mkdirs가 해줍니다.

>Fille(savedDirectory, savedFilename) = 특정 경로에 특정 파일명을 가진 파일 생성이 맞나요?

이 부분도 저것은 FIle 인스턴스만 생성하는 것이구요,
파일 생성은

```java
multipartFile.transferTo(uploadPath);
```
이 멀티파트 메서드가 해당 파일 객체가 가리키는 경로에 파일을 작성하는 것입니다.

> 이때, 저장되는 savedFilename(파일명)이 난수가 되는데,
유저가 Place를 불러올 때, 이 안에 저장되는 imageUrl은 http;//나아가~/난수.png가 되는 건가요?

넵 맞습니다.

2023-10-04 16:05 UTC, kokodak requested changes
안녕하세요 이레!

PR 작업물 잘 봤습니다! 기존의 장소 등록 로직도 잘 옮겨주신 것 같고, 전체 조회도 잘 작성해주신 것 같아요.

다만 저도 중요한 변경점이 있어서 RC 요청드립니다!!

또한 루카 말대로 등록 API 와 조회 API 변경사항들이 하나의 PR 에 뭉쳐있어서, 정확한 컨텍스트 파악이 비교적 어려울 수 있을 것 같아요.. 다음부터는 나눠서 진행주시면 감사하겠습니다 😁

2023-10-04 16:05 UTC, kokodak commented on backend/src/test/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceControllerTest.java
> +        });
P2:

```suggestion
final List<TemporaryPlaceResponse> actual = extract.as(new TypeRef<>(){});
```

extract 객체에서 List 형식으로 결과 값을 직렬화시킬때는 위 코드처럼 작성해주셔도 됩니다 ㅎㅎ

2023-10-04 17:37 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceController.java
> +        final List<TemporaryPlace> temporaryPlaces = temporaryPlaceService.findAllPlace();
api 명세 얘기가 될 것 같은데요,,! 저희는 지금까지 정렬이 필요한 모든 api에 쿼리 스트링으로 조건을 달아주었습니다. 서비스 로직에서 시간 순으로 정렬을 하는 것이 보이는데 쿼리스트링으로 조건을 걸어줄 필요성에 대해서 이래 의견은 어떠신가요!?

2023-10-05 01:08 UTC, zillionme commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +        final List<TemporaryPlace> temporaryPlaces = temporaryPlaceRepository.findAll();
API명세에 player관련 명세가 없어서 아무생각없이 코드를 짜버렸네요. 조회 쿼리를 다루면서 N+1문제에 대해서도 깊은 고민을 안했군요...ㅎㅎ
감사합니다

2023-10-05 01:13 UTC, zillionme commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +    }
> 기획적인 문제 : 주변 장소 20m안에 다른 장소 있으면 등록 못하게 막는것을 유지할것인가
> 에 대해서 유저에게 빠른 피드백을 주기 위해 장소 검수를 등록하는 시점에 확인해야한다고 생각했습니다.
> 따라서 처음에는 검수 할 장소 등록 시점에 20m내에 다른 장소가 있으면 등록 자체를 막았는데요. 안드로이드의 뷰 구현 문제도 있고 해서 최종적으로 삭제하게 되었습니다.
이부분에 대해서는 위에 리뷰 포인트로 남겨두었는데요. 슬랙에서 얘기 나눈대로 안드 쪽에서도 아직 구현이 안된 부분이라 후일에 논의가 끝나면 다시 추가해도 될 것 같습니다

2023-10-05 01:14 UTC, zillionme commented on backend/src/main/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceController.java
> +                .location(URI.create("/temporary-places/" + temporaryPlace.getId()))
관리자 페이지에서 임시장소 하나하나를 따로 볼 수도 있고 후에 확장성을 고려해서 위와 같이 코드를 짰숩니다~

2023-10-05 01:32 UTC, zillionme commented on backend/src/test/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceControllerTest.java
> +        });
공부해오겠습니다... ㅜㅜ

2023-10-05 02:16 UTC, zillionme commented on backend/src/main/java/com/now/naaga/temporaryplace/application/dto/CreateTemporaryPlaceCommand.java
> +                                          MultipartFile imageFile)  {
고쳤습니다!

2023-10-05 02:25 UTC, zillionme commented on backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
> +            uploadPath.delete();
좋습니다 해당 내용 이슈로 파두도록 하겠습니다

2023-10-05 02:32 UTC, zillionme commented on backend/src/main/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceController.java
> +        final List<TemporaryPlace> temporaryPlaces = temporaryPlaceService.findAllPlace();
이것도 얘기를 나눠봐야 할 것 같은데요 API명세 상으로는 아직 관련 내용이 적용되지 않아서.
+ 관리자 페이지에서 오래된 순으로 하는 게 정해져 있을 것 같아서  위와같이 코드를 짜게 되었습니다

2023-10-05 02:33 UTC, dooboocookie approved these changes
잘 적용해주셨네요

2023-10-05 02:35 UTC, kokodak approved these changes
고생하셨습니다~

2023-10-05 03:00 UTC, merged