refactor: 게임 시작 뷰 디자인 변경
woowacourse-teams/2023-naaga pull request #408
Opened 2023-10-04 10:50 UTC by briandr97

## 📌 관련 이슈
- closed #403 

## 🛠️ 작업 내용
- [x] 게임 시작 뷰를 리디자인된 뷰로 변경합니다.

## 🎯 리뷰 포인트
버튼 배경을 넣는 것에 이슈가 조금 있네요. 뭐가 불가능하다 이런 이슈는 아니구용
노란 버튼의 경우 여러군데에서 쓰이는데 높이가 다 다릅니다.
근데 각 버튼을 svg든 png든 export해보면 각각 다른 높이를 갖고 export됩니다.
그래서 이 부분에 대해 어떻게 해야할지 같이 고민해봐야할 것 같은데
제 개인적인 생각으로는 제일 높이가 낮은 svg를 하나 뽑고 더 큰 경우엔 padding 값으로 조절하는게 어떤가 합니다.
그렇지 않으면 각 높이별로 drawable을 다 만들어야하지 않을까 싶습니다.

- 리뷰 포인트

## ⏳ 작업 시간
추정 시간:   1h
실제 시간:   1.5h

2023-10-04 12:13 UTC, krrong requested changes
고생하셨습니다 빅스!💻  
금방 생각해볼 수 있는 것 몇 개를 코멘트로 달아두었습니다! 확인 부탁드릴게요~!  
빅스 덕분에 좋은 속성들을 알아가네요 감사합니다~!  

> 제 개인적인 생각으로는 제일 높이가 낮은 svg를 하나 뽑고 더 큰 경우엔 padding 값으로 조절하는게 어떤가 합니다.

이 의견에 적극 동의합니다! 현재 Pr이 머지되는대로 다른 뷰들도 수정하면 좋겠어요 :)

2023-10-04 12:13 UTC, krrong commented on android/app/src/main/res/layout/activity_begin_adventure.xml
> +            app:layout_constraintDimensionRatio="1.7:1"
👍  

[P5]  
빅스도 알고있겠지만 xml에서도 자동정렬을 하면 순서가 알맞게 변경됩니다! 가끔 id가 아래있어서 어리버리 했던 적이 있어서 남겨보아요🙃

2023-10-04 12:13 UTC, krrong commented on android/app/src/main/res/layout/dialog_location_permission.xml
> +            android:textSize="16dp"
[P3]  
dp로 지정해준 이유가 있을까요?!

2023-10-04 12:13 UTC, krrong commented on android/app/src/main/res/layout/dialog_location_permission.xml
> +            android:fontFamily="@font/pretendard_medium"
[P4]  
다이얼로그에서의 폰트는 기존에 사용하던 폰트를 유지하려고 하신거겠죠?

2023-10-04 12:13 UTC, krrong commented on android/app/src/main/res/values/styles.xml
> +        <item name="android:letterSpacing">0.2</item>
이렇게 자간도 설정해줄 수 있군요..! 또 하나 배워갑니다~

2023-10-04 14:28 UTC, briandr97 commented on android/app/src/main/res/values/styles.xml
>      <style name="BeginActivity.Button">
반영했습니다

2023-10-04 14:34 UTC, briandr97 commented on android/app/src/main/res/layout/activity_begin_adventure.xml
> +            app:layout_constraintDimensionRatio="1.7:1"
저도 영문은 모르겠지만 언제부턴가 xml이 자동정렬 되지 않습니다. 저도 그 이유를 몰라서 아직 못 고치고 있네요.

언급해주신 부분에서는 어느 부분의 순서가 안 맞는지 알려주실 수 있으신가요?

2023-10-04 15:06 UTC, krrong commented on android/app/src/main/res/layout/activity_begin_adventure.xml
> +            app:layout_constraintDimensionRatio="1.7:1"
아하 그런 문제가 있었군요...! 그건 몰랐네요😢  
제가 언급한 부분보다 더 많이 변경되는 부분을 찾아보면 이렇게 변경됩니다!
```xml
        <androidx.appcompat.widget.AppCompatButton
            android:id="@+id/btn_beginAdventure_myPage"
            android:layout_width="0dp"
            style="@style/BeginActivity.Text"
            android:textSize="24sp"
            android:layout_height="wrap_content"
            android:background="@drawable/bg_blue_button"
            android:text="@string/beginAdventure_my_page"
            app:layout_constraintStart_toEndOf="@id/btn_beginAdventure_upload"
            app:layout_constraintEnd_toEndOf="@id/btn_beginAdventure_begin"
            app:layout_constraintTop_toTopOf="@id/btn_beginAdventure_upload"
            app:layout_constraintBottom_toBottomOf="@id/btn_beginAdventure_upload" />
```

```xml
        <androidx.appcompat.widget.AppCompatButton
            android:id="@+id/btn_beginAdventure_myPage"
            style="@style/BeginActivity.Text"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:background="@drawable/bg_blue_button"
            android:text="@string/beginAdventure_my_page"
            android:textSize="24sp"
            app:layout_constraintBottom_toBottomOf="@id/btn_beginAdventure_upload"
            app:layout_constraintEnd_toEndOf="@id/btn_beginAdventure_begin"
            app:layout_constraintStart_toEndOf="@id/btn_beginAdventure_upload"
            app:layout_constraintTop_toTopOf="@id/btn_beginAdventure_upload" />
```
별건 아니지만 개인적으로는 정렬된게 보기엔 편하긴 하더라구요. 하지만 자동정렬 기능이 불가능하여 반영은 어려워 보이니 패스하셔도 됩니다 :)

2023-10-04 15:16 UTC, briandr97 commented on android/app/src/main/res/layout/dialog_location_permission.xml
> +            android:fontFamily="@font/pretendard_medium"
네 기존의 폰트를 유지하는 것으로 합의가 조금 전에 됐네요! 이대로 진행하겠습니다!

2023-10-04 15:16 UTC, briandr97 commented on android/app/src/main/res/values/styles.xml
> +        <item name="android:letterSpacing">0.2</item>
저도 그저 구글링 했을뿐..!

2023-10-04 15:16 UTC, briandr97 commented on android/app/src/main/res/layout/dialog_location_permission.xml
> +            android:textSize="16dp"
말씀드렸던 버튼 문제 때문이었습니다. 현재 버튼의 height를 고정 dp로 주고 있기 때문에 글자를 sp로 두어 사용자의 폰트가 커지게 되면 배경이 함께 커지지 못하고 글자가 가려지는 현상이 발생합니다.

하지만 위치 권한 다이얼로그의 버튼 배경을 최소 기준점으로 잡는데 합의가 된 것 같아서 변경하였습니다!

2023-10-05 01:02 UTC, krrong approved these changes
잘 반영해주신 것 같아 이만 머지하도록 하겠습니다!

2023-10-05 01:02 UTC, merged