refactor: 스플래시 디자인 변경
woowacourse-teams/2023-naaga pull request #416
Opened 2023-10-04 14:58 UTC by krrong

## 📌 관련 이슈
- closed: #415 

## 🛠️ 작업 내용
- [x] 안드로이드 12부터 필수인 스플래시가 안보이는 것**처럼** 변경
- [x] 스플래시 로고, 배경을 변경

## 🎯 리뷰 포인트
[실행 gif](https://github.com/woowacourse-teams/2023-naaga/assets/84285337/11c0a317-155a-45ae-a32f-1da5a33471f1)
- 실제로 안드로이드 12 스플래시를 안보이도록 하는 것이 아니라 단순히 아이콘을 투명하게 처리하여 보이지 않는 것처럼 만들었습니다... 더 좋은 방법이 있는지는 잘 모르겠어요 😢  

## ⏳ 작업 시간
추정 시간: 1h  
실제 시간: 1h

2023-10-04 16:19 UTC, hyunji1203 requested changes
크롱🦖 하루종일 정말 고생많았어요..
저는 현재 구현해 놓은 스플래시 맘에 듭니다!
아 그리고 궁금한 부분에 대해 코멘트 남겨놨는데 확인해주시면 됩니다! 👍

2023-10-04 16:19 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
> +        setTheme(R.style.Theme_Naaga)
[P5]
해당 코드가 없어도 차이가 없어 보이는데 이 코드를 추가해 준 이유가 무엇인가요? 궁금해서 물어봅니다!😁

2023-10-05 01:32 UTC, briandr97 reviewed
기본 스플래시를 안보이게 한 이유가 있을가요?
로고가 뜨는 것 vs 빈화면이 뜨는것
이렇게 두 가지 중에 하나를 선택한 것 같은데 그 이유가 궁금합니다.

어차피 떠야한다면 로고가 있는 편이 낫지 않을까 싶어서요!

2023-10-05 01:39 UTC, krrong commented
빅스가 말한 것처럼 스플래시에 로고를 띄우는 것도 고려했었습니다. 로고가 보이지 않는 것을 선택한 이유는 다음과 같아요.  
- 커스텀 스플래시 화면을 첨부한 영상처럼 로그인 뷰(혹은 설정 뷰)와 유사하게 만들었다.
- 이로 인해 [기본 스플래시] -> [커스텀 스플래시] -> [게임 시작 화면] 으로 가는 과정에서 로고를 보이지 않도록 하는 것이 가장 자연스럽다고 생각했다.

[기본 스플래시] [커스텀 스플래시] 화면을 최대한 일치시키고 두 번의 스플래시가 뜨도록 하는 것이 더 나을까요?

2023-10-05 01:50 UTC, briandr97 commented
저는 개인적으로 두번째 스플래시와 로그인 뷰가 비슷하게 생겨야할 이유도, 첫 번째 스플래시와 두 번째 스플래시가 같아야할 이유도 없다고 생각하긴 합니다.

배달의 민족같은 앱은 어떻게 한건진 모르지만 스플래시가 깔끔하게 한번만 나오는 반면 쿠팡 같은 경우에도 전혀 다른 스플래시가 두번 나오기 때문이죠.

그래서 저는 달라도 자연스럽다고 느낍니다.
이 부분에 대해 어떻게 생각하시는지 궁금합니다!

2023-10-05 01:51 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
> +        setTheme(R.style.Theme_Naaga)
뽀또가 이야기한 부분은 `setTheme(R.style.Theme_Naaga)` 이 부분인가요?  
뽀또 말대로 해당 코드가 없어도 잘 동작하네요! 반영했습니다!
다만 `installSplashScreen()` 이 코드는 필요해요! 🦖

2023-10-05 02:00 UTC, krrong commented
> 두번째 스플래시와 로그인 뷰가 비슷하게 생겨야할 이유도

이 부분에 대해서는 공감합니다. 그냥 만들다보니 그렇게 됐어요ㅋㅋ

> 첫 번째 스플래시와 두 번째 스플래시가 같아야할 이유도 없다

사실 저도 스플래시에 대해서 생각하고 알아보기 전에는 스플래시 화면이 두 개 뜨고 있는지도 모르고 있을 정도로 크게 신경쓰지 않았는데요. 이 부분을 한참 보다보니 확실히 하나로 통일되는(사실 2개지만 하나로 보이게끔 해서 빅스가 말하는 배달의 민족 앱처럼 만드는 것) 스플래시 화면이 자연스럽다고 느끼게 된 것 같아요.  
쿠팡 혹은 투썸플레이스 같은 앱에서도 2개의 스플래시가 존재하기 때문에 다르게 존재해도 무방하다고 생각합니다.

2023-10-05 02:17 UTC, briandr97 commented
저도 궁극적으로는 배달의 민족처럼 하나만 나오는 게 좋다고 생각합니다. (어떻게 한지 몰라서 적용을 못하지만..)
그래서 일단 그렇게 되지 못한다면 빈 화면 보다는 로고가 있는 편이 조금 더 깔끔하다고 생각이 듭니다.
개인적으로 빈 화면에서는 미완성된건가? 하는 느낌을 받기 때문입니다.
크롱이 괜찮으시다면 로고가 있는 편이 아직은 낫다고 생각합니다..!

2023-10-05 05:33 UTC, krrong commented
빅스, 뽀또의 의견을 반영하여 수정했어요! 수정한 스플래시 화면은 아래와 같습니다.  
혹시라도 추가의견이 있다면 언제든 이야기해주세요!🙃  
[스플래시.webm](https://github.com/woowacourse-teams/2023-naaga/assets/84285337/8be60511-3206-4e4d-8e41-b59a6764a066)

2023-10-05 05:46 UTC, briandr97 approved these changes
확인했습니다! 고생하셨습니다!

막상 적용된 것을 보니 디폴트 스플래시와 우리 자체 스플래시가 비슷하게 생겼는데 배치가 살짝 달라 흔들리는 느낌이 조금 드네요 ㅋㅋ

이 부분에 대해서는 추후 논의해보도록 하죠 우선 머지하겠습니다!

2023-10-05 05:52 UTC, hyunji1203 commented
같은 로고가 붙은 스플래시 화면이 두번 뜨는 것도 통일성있고 좋네요!
스플래시는 이정도면 충분한 것 같아요! 그럼 이만 approve 하겠습니다!
고생 많았어요~!!!

2023-10-05 05:53 UTC, hyunji1203 approved these changes
같은 로고가 붙은 스플래시 화면이 두번 뜨는 것도 통일성있고 좋네요!
스플래시는 이정도면 충분한 것 같아요! 그럼 이만 approve 하겠습니다!
고생 많았어요~!!!

2023-10-05 05:53 UTC, merged