feat: 쪽지 기록 기능 뼈대코드 설계 및 구현
woowacourse-teams/2023-naaga pull request #441
Opened 2023-10-10 07:10 UTC by zillionme

## 📌 관련 이슈
- closed: #437  

## 🛠️ 작업 내용
- [x] 쪽지 기록 기능 뼈대코드 설계
- [x] 쪽지 기록 관련 엔티티 구현
- [x] 쪽지 기록 관련 컨트롤러 구현
- [x] 쪽지 기록 관련 레포지토리 구현

## ⏳ 작업 시간
추정 시간:   1시간
실제 시간:   1시간

2023-10-11 00:49 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letterlog/domain/LetterLog.java
> +
P1:

해당 부분에 JPA 엔티티 어노테이션이 존재하지 않습니다.!!
이것 때문에 테스트 터지고 있으니 최우선으로 수정해주세용

2023-10-11 00:49 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    public LocalDateTime getCreatedTime() {
꼼꼼한 채채 좋은데요?

2023-10-11 00:57 UTC, dooboocookie requested changes
일단 테스트가 깨지는 부분이 있어서 고쳐주시면 될 것 같고.
제 생각엔 ERD와 설계의도를 PR에 좀 남겨주시면 좋을것 같아요!!

2023-10-11 04:24 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    public LocalDateTime getCreatedTime() {
앗 인정!
저도 컨밴션을 지키겠습니다 ㅎㅎ

2023-10-11 05:33 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    public LocalDateTime getCreatedTime() {
급히 코드를 작성하느라 컨벤션을 못지킨 부분이 많네요
수정했습니다

2023-10-11 05:33 UTC, kokodak requested changes
저도 루카와 마찬가지로, LetterLog 가 나오게 된 계기와 의도를 이 PR 을 통해 파악할 수가 없어서 리뷰가 좀 어려운 것 같아요.

뼈대코드라 코드 복잡도가 높진 않지만, 이 PR 을 통해 무엇을 리뷰받고 싶은지 드러내면 좋을 것 같습니당

RC 요청 드리고, 다시 설계 의도를 적어주시면 감사하겠습니다!

2023-10-11 05:33 UTC, kokodak commented on backend/src/test/java/com/now/naaga/common/builder/LetterLogBuilder.java
> +    }
P4:

Builder 를 만들면서 중요하게 생각했던 점은, 옵션을 주지 않아도 default 값이 존재해야한다는 점이었는데요!

그런 입장에서 저는 개인적으로 초기값의 Enum 을 주는 것이 좋지 않을까? 하는 생각이지만..

도메인 성격상 default 값이 존재하지 않는 것 같아서, 이것은 뼈대코드 설계하신 분의 선택을 따르겠습니다.

2023-10-11 05:34 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/domain/Letter.java
> +    public LocalDateTime getCreatedTime() {
근데 혹시 이 리뷰를 발견한 누군가, protected를 사용하는 이유를 명확히 아시나요

2023-10-11 05:36 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letterlog/domain/LetterLog.java
> +
수정했습니다

2023-10-11 05:36 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letterlog/domain/LetterLog.java
> +
수정했습니다

2023-10-11 05:37 UTC, zillionme commented on backend/src/test/java/com/now/naaga/common/builder/LetterLogBuilder.java
> +    }
이부분에 대해서는 gameResult의 빌더를 참고했는데요, 게임결과 도메인도 결과 타입이라는 enum을 가지고 있지만, 따로 초기화 해주지는 않더라구요. 그래서 테스트할 때 유의해서 사용해야할 것 같습니다

2023-10-11 05:37 UTC, zillionme commented on backend/src/test/java/com/now/naaga/common/builder/LetterLogBuilder.java
> +}
수정했습니다

2023-10-11 05:46 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letterlog/domain/LetterLogType.java
> +    WRITE,
루카의 말은 POST /letters 요청을 할 때
0. Letter객체 생성후 save
1. playerId로 진행 중인 Game을 조회
2. 쓰기 관련 letterLog(Game,Letter) 생성 및 저장
이 플로우를 말하는 것 같은데요.
이 경우에도 enum타입이 존재해야할 것 같습니다.

> 일단 제생각엔 작성자가 누구인지에 대한 기록은 Letter라는 엔티티, 테이블, 객체에 있는게 조금 더 적합한 것 같아요.

어차피 POST로 쪽지 등록시, Auth인터셉터를 통해 playerId가 전달되기 때문에, letter객체의 player을 사용할 필요는 없어 보입니다

물론, 로그 테이블을 읽기 로그와 쓰기 로그에 대한 테이블로 각각 나누는 것이 좋아 보인다는 의견에 대해서는
어차피 API가 GET /letterlogs?gameId={gamId}&status=read로 들어와야 할 것 같기 때문에, 
enum 방식을 선택한 것인데요.
API와 테이블은 연관관계가 없어도 되므로 루카의 의견에 대해 다른 크루들의 의견도 궁금합니다.

저는 루카의 의견에 중간인 것 같아요. 이것도 저것도 확 와닿지 않는 느낌.
테이블을 나누면 조회할 때, 컬럼이 하나 줄기 때문에, 성능이 빨라지는? 장점은 있을 것 같습니다.

2023-10-11 05:47 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letterlog/domain/LetterLog.java
> +
제가 드디어 미쳤군요 수정했습니다

2023-10-12 15:10 UTC, dooboocookie approved these changes
이레 복잡한 엔티티 설계 고민하시느라 고생많으셨어요.
이미 해당 엔티티 설계에 대해서는 팀적으로 충분히 공유가 되었다는 생각이 들어서 제가 드릴 추가적인 리뷰는 없을 것 같습니다.


이제는 어프루브하고 비즈니스 로직 짜면서 더 고민해보시죠.

 2가지 약간 언급하고 싶은 부분은
 1. 1:1이 아니라 N:1 관계입니다
 
 
![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/10db585e-e108-4b21-a61c-107a9952e5bd)
위와 같이 `플레이어` -- <쓰기> -- `쪽지`의 관계가 1:1라고 하셨는데,
이레가 코드에서
<img width="265" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/79090478/fed6c36a-048c-4218-9fb7-96bead1d59fa">
@ManyToOne이라고 하신 것처럼 이것은 N:1관계입니다.
다른 팀원들에게도 제 노하우를 조금 설명드려보면 저는 한 엔티티가 한 엔티티를 어떻게 바라보냐에 따라 X:를 결정하는데요.
이경우에는
- 1개의 플레이어가 여러개의 쪽지를 쓸 수 있으므로 쪽지쪽은 N
- 1개의 쪽지는 1개의 플레이어에게 쓰여질 수 있으므로 플레이어쪽은 1
이런식으로 관계를 정의합니다.

2. Letter와 LetterLog 패키지 분리
이 패키지 분리는 생명주기가 다르기 때문에 지정하신 것인가요?
제가 생각했을땐 LetterLog라는 이름에서도 보여지듯 이는 약간 중간테이블 혹은 로그성 도메인이라는 생각이 들어서 크게 독립적인 도메인 제약조건을 갖거나 하지는 않을 것 같아요.
그래서 일단 분리하신 이레의 의견을 존중하지만, 레터로그를 레터로 편입시키는 것도 좋아보입니다!!
이것은 크게 변경 요구사항은 아니라 이쪽에 내용 달겠습니다!

2023-10-12 15:48 UTC, chaewon121 approved these changes
이레~! 컨벤션 모두 수정해 주셨군요 고생 많으셨어요~!
일단 루카의 의견에 이어서 제의견은 letter 패키지안에 도메인 3개다 넣어놓고 api 구현하면서 패키지 분리를 생각해보는것은 어떨가 싶어요. 일단 기능을 직접 짜보지 않으면 머리로 생각하는건 한계가 있다고 생각합니다.
결론은 3개 모두 한패키지에 넣자입니다! 저도 아직 기능을 구현하지 않아서 의견내기가 어렵네요..ㅠㅠ나중에 분리해도 괜찮다고 생각합니다!

2023-10-13 02:26 UTC, kokodak approved these changes
PR 코멘트 구체적으로 수정해주셔서 감사합니다 이레이🥹 덕분에 이해가 잘 됐어요.

기존의 테이블에서 분리를 한 이유가 타당하다고 생각합니다. 많은 고민을 하셨다는 흔적도 보이구요!!

뼈대코드인만큼, 테이블 분리에 대한 근거만 명확하다면 큰 문제가 없다고 느껴져서 Approve 하도록 하겠습니다.

2023-10-13 02:38 UTC, merged