Feat/#459
woowacourse-teams/2023-naaga pull request #460
Opened 2023-10-13 14:13 UTC by chaewon121

## 📌 관련 이슈
PR과 연관된 이슈의 번호를 작성해주세요.
PR 머지 시 close 되어야 하는 이슈의 경우 이슈 번호 앞에 `closed` 키워드를 붙여주세요.  
ex) `closed #2`

## 🛠️ 작업 내용
PR에서 작업한 주요 내용을 적어주세요.
- [ ] 작업1
- [ ] 작업2

## 🎯 리뷰 포인트
리뷰시 중점적으로 봐주었으면 좋을 부분을 적어주세요.  
없다면 적지 않아도 됩니다.  

- 리뷰 포인트

## ⏳ 작업 시간
추정 시간:   
실제 시간:   
이유: 차이가 많이 난다면 이유도 같이 적어주세요 :)

2023-10-14 08:59 UTC, dooboocookie requested changes
안녕하세요. 채채.

일단 코드 너무 잘 구현해주셔서 감사합니다~

리뷰에도 적었지만 이번 RC의 전체적인 의견을 말씀드릴게요.

### LetterService가 너무 비대하다.
- 현재 해당 서비스는 LetterLog와 Game의 서비스들과 협력하고 있는데요.
- 그 서비스들에게 갈 일들이 많이 Letter 서비스에서 일어나고 있는 것 같아요.

그것 외에는 따로 강하게 주장할만한 내용은 없을 것 같습니다!!

2023-10-14 08:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
P4:
 
지금 해당 프라이빗 메서드에서 하고 있는 행위가 
GameService에서 진행중인 게임'들'을 조회해오는 것 인데요.

채채가 위 프라이빗 메서드에서 구현한대로 게임 상태 조회에 대한 2가지 특성이 있을 것 같은데요.
1. 진행 중 게임은 2개 이상일 수 없다.
2. 특정 상황에서는 진행중 게임이 없으면 예외이다.

그래서 제 생각에는 위 2가지 상태에 대해서 예외를 발생 시키는 public 메서드를 GameService에 두는 것도 괜찮다라는 생각이 드는데요.
혹시, 이부분에 대해서는 어떻게 생각하시나요?

2023-10-14 08:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
P2:

이 퍼블릭 메서드에 리드온리 옵션을 활성화하고 특별히 다른 메서드로 뺀 이유가 있으신가요?
제가 알기론 이런식으로 구현하여도 한 Service 객체 안에 존재해서 트랜잭션 분리가 안되는 것으로 알고 있는데요.

제 생각에는 이 53~54의 1~2줄 기능은 본 메서드의 있어도 된다는 생각인데요.
혹시 어떻게 생각하시나요?

2023-10-14 08:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
P2: 

그리고 진행중 게임을 조회하는 것이
`LetterService`와 `LetterLogService` 중 LetterService의 역할일까요?
일단 제 생각은 그렇지 않습니다.

저희가 도메인 패키지를 분리하지 않았지만 물리적인 도메인을 `Letter`와 `LetterLog`으로 나눴으면
`읽기`라는 행위를 할 때
사실 `Letter`는 특정 쪽지의 `내용을 보여주고` `로그를 호출한다` 까지인 것 같은데요.
`LetterLog`에서 로그하라는 명령이 떨어졌으면 해당 플레이어의 진행 중 게임을 찾아서 그 게임으로 로깅을 해야한다고 생각합니다.

2023-10-14 08:59 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
> +}
P?:

이건 팀원들에게 좀 물어보고 싶은게 있는데요.
저희가 Command에서는 도메인 자체를 넘겨줄 수 있다고 정의하긴 했는데요.
이런식으로 다른 서비스에서 조회해서 영속화 되어있는 엔티티를 넘겨주는 것에 대해서 어떻게 생각하시나요?

서비스 -> 서비스로 호출하는 것에 대해서는 일단 영속성 컨텍스트가 살아 있어서 OSIV에 대해서 이야기하고 싶은 것은 아닙니다.

저 현재로서는 저 log라는 행위가 서비스안에서 호출된다는 명확한 사용처가 있지만 특정 서비스에 퍼블릭한 메서드를 선언한다는 것은 그 메서드가 여러 군데에서 사용될 수 있을 것 같은데요.
그렇다면 그때, 영속화(혹은 아이디가 존재하는) 엔티티가 넘어갈 것이라고 기대하기 보다는 id값을 넘겨주는 것이 좋지 않을까요??

2023-10-14 08:59 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +    void 쪽지_식별자로_쪽지를_조회시_잔행중_게임이_없으면_예외가_발생한다() {
예외 테스트 굳

2023-10-15 07:50 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
이 부분에 대해서는 제가 짰는데,
테이블을 구성하면서 Letter가 이론적으로는 Game에 종속적이라고 생각했기 때문입니다. 
- 쪽지를 읽을 때, "게임 중에 읽은 쪽지"에 대해서 기록을 남기는데,
- 그렇다면, 쪽지 자체도 게임 중에 읽혀야 로깅을 할 수 있지 않나? (즉, 쪽지를 조회하기 전에 진행중인 게임에 대해서만 쪽지를 읽는다)
-라는 생각이 들었습니다.
따라서, getGameInProgress()메서드의 위치도 쪽지 조회 메서드의 맨 위에 붙어야하는 것 아닌가 생각을 했습니다.

즉, 테이블 관계에서는 쪽지와 게임이 상관 없지만, 도메인 레벨에서는 쪽지와 게임이 연관관계를 갖게 되는 것입니다. (이 부분이 이상하다고 느껴지기도 하지만 동시에 테이블과 도메인이 꼭 같아야 하나 라는 생각입니다)

사실 이부분에 대해서는 루카의 말이 맞는 것 같기도 하고 헷갈리네요. 루선생 코선생 채선생 도와주세여

2023-10-15 08:11 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
동의합니다

2023-10-15 08:12 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
> +}
P4:
이론적으로는 다른 곳에서 ReadLetterLog서비스를 사용할 수 있기 때문에 매개변수로 넘겨주는 값을 신뢰할 수 없다고 생각합니다.
따라서 gameId로 넘겨 받는 것이 나은 선택이라는 생각이 드네요

2023-10-15 08:31 UTC, zillionme requested changes
코드를 작성하기 전에 서로 얘기를 말했던 터라,
루카가 언급한 두 가지 문제를 제외하고(저한테도 포함되는 사항) 딱히 리뷰할 점이 보이지 않았습니다.
두가지 문제에 대한 수정이 이뤄지면 바로approve 하도록 하겠습니다

2023-10-15 08:31 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
> +}
P4:
이론적으로는 다른 곳에서 ReadLetterLog서비스를 사용할 수 있기 때문에 매개변수로 넘겨주는 값을 신뢰할 수 없다고 생각합니다.
따라서 gameId로 넘겨 받는 것이 나은 선택이라는 생각이 드네요

2023-10-15 15:51 UTC, dooboocookie approved these changes

2023-10-15 15:57 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
> +}
전 id 를 사용하는 것을 더 선호하는 것 같아요.

말씀하신대로 영속화가 되어있는 도메인인지 아닌지를 파악하려고 하기 보다는, id 값을 넘겨서 필요할 때마다 사용하는게 더 낫겠다는 생각입니다.

또한, Command 는 presentation 계층에서도 사용하고 있는데요! 이럴때는 항상 불완전한 도메인이 넘어가야하기 때문에 NPE의 위험성이 있긴 한 것 같습니다.

2023-10-15 16:12 UTC, kokodak requested changes
안녕하세요 채채

저도 리뷰를 좀 남겨보았는데요!

대부분 이전 리뷰들과 겹쳐서, 한번 쭉 확인해주시고 반영해주시면 감사하겠습니다 ㅎㅎ

2023-10-15 16:12 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +                         final GameService gameService, final PlayerService playerService) {
P3:

마지막 친구도 개행으로 내려주시와요

2023-10-15 16:12 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
> LetterLog에서 로그하라는 명령이 떨어졌으면 해당 플레이어의 진행 중 게임을 찾아서 그 게임으로 로깅을 해야한다고 생각합니다.

위 의견에 동의합니다! 게임을 찾는 로직부터 그걸 가지고 지지고 볶는 로직은 LetterLogService 안에 들어가는 게 좋을 것 같아용

2023-10-15 17:00 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
인정합니다
LetterLogService로 책임 넘기도록 리팩터링 해볼게요!

2023-10-15 17:10 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
저 매서드를 따로 분리한 이유는 기본 아이디로 조회하는 로직은 다른곳에서도 많이 쓰인다 생각하고 매서드를 분리했습니다. 
다른 저희 코드들을 봤을때 id로 조회하는 로직은 따로 매서드로 분리되어 있더라구요.
아직은 루카말씀처럼 분리할 이유는 따로 없습니다. 추후에 빼는것도 좋을것같네요!

2023-10-15 17:11 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
> +}
저도 id를 사용하는 것이 더 좋다고 생각합니다. 위에 로직을 수정하면서 필요한 letter만 도메인을 넘겨주고 필요하지 않은것은 id로 넘겨주는것으로 수정하였습니다

2023-10-15 17:12 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
> +}
로직을 수정하면서 필요한 letter만 도메인을 넘겨주고 다른 부분에 대해선 id를 넘겨주도록 수정하였습니다!

2023-10-15 17:13 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +                         final GameService gameService, final PlayerService playerService) {
저친구가 왜 저기에.. 수정하겠습니다!

2023-10-15 17:28 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
진행 중 게임은 2개 이상일 수 없다. -> 이것에 대한 예외가 필요할까요?
일단 letterlog에서 잡을 예외는 아니라고 생각합니다. 이미 진행중인게임이 2개이상이 있다는건 게임로직부터 잘못된것이라고 생각합니다.
이것에 대한 예외는 게임로직에서 잡아야한다고 생각하는데..
그래서 gameService.findGamesByStatus 이 매서드에서 저 예외를 추가할까 생각해보았습니다.
그런데 단순히 게임을 모두 조회한다는 로직에 저 예외가 추가되는것이 맞을까요?
저는 잘 모르겠네요.. 다른 팀원들의 생각은 어떤가요?

2023-10-15 19:04 UTC, chaewon121 reviewed
가장 크게 바뀐로직은:
getGameInProgress()를 ReadLetterLogService로 넘겨줬습니다! 모두 좋은 의견 감사합니다~!
그 과정에서 dto의 인자를 최대한 id로 주도록 수정하였는데 letter을 도메인을 넘겨줘야해서 도메인으로 하였습니다.
또한 서비스 테스트도 추가하였습니다~!

2023-10-16 01:47 UTC, kokodak approved these changes
안녕하세요 채채

새벽에 작업하신다고 고생 많으셨어요

제가 드렸던 피드백은 모두 잘 반영된 것 같아서 이만 Approve 하도록 하겠습니다.

추가적인 피드백들로 컨벤션 관련된 것들이 있는데, 이 부분들은 한번 확인해주시고 merge 해주시면 감사하겠습니다 ~

2023-10-16 01:47 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/ReadLetterLogService.java
> +    private final GameService gameService;
P3:

개행이 필요해요 !!

2023-10-16 01:47 UTC, kokodak commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +        assertThat(letterException.exceptionType()).isEqualTo(NO_EXIST);
자세한 검증 굿 👍

2023-10-16 01:47 UTC, kokodak commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +class LetterServiceTest {
서비스 테스트 보강해주셔서 감사합니다

2023-10-16 01:47 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    private final PlayerService playerService;
P3:

필드 개행!

2023-10-16 04:14 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/ReadLetterLogService.java
> +    private final GameService gameService;
수정완료!

2023-10-16 04:14 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    private final PlayerService playerService;
수정완료!

2023-10-16 04:20 UTC, merged