feat:플레이어의 주변 쪽지 조회api 구현
woowacourse-teams/2023-naaga pull request #461
Opened 2023-10-13 15:10 UTC by chaewon121

## 📌 관련 이슈
- closed: #455 

## 🛠️ 작업 내용
- [x] 플레이어의 주변 쪽지 조회api 구현 

## 🎯 리뷰 포인트
고민사항:
RequestParam을 double로 형변환 할 시 예외를 잡아주었습니다. 무조건 double값이 들어와야 하기 때문인데요..!
이 로직을 중점으로 봐주시면 감사하겠습니다!

인수테스트만 작성된 상태입니다. api 구현이 모두 끝나고 리뷰 받으면서 단위테스트를 추가하겠습니다..!
제가 마음이 급해서..양해 부탁합니다!

## ⏳ 작업 시간
추정 시간:   2h분
실제 시간:   3h분

2023-10-14 11:09 UTC, dooboocookie requested changes
채채 이렇게 금방 API 2개를 작성해주시다니 고생많으셨어요.

제 생각엔 일단 해당 pr을 먼저 건들기 보단 첫번째 pr을 조금 더 나은 상태로 머지 시키고 
dev_backend를 이 브랜치에 pull 당겨서 작업을 이어나가는것이 어떨까 싶네요.

2023-10-14 11:09 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
P1:

0.1km == 100m 자리수 확인 부탁드립니다!!

2023-10-14 11:09 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
이런 부분을 서비스 테스트에서 걸를 수 있었으면 좋겠네용!!

2023-10-14 11:09 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
P3:

그리고 해당 숫자는 로직에 중요한 숫자이므로 상수로 빼주시는건 어떨까요?

P5:

N미터 반경의 있는 쪽지들을 조회한다가 도메인 로직의 중요한 부분같은데, 짧아도 도메인 서비스 안에 넣는 것도 가능할 것 같아요.

2023-10-14 11:09 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
> +
P2:

필요없는 개행은 제거해주세요~!

2023-10-14 11:09 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/presentation/dto/FindNearByLetterCommand.java
> +    }
P2:

파라미터가 2개인 정적 팩터리 메서드는 of를 사용하는 것이 저희 컨벤션으로 자리 잡았다고 생각합니다!!

2023-10-14 11:09 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +
P2:

테스트를 보완해주시면 좋을 것 같아요!!

시간 상 문제로 Test를 전체 플로우를 훑는 E2E 테스트를 작성하신 것은 이해합니다.

하지만 위에서 언급했듯이 비즈니스의 심각한 영향을 끼치는 오류가 있는데 해당 예외 케이스에 대한 테스트가 없어서 그것을 잡아내지 못했네요.

E2E 테스트만 작성한다면 그것이 반환하는 값이 정말 비즈니스 적으로 옳은지 검사할 필요가 있을 것 같아요!!

일단 테스트를 추가한다고 하셨으니까 서비스 테스트를 조금 보강해주시면 될 것 같아요.

2023-10-15 03:40 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
> +        }
아double로 받으면 되네요 ㅋㅋㅋ나뭐지...바로수정하겠습니다!

2023-10-15 03:40 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/repository/LetterRepository.java
> +            ") * 6371.0 <= :distance")
맞아요 공간인덱스 적용하게되면 이부분도 적용하게될것같습니다

2023-10-15 03:41 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/dto/FindNearByLetterCommand.java
> +    }
앗 of가 맞습니다! 수정하겠습니다!

2023-10-15 08:36 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/presentation/dto/NearByLetterResponse.java
> +public record NearByLetterResponse(Long id,
P4:
사소한 네이밍 문제인데 NearbyLetterResponse라고 쓰면 더 좋을 것 같습니다

2023-10-15 08:50 UTC, zillionme requested changes
루카가 이미 리뷰를 잘 남겨주어서 더 리뷰할 것이 보이지 않네요.
루카 리뷰 반영하는 대로 approve 하도록 하겠습니다

2023-10-15 08:50 UTC, zillionme commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +                .param("longitude", "127.036953")
value값을 문자열이 아닌 숫자로 바꾸면 좋을 것 같아요

2023-10-15 08:50 UTC, zillionme commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +                .param("longitude", "127.036953")
문자열 값이 무슨 값에 해당하는지 모르겠습니다. 역삼역_좌표의 위 경도 값인가요?

2023-10-15 15:52 UTC, dooboocookie approved these changes

2023-10-15 16:37 UTC, kokodak requested changes
안녕하세요 채채

API 구현 고생하셨습니다!!

몇가지 리뷰 남겼는데, 한번 확인해주세요-!

(+ 서비스 테스트는 상당히 중요한 부분이니.. 시간이 들더라도 구현해주셨음 합니다 🥹 채채는 똑똑하니까 20분도 안걸릴거에요)

2023-10-15 16:37 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
> +                                                                       @RequestParam(name = "longitude") final String longitude) {
P4:

쿼리스트링 이름과 변수명이 같으면 name 필드를 생략할 수 있는 것으로 알고 있어요!

빼주셔도 좋고 두셔도 좋고 채채가 판단해주세요 ㅎㅎ

2023-10-15 16:37 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
> +                .collect(Collectors.toList());
P3:

컨트롤러 메서드에 변환 과정을 담기보다는, `NearByLetterResponse` DTO 내부에 변환 로직으로 정적 팩터리 메서드를 정의하는 게 깔끔할 것 같아요!

선례로 `GameResponse.convertToGameResponses()` 이런 메서드가 있습니다

2023-10-15 16:37 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/presentation/dto/NearByLetterResponse.java
> +public record NearByLetterResponse(Long id,
are you 영잘알?

2023-10-15 16:37 UTC, kokodak commented on backend/src/main/java/com/now/naaga/letter/repository/LetterRepository.java
> +                                                 @Param(value = "distance") final double distance);
리마인드 차원에서.. distance 는 km 단위입니당

2023-10-15 16:37 UTC, kokodak commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +                .param("longitude", "127.102899")
P2:

어떤 위치의 좌표값인지에 대해 매직넘버를 사용하기보다는, Fixture 로 나타내주시는 게 좋아보여요!

해당 값만 보고서는 어떤 위치에서의 주변 쪽지 조회 테스트인지 감 잡을 수가 없어서.. 유효한 테스트인지 리뷰하기가 어렵네용

2023-10-15 17:38 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/dto/NearByLetterResponse.java
> +public record NearByLetterResponse(Long id,
이레 영잘알?

2023-10-15 17:39 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +                .param("longitude", "127.036953")
가독성에 문제가 있군요 리팩터링 할게용

2023-10-15 17:40 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/repository/LetterRepository.java
> +                                                 @Param(value = "distance") final double distance);
수정완..ㅠㅠ

2023-10-15 17:40 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +                .param("longitude", "127.102899")
인정합니다 리팩터링 하겠습니다!

2023-10-15 17:44 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
> +                                                                       @RequestParam(name = "longitude") final String longitude) {
바로 적용완료!

2023-10-15 17:48 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
> +                .collect(Collectors.toList());
더욱 깔끔한 코드가 되었네요 감사합니다

2023-10-15 17:51 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +                .param("longitude", "127.102899")
(+ 서비스 테스트는 상당히 중요한 부분이니.. 시간이 들더라도 구현해주셨음 합니다 🥹 채채는 똑똑하니까 20분도 안걸릴거에요) -> 칭찬은 고래도 춤추게한다.. 바로반영하겠습니다

2023-10-15 18:23 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
0.1km == 100m 자리수 확인 부탁드립니다!! -> 반영완료
이런 부분을 서비스 테스트에서 걸를 수 있었으면 좋겠네용!! ->반영완료
그리고 해당 숫자는 로직에 중요한 숫자이므로 상수로 빼주시는건 어떨까요? -> 반영완료
도메인 서비스에대한 지식이 부족하여 학습 후 고민해보도록 하겠습니다~!

2023-10-15 18:23 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +
테스트보강 완료!

2023-10-15 18:28 UTC, chaewon121 reviewed
로직상으로 크게 변형된것이 없어 따로 수정부분에 대해서 남기지 않겠습니다.
여러분들 댓글에 반영사항에 대해서 남겨놓았습니다~!

2023-10-15 19:03 UTC, kokodak approved these changes
채채 새벽에도 고생 많으셨어요 🥹

제 피드백은 모두 반영된 것 같아 Approve 하도록 하겠습니다! 고생하셨어요!!!!!!

2023-10-15 19:03 UTC, kokodak commented on backend/src/test/java/com/now/naaga/common/fixture/PositionFixture.java
> +            잠실역_교보문고_좌표.getLongitude());
110 미터 값 확실하네요 👍

2023-10-15 19:03 UTC, kokodak commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +class LetterServiceTest {
서비스 테스트!! 고생하셨습니다 채채  👏👏👏👏

2023-10-16 00:55 UTC, zillionme approved these changes
채채 늦은 밤까지 고생하셨습니다. 
쪽지 관련 3개의 API를 맡아서 하고 있는데, 나머지 두개는 지금 리뷰가 많이 달렸더라구요?
같이 리팩터링 하면 더 좋을 것 같습니다. 혹의 논의만 같이하고 이어받아서 리팩터링해도 좋구요(남은 두개의 api 빠르게 리팩터링하기)

변경사항들 모두 적용된 것 같아 approve 하도록 하겠습니다!!!

채채짱😇

2023-10-16 04:16 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/common/fixture/PositionFixture.java
> +            잠실역_교보문고_좌표.getLongitude());
지피티 선생님과 함께했답니다

2023-10-16 04:17 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +class LetterServiceTest {
칭찬은 채채도 테스트를 짜게한다..👏

2023-10-16 05:03 UTC, merged