feat: 좋아요/싫어요 등록 API 구현
woowacourse-teams/2023-naaga pull request #462
Opened 2023-10-13 19:48 UTC by kokodak

## 📌 관련 이슈
- close: #442 

## 🛠️ 작업 내용
- [x] API 명세 구체화
- [x] 등록 API 구현
- [x] 테스트 코드 작성

## 🎯 리뷰 포인트

# 언제 사용되는가?

기존에 눌려있던 좋아요/싫어요가 있을 때, 기존의 것 말고 다른 것을 눌렀을 때 작동되어야합니다.
또는, 기존에 눌려있던 좋아요/싫어요가 없다면 새로운 엔티티를 생성합니다.

# 어떻게 작동되는가?

- 이 API 는 다음 두가지 경우에서 다음과 같은 방식으로 작동합니다.
    - 기존에 눌려있던 좋아요/싫어요 가
        1. 있을 때, 기존의 것 말고 다른 것을 눌렀을 때
            1. 기존에 있던 엔티티의 PlaceLikeType 값을 수정합니다.
        2. 없을 때는 아무거나 눌렀을 때
            1. 새로운 엔티티를 생성한다.

- 또한 어떤 Type 을 등록하냐에 따라 역정규화한 테이블의 집계 컬럼 값이 수정되어야합니다.
    - 만약 좋아요를 등록했다면, 좋아요 집계 컬럼 값을 +1 합니다.
    - 만약 싫어요를 등록했다면,
        - 기존의 좋아요 에서 싫어요로 바꾼 것이라면 좋아요 집계 컬럼 값을 -1 합니다.
        - 아무것도 없는 상태에서 새롭게 싫어요를 등록한 것이라면 좋아요 집계 컬럼 값은 변하지 않습니다.

# 생각해볼만한 점

- 동시성 이슈가 발생할 수 있는가?
    - 좋아요 집계 컬럼 값이 수정될 때 발생할 수 있습니다.
    - 대처할 것인가?
        - 당장은 하지 않을 것 같습니다. 동시성 이슈가 터질 수 있다는 점만 인지해놓으면 될 것 같습니다!

---

생각보다 로직의 복잡도가 살짝 있어서, 최대한 코드를 깔끔하게 짜려고 노력했는데.. 마음에 드실지 모르겠습니다.

리뷰 잘 부탁드립니다~!!~!~!~!~!~!!

## ⏳ 작업 시간
추정 시간:   4시간
실제 시간:   4시간

2023-10-14 16:28 UTC, dooboocookie requested changes
몇가지 의견 궁금한 점이 있어서 RC 남깁니다.

이게 과연 하나의 서비스 메서드안에 있어도 될 일인가 싶을 정도로 총 경우의 수 5개 정도로 나뉘는 작업을 하고 있는데요.

저도 코드리뷰하면서 3시간 정도 코드 직접 짜보면서 고민을 해봤어요.
도메인 서비스로 넣는 것, 분기 절차를 바꾸는 것 등등 여러가지고 변경을 시도해봤는데요.

도메인 서비스로 넣는 것을 아직 그럴만한 구석을 못봤구요.
분기 절차를 바꾸는 것은 나름 유의미했던 것 같습니다.

예를 들어서
현재는 
![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/dfa836d9-279b-4436-87e4-fe1ecfa99ec4)
이렇게 이전에 등록된게 있는지 없는지 부터 해결하고 가는데요.

저는
![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/1e14b1d6-3b8f-4c76-a6c6-85334caa2aa0)

아예 통계 +1을 하는 행위를 입력값이 좋아요인지 싫어요인지 따로 보고 분기를 뽑아봤는데요.
코드 가독성의 유의미한 변화가 있었던 것 같아서, 살짝쿵 의견 어필해봅니다.

그리고 이건 진짜 코드만을 위한 성능 저하인데,
UPDATE가 아니라 DELETE, INSERT인 과정도 좋을 것 같다는 생각이 들었어요.
이러면 확실히 분기를 줄일 수 있을 거에요.

---
그리고 이 좋아요는 유저가 따닥 누를 수 있는 확률이 높은 동작이라.
이를 어떻게 해결할지 안드로이드랑 이야기해봐야될 것 같긴해요.

그럴 때는 `새로운 좋아요를 추가하는 것`과 
만약 이전에 `눌려있었다면 이전걸 삭제하거나 예외를 터트리는 과정`을` 비동기`로 처리해도 좋을 것 같아요.
메인 요청 흐름의 트랜잭션을 최대한 짧게 가져가는것에 대한 의견입니다.

2023-10-14 16:28 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/like/presentation/PlaceLikeControllerTest.java
> +    void 좋아요_등록이_성공하면_201_응답을_반환한다() {
P2:

예외 응답에 대한 테스트도 있으면 좋을 것 같아요

2023-10-14 16:28 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/like/application/PlaceLikeServiceTest.java
> +    void 기존의_좋아요_타입과_반대되는_타입을_등록하면_기존의_엔티티에서_좋아요_타입만_수정된다() {
굿 테스트 케이스별로 꼼꼼하게 해주셨네요

2023-10-15 06:33 UTC, kokodak commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +                                            () -> createPlaceLike(playerId, placeId, placeLikeType));
> 1. 제 기준에선 조금 뎁스가 깊어 보입니다.

그럴 수 있겠다고 생각합니다. 전 개인적으로 람다식이 더 직관적이라 생각해서 사용했는데, if 문 분기처리로 명확하게 처리해주는 것 또한 좋다고 생각하기 때문에 이 부분은 람다식을 제거하는 방향으로 리팩터링 하겠습니다.

> 2. cancelLike 메서드와 스타일 불일치

이거는 잘 모르겠네요.. 개인의 개성을 죽일 수도 있지 않을까? 하는 생각입니다.

2023-10-15 06:35 UTC, kokodak commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +        }
저도 이 부분이 중복이 돼서 거슬렸는데 딱 짚어주셨군요 ㅎㅎ.. 좋다고 생각합니다.

2023-10-15 06:37 UTC, kokodak commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +        }
else if 만 지양하면 되는 줄 알았는데 else 도 포함이었군요.

early return 이나 말씀하신대로 코드를 리팩터링해서 제거해보겠습니다

2023-10-15 06:37 UTC, kokodak commented on backend/src/main/java/com/now/naaga/like/domain/PlaceLikeType.java
> +    }
ㅎㅎ 딱걸렸네

2023-10-15 06:39 UTC, kokodak commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +                                 final PlaceLikeType placeLikeType) {
좋습니다. 변수명으로 더 직관적이고 명시적인 의미를 담자는 얘기시죠?

placeLike 라는 업데이트 할 대상은 `target` 으로 변경하였고,
placeLikeType 이라는 실제 업데이트 될 값은 `toBeChanged` 라는 이름을 붙여주었습니다!

2023-10-15 07:22 UTC, kokodak commented
루카 좋은 피드백 감사합니다. 모두 반영하였고 확인해주시면 감사하겠습니다.

---

> 아예 통계 +1을 하는 행위를 입력값이 좋아요인지 싫어요인지 따로 보고 분기를 뽑아봤는데요.
코드 가독성의 유의미한 변화가 있었던 것 같아서, 살짝쿵 의견 어필해봅니다.

확실히 중복 분기문이 제거도 되고, 가독성 측면에서도 좋아진 것 같아서 적용해봤습니다. 굿

> 그리고 이건 진짜 코드만을 위한 성능 저하인데,
UPDATE가 아니라 DELETE, INSERT인 과정도 좋을 것 같다는 생각이 들었어요.
이러면 확실히 분기를 줄일 수 있을 거에요.

코드의 로직이 쉬워진다는 데에 동의합니다. 다만 `DELETE, INSERT` 인가 `UPDATE` 인가에 대해서는 이미 많은 얘기를 나눠서 하나로 확정시켰다고 생각하고, `쿼리를 2배로 늘려서까지 코드 가독성을 올려야 할 정도로 로직이 복잡한가?` 에 대해서는 전 `그렇지 않다` 라는 입장이기 때문에 일단 이번 PR 에서는 그대로 두겠습니다.

> 그리고 이 좋아요는 유저가 따닥 누를 수 있는 확률이 높은 동작이라.
이를 어떻게 해결할지 안드로이드랑 이야기해봐야될 것 같긴해요.
>
> 그럴 때는 새로운 좋아요를 추가하는 것과
만약 이전에 눌려있었다면 이전걸 삭제하거나 예외를 터트리는 과정을 비동기로 처리해도 좋을 것 같아요.
메인 요청 흐름의 트랜잭션을 최대한 짧게 가져가는것에 대한 의견입니다.

확실히 동시성 이슈가 발생할 확률이 있는 시나리오겠네요.

따닥을 했을 때, 좋아요/싫어요 등록 요청이 동시에 2개 날라간다면, DB 에서 PlaceLike 값을 조회할 때 두 요청 모두 `기존의 PlaceLike 없음` 이라는 결과를 받을테니 두개의 PlaceLike 가 생겨나겠네요.

이는 playerId 와 placeId 컬럼을 쌍으로 묶어 유니크 처리해주면 `두개의 PlaceLike` 문제는 해결할 수 있겠으나..

이보다 더 근본적인 문제는, 좋아요 등록과 싫어요 등록 요청이 동시에 나갔을 때, 항상 사용자가 최종적으로 선택한 좋아요 타입이 DB에 반영된다는 점을 보장할 수 없을 것 같아요.

왜냐하면 동시에 발생한 `좋아요 등록 트랜잭션`과 `싫어요 등록 트랜잭션` 중, `어떤 것이 먼저 처리되는가?` 에 대해서는 아무도 모르니까요.

이는 말씀해주신 `비동기 처리를 통한 트랜잭션의 범위 최소화` 로는 해결할 수 없는 문제로 보여집니다. 예상컨데, 이는 사용자가 좋아요/싫어요 버튼을 누르고 게임 결과 화면 밖을 나갈 때, 클라이언트에서 좋아요/싫어요 등록 API 요청 콜을 1회 하는 것이 제일 쉽고 효과적인 방법이라고 생각됩니다.

---

추가적으로 루카에게 궁금한 점은, 어떤 부분에서 비동기 처리가 좋다고 생각하셨는지 구체적인 생각이 궁금합니다. 또한 트랜잭션 범위를 최소화하는 것이 이 동시성 시나리오에서 어떤 영향을 줄 수 있는지도 궁금합니다! 저에겐 굉장히 추상적으로 들려서 정확히 이해를 하지 못했습니다 🥲

2023-10-15 10:51 UTC, zillionme requested changes
리뷰 확인해주시면 바로 approve 해도 될 것 같습니다 👍🏻

2023-10-15 10:51 UTC, zillionme commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +        return placeLikeRepository.save(new PlaceLike(place, player, placeLikeType));
질문 -> 채채는 모를것 같아서 남기는) 

좋아요일 때, 장소 통계의 좋아요 수를 +1하는데,
이때 내부적으로, 기존의 장소통계가 없으면 예외를 발생시키더라구요
placeStatistics가 이 플로우에서 생성되지 않는데 어디서 생성되는 건가요?

=> place가 생성됨과 동시에 생성하도록 한다고 하는데, 도메인은 placestatistics가 place를 의존하고 있는데, place에서 placestatistics를 생성하면 양방향 의존이 생긴다고 해서 생각 더 해주신다고 하네요

2023-10-15 15:39 UTC, chaewon121 requested changes
와우 이해하는데 한참걸렸네요..어려운 파트를 맡으셨군요 고생많으셨습니다!
개인적으로 나중에 좋아요수를 바꾸는 로직과 트렌젝션을 분리해보는 리팩토링을 해보고 싶네요!
복잡함에도 불구하고 이해하기 너무 편했습니다!
일단 현재 새로운 좋아요가 생길때 좋아요수가 증가되는 로직이 보이지 않아서 request change 하겠습니다! 양방향이 어떻게 해결될지 저도 고민해보겠습니다. 일단 이부분만 해결된다면 바로 approve 하겠습니다!

2023-10-15 15:39 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +        return placeLikeRepository.save(new PlaceLike(place, player, placeLikeType));
위 이레 의견에 따르면 좋아요수가 증가된느 로직이 현재 빠진 이유는 양방향 의존성때문에 일단 추가하지 않았다는것으로 이해해도 될까요? placeStatisticsService.plusLike(); 를 하면 양방향 의존성이 생긴다..?어느부분에서 양방향이 생긴다는 것인지 자세하게 설명 부탁드려도 될까요?ㅠㅠ

2023-10-15 15:51 UTC, dooboocookie approved these changes
잘 적용해 주셨네요. 어프루브 하겠습니다

> 추가적으로 루카에게 궁금한 점은, 어떤 부분에서 비동기 처리가 좋다고 생각하셨는지 구체적인 생각이 궁금합니다. 또한 트랜잭션 범위를 최소화하는 것이 이 동시성 시나리오에서 어떤 영향을 줄 수 있는지도 궁금합니다! 저에겐 굉장히 추상적으로 들려서 정확히 이해를 하지 못했습니다 🥲

저도 추상적으로 생각한거라 자세한 방법에 대해서는 이야기를 못하겠지만 조금 러프하게 POST 요청을 받아드리는 것은 어떠냐는 의견이였습니다.

1. 무조건 INSERT 시킨다.
2. 통계를 올리는 작업을 비동기로 한다.
3. (어쩌면 2에 포함) `PLACELIKE가 1개만 존재할 수 있다.` `선행된 insert작업을 삭제하면서 count를 조작한다`는 작업을 비동기로 한다.

좋아요 같은 경우 티케팅같은 도메인 보다는 엄중한 도메인은 아니라고 생각이 들어요 따닥을 했다고 해도 유저한테는 그냥 됐다고 판단하게 둬도 될 것 같아요.

그래서 위와 같이 생각했었는데, 1번이 트랜잭션이 끝나야 2~3번을 다른 트랜잭션에서 처리할 수 있겠네요... 이건 조금 더 생각해볼게요.

2023-10-15 17:24 UTC, kokodak commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +        return placeLikeRepository.save(new PlaceLike(place, player, placeLikeType));
음.. 채채가 약간 잘못 이해하고 계신 부분들이 있어서 그것부터 바로 잡고 가겠습니다!

일단 현재 로직에서 `새로운 좋아요가 생길때 좋아요 수가 증가되는 로직` 은 존재합니다...!

```java
if (placeLikeType == PlaceLikeType.LIKE) {
    placeStatisticsService.plusLike(new PlusLikeCommand(placeId));
}
```

또한, `양방향 의존성이 생긴다` 라고 한 부분은 좋아요 수와 전혀 상관없는 부분이에요!

이레가 양방향이 걸린다라고 표현했던 지점은, 다음 두가지입니다.

1. PlaceStatistics 도메인이 Place 를 알고 있다.
2. Place 생성시 PlaceStatistics 가 함께 생성되어야하므로, PlaceService 에서 PlaceStatisticsService 를 의존시켜야한다.

이렇게 두가지를 보면, place 패키지와 placestatistics 패키지가 양방향 의존이 걸리게 됩니다. 그것을 말한거였어요!

2023-10-15 17:46 UTC, kokodak commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +    }
> 제 이해 겸, 다음에 봤을 때 한번에 읽을 수 있도록 코드 흐름을 정리합니다.

👍

> placeLikeOptional, placeLike의 네이밍에 "기존의"라는 뜻을 더해주면 더욱 코드가 이해하기 쉬워질 것 같아요
예를들면, existingPlaceLike로요,
updatePlaceLike에서도 기존의 placeLike와 다른 용어인 target을 사용해서 조금 헷갈릴 수 있다고 생각합니다

좋아요! 기존의 라는 뜻을 더해봤고, target 부분은 루카의 의견을 반영하고 바꾼 것이라서.. 이건 그대로 둬도 괜찮을까요?

> 기존의 타입이 싫어요이고 바꾸려는 타입이 좋아요라면
선행되어 좋아요가 +1되었기 때문에 기존의 싫어요는 단순히 무시되는 게 맞나요?

맞습니다!

> 좋아요 수와 별개로 관리되어야겠지만
싫어요 �수도 유의미하다고 생각되어서 저장할 수 있으면 좋을 것 같은데 이에 대해 어떻게 생각하시는 지 궁금합니다

저도 그렇게 생각해요. 싫어요 수도 가능하면 DB에서 따로 저장해두고 싶은데, 이에 대해서는 추가적인 이슈를 할당해서 진행하는게 좋아보여욥

2023-10-15 18:03 UTC, kokodak commented
> 사실 좋아요에 대한 플로우를 명확하게 이해하지 못했는데요
>
> 좋아요를 누른다 = 등록 api
좋아요를 한번 더 누른다 = 삭제 api
좋아요를 누른 상태에서 싫어요를 누른다 = 등록 api
가 맞나요?
이 상황에서 delete,insert로 바꾼다는 말이 무슨 말인지 잘 모르겠습니다.

정확하게 파악하셨습니다.

- 새롭게 눌리거나, 기존의 것과 다른 것이 눌렸을 때는 등록 API
- 기존에 눌려있던 것을 다시 한번 눌렀을 때는 삭제 API

이렇게 정리되겠네요.

또한, UPDATE 를 DELETE + INSERT 로 바꾼다고 한 얘기는, 분기 복잡성을 낮추기 위해서 나왔던 얘기에요.

기존에 눌려있던 타입을 바꿀 땐 UPDATE 쿼리, 새롭게 눌릴때는 INSERT 쿼리가 발생되는데요!

그렇게 하지말고, 기존에 눌려있던 안눌려있던 그냥 DELETE 하고 INSERT 한다면 분기문이 더 적어지겠죠? 그래서 나온 얘기였습니다.

> 라는 말의 뜻이, 사용자가 좋아요와 싫어요 버튼을 빠른 시간 내에 누른다는 건가요.
가능한지는 모르겠지만, 트랜잭션에 동기화된 큐를 사용하는 방법은 없을까요?
최근에 배운 jdbc 트랜잭션 매니저가 생각나서요
>
> aop를 사용해서 나아가 패키지내의 특정 서비스 클래스중 특정 메서드(트랜잭셔널이 붙은)가 실행 될 때, 트랜잭션 식별자를 만들어서 스레드 로컬(따로 클래스)에 저장한다.
(여기부터는 어떻게 구현할지 잘 모르겠음) 동기화된 큐에 먼저 도착한 스레드의 트랜잭션 아이디를 저장, 다음 걸 저장 한뒤,
fifo로 응답 처리하면 되지 않을까요
라고 망상해보았습니다

호오... 깊게 생각하셨군요.. 일단 동기화 큐를 사용하는 게 기술적으로 가능한지는 모르겠어요. 스레드 로컬을 사용하면, 각 스레드에서만 사용할 수 있는 상태일텐데, 동시에 요청이 들어오면 다들 각각 다른 스레드를 사용하겠죠 ? 그러면 각 요청 스레드들은 다른 곳의 스레드 변수를 모를텐데.. 이에 대해 큐를 구현할 수 있을가요...?

일단 제가 말했던 문제점은 이런 겁니다.

사용자는 A - B 순서대로 따닥 했다고 가정해봐요. 그러면 사용자는 B 상태가 적용되어있을거라 기대하겠죠?

이때 서버 입장에서는 A 요청과 B 요청이 동시에 날라갔는데, `네트워크 시간 + 코드 시간`이 적절히 기막히게 밀려서 B 요청에 대한 트랜잭션이 먼저 처리되고 A 요청에 대한 트랜잭션이 그 후에 처리된 상황을 가정해보는거죠.

사용자의 입장에서는 분명 B 를 더 늦게 눌렀으니 B가 적용되었을것이라 기대하겠지만, 서버 입장에서는 B 트랜잭션이 먼저 처리되고, 그 후에 A 트랜잭션이 처리되었으니 서버 리소스의 상태는 B가 아닌 A 일거에요.

이런 곳에서 차이가 발생할 수 있어서.. 이에 대한 해결은 아마 클라이언트에서 하거나, 요청 스펙에 `버튼을 누른 순서` 정보가 함께 추가로 와야할 것 같아요. 그래야 정확하게 처리할 수 있겠죠?

2023-10-15 18:13 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
> +        return placeLikeRepository.save(new PlaceLike(place, player, placeLikeType));
아 있네요..? 죄송합니다..

2023-10-16 00:48 UTC, zillionme approved these changes
코코닥 친절한 코멘트까지 모두 확인했습니다.👍🏻
수고하셨숩니다!

+)

루카-코코닥이 얘기한 따닥 문제가 A-B가 순서대로 거의 동시에 날라왔는데, 선입된 요청이 선출되지 않을 수 있다는 문제라고 생각해서 동기화 큐 얘기를 남긴건데요. 요청 선입 선출의 문제가 아니라
네트워크 지연등의 문제로 A 요청이 B 요청보다 먼저 서버에 도착하고 처리된 경우를 말한건가요?

요청은 a-b로 도착했지만 응답은 b-a순으로 나가는 문제는 동기화(여러 스레드가 한번에 하나씩만 접근 할 수 있도록)를 통해 해결할 수 있다고 생각했는데
후자의 문제는 클라이언트에서 요청의 시간을 보내주는 방식이 아니면 요청의 순서를 정하는 게 어려울 것 같습니다.

2023-10-16 01:22 UTC, merged