쪽지 등록 및 기록 API 구현
woowacourse-teams/2023-naaga pull request #463
Opened 2023-10-14 02:21 UTC by zillionme

## 📌 관련 이슈
- closed: #456  

## 🛠️ 작업 내용
- [x] 쪽지 등록/기록하는 ApI구현
  - [x] 서비스 로직
  - [x] API 연결
- [x] 테스트 작성

## 🎯 리뷰 포인트
1. LetterService 에 아래와 같은 코드가 있는데요.
```
    private Game getGameInProgress(final Player player) {
        final FindGameByStatusCommand findGameByStatusCommand = new FindGameByStatusCommand(player.getId(), IN_PROGRESS);
        final List<Game> gamesInProgress = gameService.findGamesByStatus(findGameByStatusCommand);
        if(gamesInProgress.isEmpty()) {
            throw  new GameException(GameExceptionType.NOT_EXIST_IN_PROGRESS);
        }
        return gamesInProgress.get(0);
    }
```
현재, 쪽지를 등록한 후, 진행 중인 게임에 한해서 쪽지를 기록할 수 있도록 했기 때문에, 진행중인 게임이 없으면 예외를 발생시킵니다.
이때, "게임이 존재하지 않는 예외"를 발생해야하는지, "진행중인 게임이 존재하지 않습니다"라는 예외를 터뜨려야 하는지 의견을 묻고 싶은데요
게임 컨트롤러에서 사용되는 gameService.findGamesByStatus는 진행중인 게임이 없다면 빈 리스트를 반환합니다.
하지만 게임 중 등록한 쪽지 기록의 경우, 진행중인 게임이 존재하지 않으면 반드시 예외를 터뜨려야 합니다.
기존의 GameExceptionType.NOT_EXIST 예외는, gameService.findById메서드에서 Id에 해당하는 게임이 존재하지 않을 때 예외가 발생하는데요.

제 의견은, 진행 중인 게임이 없는 것은 gameId에 해당하는 게임이 없는 것과 다르다고 생각합니다.
그 이유는, 예외 발생에 있어서 게임을 찾아오는 조건이 다르기 때문인데요. (특정 게임을 조회하는 것과 진행 중인 조건이 달린 게임을 조회하는 것)
헷갈리는 이유는 단순히, 진행 중인 게임은 결과적으로 1개일 수 밖에 없어 논리적인 식별자로도 작동하기 때문입니다.

만약 종료된 게임이 존재하지 않아서 예외를 터뜨려야 하는 상황이 있다고 가정하면, 이 또한 특정 조건에 해당하는 게임이 존재하지 않는 것이기 때문에 NOT_EXIST_DONE이라는 예외가 발생해야할 것 같습니다.

---

2.LetterService의 getGameInProgress()메서드의 위치에 관하여.
     letter 테이블에 game이 존재하지 않도록 했지만, 실제로 현재, 게임은 <등록>이라는 행위에 있어서 게임에 종속적입니다.
따라서 게임이 존재하지 않는다면, 쪽지를 등록할 수 없어야하는데요.

현재의 코드는 게임이 존재하지 않더라도 플레이어가 있으면 쪽지를 등록하고,
게임 중 등록한 쪽지를 기록(log)할 때, 기록 할 게임이 존재하지 않는다면 예외가 발생하도록 하게 두었습니다.

letter 객체를 생성하기 전에 해당 메서드를 먼저 실행하는 것이 맞는지 의견 내주시면 감사하겠습니다.

---

3.`WriteLetterLogCreateCommand` 에서 게임 id가 아닌 게임 객체와 쪽지 객체를 넘겨주고 따로 조회하지 않는 이유.
    - 이미 진행중인 게임이라는 가정하에 “등록쪽지”를 “기록”함
    - 이미 만들어진 쪽지라는 가정하에 “등록 쪽지”를 “기록”함
    
    즉, 진행중인 게임에 등록된 쪽지라는 가정이 있어야 기록도 가능하기 때문에, 위와 같이 dto를 만들게 되었습니다.
    
    이 부분에 대해서 다른 의견 있다면 남겨주세요!

### 개인적인 질문
```
INACCESSIBLE_AUTHENTICATION(
            403,
            HttpStatus.FORBIDDEN,
            "게임에 접근할 수 있는 권한이 없습니다."
    ),

    NOT_EXIST(
            404,
            HttpStatus.NOT_FOUND,
            "게임이 존재하지 않습니다."
    ),
    NOT_DONE(
            417,
            HttpStatus.BAD_REQUEST,
            "아직 종료되지 않은 게임입니다."
    ),

    HINT_NOT_EXIST_IN_GAME(
            454,
            HttpStatus.NOT_FOUND,
            "게임에서 해당 힌트가 존재하지 않습니다."
    ...
}
```
는 GameExceptionType 클래스의 일부인데요
백엔드 정의 에러코드에서, 
- 첫번째 숫자 4=Game 도메인에서 발생한 에러
인 것은 알겠는데, 두번째 세번째 숫자가 의미하는 법이 뭔가요?
노션에서 예외 관련 컨벤션을 찾아봤는데 존재하지 않네요ㅠ 제가 못찾은 걸수도 있는데, 어디에 위치하는지 대충이라도 아시는 분이 알려주실 수 있나요

## ⏳ 작업 시간
추정 시간:   3시간
실제 시간:   3시간

2023-10-15 03:08 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
P2:

채채의 PR과 같은 의견인데요.
해당 부분은 LetterLog에서 궁금할 일이지 Letter에서는 딱히 궁금해할 일이 아닌것 같습니다.
등록자의 PlayerId를 WriteLetterLogSevice로 넘겨주면서 쓰기에 대한 기록을 할 때, 
위와 같은 작업을 하는 것이 적합해보입니다.

2023-10-15 04:48 UTC, dooboocookie requested changes
이레 고생많으셨어요

# 1번 질문

> "게임이 존재하지 않는 예외"를 발생해야하는지, "진행중인 게임이 존재하지 않습니다"라는 예외를 터뜨려야 하는지 의견을 묻고 싶은데요.

저는 일단 두 예외 다 괜찮다라고 생각합니다.

위의 리뷰에서 남겼지만, 해당 게임을 조회하는 쿼리는 특정 조건으로 필터링하는 것이 아니라.
해당 상황에서는 진행중인 게임이 꼭 존재할 것이라고 생각하고 그 단건을 조회하는 것이기 때문입니다.

이레 말대로 논리적으로 저희 Game은 `playerId가 특정되고`, `In Progressing인 게임`은 `유니크`해야합니다.
그렇기 때문에 이것은 id로 조회하는 것과 별반 다를바가 없습니다. 그래서 기존에 NOT_EXIST를 발생시키는 것도 무리는 없다고 생각합니다.
하지만 이 상황을 조금 더 특정한 상황이라고 판단해서 다른 커스텀 예외를 터뜨리는 것도 좋다고 생각합니다.

저는 다만 이 쿼리를 날리는 GameSerivce의 메서드가 조금 다를 필요는 있다고 생각합니다. 이는 리뷰에 남겼습니다.

# 2번 질문

> letter 객체를 생성하기 전에 해당 메서드를 먼저 실행하는 것이 맞는지 의견 내주시면 감사하겠습니다.

이레는 일련의 과정을 진행하기 전에 등록할 수 있는 상태인지 검증을 모두 하고 프로세스를 진행한다는 말씀이시죠?
저는 일단 이는 하나의 트랜잭션으로 묶여있기 때문에 절차적인 문제는 거의 고려하지 않아도 된다는 의견입니다.
다만 저는 조금 더 저희가 책임 분리를 한 만큼 어느 곳에 책임들이 위치해있을지 고려했으면 좋겠습니다.

이레가 테이블 설계할 때는 쪽지가 게임에 종속되지 않았으면 좋겠다고 생각하고 테이블 분리를 하셨자나요?
저는 그에 대한 생각이 Service에도 반영이 되어야했다고 생각합니다.
지금은 LetterService가 GameService를 의존하고 있으니 종속적인 것이겠죠?
Game에 종속적인 것은 LetterLog로도 충분하지 않을까요?

# 3번 질문

> WriteLetterLogCreateCommand 에서 게임 id가 아닌 게임 객체와 쪽지 객체를 넘겨주고 따로 조회하지 않는 이유

이는 채채 리뷰와 이레 리뷰에 내용 남겨서 그냥 같이 고려해보면 될 것 같아요..

---
![image](https://github.com/woowacourse-teams/2023-naaga/assets/79090478/1df1d433-141d-4fe3-88bf-96d34f8f89b8)

이렇습니다.
2번쨰 숫자는 5부터 차근차근 숫자가 커질 때 발생할 수 있는 숫자 아닐까요? 혹은 서브도메인을 나타내는 숫자일 수도 있겠네요.

2023-10-15 04:48 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +                .isInstanceOf(GameException.class);
P3:

코코닥이 저에게 해줬던 리뷰인데요.
```suggestion
        Assertions.assertAll(() -> {
            final BaseExceptionType baseExceptionType = assertThrows(GameException.class, () -> letterService.createLetter(letterCreateCommand))
                    .exceptionType();
            assertThat(baseExceptionType).isEqualTo(GameExceptionType.NOT_EXIST_IN_PROGRESS);
        });
```
이런 식으로 Junit의  assertThorws로 그 안의 타입까지 검증하면 더 정확한 예외 상황 검증이 가능할 것 같습니다.
제가 이것을 assertAll에 다 묶은 이유는 asserThrows로 예외를 받아내는 과정도 예외가 터지지 않으면 저기서 테스트가 터지기 때문에 저 것을 모두 검증의 영역으로 봐서입니다.
assertSoftly를 사용하지 않은 이유는 assertThrows가 assertJ가 아니여서 softAssertions.으로 체이닝이 불가능하더라구요

2023-10-15 04:48 UTC, dooboocookie commented on backend/src/test/resources/truncate.sql
> +TRUNCATE TABLE write_letter_log;
👍

2023-10-15 04:48 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/WriteLetterLogCreateCommand.java
> +                                          Letter letter) {
P?:

이는 제가 [채채 리뷰](https://github.com/woowacourse-teams/2023-naaga/pull/460#discussion_r1359261763)에서도 언급을 했는데, 이런 서비스가 서비스에게 커맨드를 넘겨줄 때, 영속화 되어있다고 가정하고 넘겨주는 것이 맞을까요??
아니면 해당 도메인을 처리하는 쪽에서 영속화해서 사용하는 것이 맞을까요?

2023-10-15 15:53 UTC, dooboocookie approved these changes

2023-10-15 17:16 UTC, kokodak requested changes
안녕하세요 이레

잘 구현해주셨군요 🚀

하지만.. 늘 그렇듯 첫방은 RC 요청....

리뷰 열심히 남겨봤는데 한번 쭉 확인해주시면 감사하겠습니다~

2023-10-15 17:16 UTC, kokodak commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +    }
P4:

음.. `이 테스트가 LetterServiceTest 에서 검증해야 할 테스트일까?` 를 한번 같이 고민해봐요. 이레는 어떻게 생각하세요?

저는 이 테스트에서 검증하고 싶은 부분이 LetterService 보다는 PlayerService 의 관할처럼 느껴져서요 ㅎㅎ.. 각 서비스의 테스트는 자신의 도메인 로직에 대해서만 집중하는 것이 어떨까 하는 생각이긴 한데..

그런 입장에서 봤을 때, `플레이어가 존재하지 않는다면 예외` 라는 검증은 이미 PlayerService 에서 됐다고 생각하는데, 이레는 그래도 여기에서 한번 더 검증하는 것이 낫다! 라는 생각이신지 궁금해요

2023-10-15 17:16 UTC, kokodak commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +    }
추가로 여기에서도 [이 코멘트](https://github.com/woowacourse-teams/2023-naaga/pull/463/files#r1359757817)를 적용하면 좋을 것 같네요 - ~ -

2023-10-15 17:16 UTC, kokodak commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +    // TODO : 삭제할 주석(질문) 플레이어가 존재하지 않는 경우, AuthInterceptor에서 예외가 발생할 것 같은데 맞나요?
아뇨 리졸빙할때 발생할 겁니다

2023-10-16 03:34 UTC, zillionme commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
> +    // TODO : 삭제할 주석(질문) 플레이어가 존재하지 않는 경우, AuthInterceptor에서 예외가 발생할 것 같은데 맞나요?
아 그러네용

2023-10-16 03:44 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    public Letter createLetter(final LetterCreateCommand letterCreateCommand) {
수정했습니다!

2023-10-16 04:10 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +    }
동일하게 생각합니다 수정했습니다

2023-10-16 04:10 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +        return gamesInProgress.get(0);
저도 좋은 것 같습니다. 수정했습니다!

2023-10-16 04:11 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/presentation/dto/LetterResponse.java
> +                             ) {
수정했습니다

2023-10-16 04:41 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/presentation/dto/LetterResponse.java
> +    public static LetterResponse of(final Letter letter) {
까먹었네요 감사합니다 수정완!

2023-10-16 04:41 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +        final Letter savedLetter = letterRepository.save(letter);
미션 1하다가 와서 정신이 나갔었나봐ㅏ여 감사합니다. 수정완

2023-10-16 04:47 UTC, zillionme commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +    }
사실 중간에 깨달았는데 이미 쓴게 아까워서 PR에 날렸습니다. 삭제하도록 하겠숩니다...ㅜ

2023-10-16 04:48 UTC, zillionme commented on backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
> +        final Letter expected = letterService.createLetter(letterCreateCommand);
변경 했습니다~

2023-10-16 09:12 UTC, kokodak approved these changes

2023-10-17 07:59 UTC, chaewon121 approved these changes
이레 안녕하세요! 저와 함께깃 충돌을 하면서 여러 코드가 섞여버렷네요 ㅠㅠㅠ 이레와 코드가 많이 겹치면서 저는 특별히 리뷰할게 없을 것 같습니다! 위에 분들이 잘 해주셨군여..
고생 많으셨습니다~! 아마 서비스 로직은 수정될것같네요 이부분에 대해서 함께 고민해 보아요~!

2023-10-17 08:56 UTC, merged