feat: 쪽지 등록기능 구현
woowacourse-teams/2023-naaga pull request #478
Opened 2023-10-15 13:25 UTC by krrong

## 📌 관련 이슈
- closed: #475 

## 🛠️ 작업 내용
PR에서 작업한 주요 내용을 적어주세요.
- [x] 인게임에서 쪽지 아이콘을 클릭하면 쪽지를 등록할 수 있는 다이얼로그가 뜬다.
- [x] 전송하기 버튼을 누르면 서버에 전송한다.
- [x] 성공하면 스낵바를 보여준다.

## 🎯 리뷰 포인트
### LetterView
- 간단한 Compound view입니다. Compound view로 만든 이유는 쪽지 등록 뷰가 괜찮다면 쪽지를 등록하는 다이얼로그 상위에도 넣으려고 해요. 이 때 재사용하기 위해 만들어보았습니다. 피그마로 확인해봤을 때는 괜찮았었습니다. 어떨지 디자이너 뽀선생님께서 판단해주세요🤠

### 약간의 미완성
- 서버에 쪽지를 등록하는 기능이 붙기 전이라 전체적인 흐름을 확인해보지는 못했습니다. 목서버를 만들려고 하니 인게임 페이지까지 들어가는 것도 좀 어려웠고, 월 제한 횟수를 넘어서 더 사용하려면 유로로 전환을 하라고 하더군요. 곤란했습니다.
- 서버에 API가 연결되면 한 번 더 확인해보겠습니다.

### 고민
- 한 가지 고민이 있는데, 약간의 기획적인 요소입니다. 사용자가 쪽지를 등록하고, 등록이 되면 지도에 보여지는 것이 나을까요? 뽀또의 생각은 어떤가요?
- 이에 대해 다른 처리는 해놓지 않은 상태입니다.

## ⏳ 작업 시간
추정 시간: 3h  
실제 시간: 3h

2023-10-17 11:41 UTC, briandr97 requested changes
고생하셨습니다! 리뷰 남겼습니다!
궁금한 점이 아직 레트로핏 서비스 인터페이스는 만들어지지 않은 상태고 그러므로 서버통신도 아직 안되는 상태인거죠?

2023-10-17 11:41 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterSendDialog.kt
> +    var message: String = ""
[P5]
이렇게 var로 선언하면 양방향 데이터 바인딩이 되나요?
처음 보는 방식이라 생소하네요

2023-10-17 11:41 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/custom/LetterView.kt
> +        binding.vLetterBackground.setOnClickListener { }
[P1]
혹시 지우는걸 잊으신건지 미래를 위한 무언가인지 궁금합니다!

2023-10-17 11:41 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/custom/LetterView.kt
> +class LetterView(context: Context, attrs: AttributeSet?) : ConstraintLayout(context, attrs) {
[P2]
사실 해당 뷰는 클릭리스너를 제외하고는 기능이 따로 없어서 배경이 있는 아이콘으로 뽑아서 사용하는게 더 가볍고 자연스러울 수 있다고 생각합니다!
(피그마를 봤을 때 하나의 뷰라기 보다는 하나의 아이콘 (혹은 이미지)라는 느낌이 듭니다!)

2023-10-17 11:41 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    val isSuccess: LiveData<Boolean> = _isSuccess
[P2]
무엇에 대한 성공인지가 변수명에서 드러나면 더 좋을 것 같습니다!

2023-10-17 11:41 UTC, briandr97 commented on android/app/src/main/res/layout/dialog_send_letter.xml
> +            android:text="@={dialog.message}"
[P5]
위에도 남겼지만 이게 양방향 데이터 바인딩 되는게 신기하네요

2023-10-17 12:28 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/custom/LetterView.kt
> +        binding.vLetterBackground.setOnClickListener { }
리스너를 어디서 달지 고민하다가 지우지 못했네요!  
꼼꼼하게 확인해주셔서 감사합니다 🤠

2023-10-17 12:35 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/custom/LetterView.kt
> +class LetterView(context: Context, attrs: AttributeSet?) : ConstraintLayout(context, attrs) {
저도 그 생각을 하기도 했는데요, 뷰를 따로 만들게 된 이유는 2가지가 있습니다.

1. 우리 앱의 사이즈가 너무 크다.
저는 이러한 이유가 drawable이 너무 많아서 그런 것이 아닌가? 하는 생각에 쪽지 아이콘의 drawable을 조금이라도 적게 유지하기 위해 뷰로 만들었습니다.  
혹시 가볍다는 말이 여기서 작용하는 것일까요? 잘 모르겠어서.. 그렇담 당장 바꾸겠습니다ㅎㅎ..


2. 더 유연하게 사용할 수 있다.
빅스 말대로 배경이 있는 아이콘을 가져오는 것이 더 자연스럽게 생각되었지만, 이번에 디자인을 전체적으로 변경하면서 느낀바가 있습니다. 만약 배경색이 변하거나 없는 것을 요하게 된다면 다시 피그마에서 디자인을 가져와야 할 것이고, 저는 이것보다는 컴파운드뷰를 만들어 사용하는 것이 더 낫겠다 생각했어요.

제 의견을 들은 빅스가 Pn이 몇으로 바뀌는지 보고 적용해보겠습니다 :)

2023-10-17 12:38 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    val isSuccess: LiveData<Boolean> = _isSuccess
isSendLetterSuccess으로 변경했는데 구리네요.. 좋은 네이밍 추천해주실 수 있을까요?

2023-10-17 12:41 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterSendDialog.kt
> +    var message: String = ""
정확히는 `var message: String = ""`로 선언하는 것 외에 추가적으로 다음의 요소들이 필요합니다.

- dialog_send_letter에서 
```xml
<data>

    <variable
        name="dialog"
        type="com.now.naaga.presentation.common.dialog.LetterSendDialog" />
</data>
```
- LetterSendDialog에서 `binding.dialog = this`

2023-10-17 12:48 UTC, krrong commented
> 궁금한 점이 아직 레트로핏 서비스 인터페이스는 만들어지지 않은 상태고 그러므로 서버통신도 아직 안되는 상태인거죠?


뽀또와 제가 같은 기능을 구현하기 때문에 공통으로 사용하는 기초 코드들을 먼저 작성하는 이슈(https://github.com/woowacourse-teams/2023-naaga/pull/450)를 발행했고, 이 위에서 작업을 진행했습니다!   
레트로핏 서비스 인터페이스는 있으며, 쪽지 등록 API 연동까지 확인했습니다!  

다만, 쪽지 등록이 완료된 후에 지도에 마커는 찍히지 않고 스낵바로 알려주고 있습니다.

2023-10-17 15:48 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterSendDialog.kt
> +    var message: String = ""
네네 저것들 모두 확인했는데, 되는게 신기하네요

2023-10-17 15:50 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    val isSuccess: LiveData<Boolean> = _isSuccess
막 세련됐다는 느낌은 아니지만, 의미가 잘 전달된다고 생각합니다!

2023-10-17 16:12 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/custom/LetterView.kt
> +class LetterView(context: Context, attrs: AttributeSet?) : ConstraintLayout(context, attrs) {
[P2]
1. 우리 앱의 사이즈가 너무 크다.
저는 이 부분이 이미지가 커스텀 뷰로 바뀌는 것으로 해결될 문제는 아니라고 추측합니다.
저도 혹시 몰라서 [커디 레포](https://github.com/woowacourse-teams/2023-emmsale/tree/android-main)를 확인해봤는데 drawable의 수가 저희에 비해 훨씬 많습니다. 하지만 그럼에도 플레이스토어에 올라가 있는 용량은 나아가가 훨씬 큽니다. (나아가 20mb, 커디 4mb)
이 부분은 제 추측상으론 아마 gradle에서 릴리즈 모드시 몇 가지 설정을 해주지 않아 일어난 것으로 보입니다.
물론 저도 해보지 않아 확신할 수 없지만, 해당 설정들을 사용시 용량이 많이 줄어드는 것으로 알고 있습니다.
[블로그 링크](https://milkissboy.tistory.com/7)
[공식문서 링크](https://developer.android.com/studio/build/shrink-code?hl=ko)
그리고 제가 "가볍다"라고 표현했던 부분은 용량적인 부분은 아니었습니다.
단순히 화면에 아이콘 하나를 띄울 때 이미지를 뽑는 것과 커스텀 뷰를 만들어 사용하는 것의 코스트 및 사용성에 대한 표현이었습니다.

2. 배경색이 변하거나 없는 것을 요하게 된다면
배경색이 없는 이미지를 뽑고 background에 drawable(shape: oval)을 적용해볼 수도 있을 것입니다.
또한 배경색이 있거나 없거나와 같이 두 가지 정도의 선택지는 괜찮다고 생각되지만 단순한 아이콘이 여러 배경색을 현란하게 갖고있게 된다면 그 부분은 디자인적인 문제라고 생각합니다.

2023-10-17 16:14 UTC, briandr97 requested changes
다시 리뷰 남겼습니다!
그리고 쪽지를 남겼을 때 어떤 피드백을 주어야할까에 대해서는 저는 현재와 같이 스낵바(혹은 토스트)가 맞다고 생각합니다.
왜냐하면 (이 부분이 쪽지 쪽 기획에서 어떻게 결정됐는지는 모르지만) 제가 등록한 쪽지는 필터링돼서 제 지도에 보이지 않을 것이라고 생각했기 때문입니다.

2023-10-17 18:11 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/custom/LetterView.kt
> +class LetterView(context: Context, attrs: AttributeSet?) : ConstraintLayout(context, attrs) {
이미지를 뽑아 drawable로 만들어도 될 것 같아 그렇게 진행했습니다~

2023-10-17 18:35 UTC, krrong commented
<img src="https://github.com/woowacourse-teams/2023-naaga/assets/84285337/5be3a489-a443-4aec-897a-3a00d65df173" width=220>
<img src="https://github.com/woowacourse-teams/2023-naaga/assets/84285337/05188ec6-e407-4192-b17e-1f97858a5c19" width=220>

2023-10-18 03:00 UTC, briandr97 approved these changes
고생해서 커스텀 뷰도 만들어주셨는데 제 리뷰 적용해주셔서 감사드립니다!
고생하셨습니다 이만 머지하도록 하겠습니다!

2023-10-18 03:00 UTC, merged