feat: 내 주변 100m 내의 쪽지들을 조회하는 기능 구현
woowacourse-teams/2023-naaga pull request #480
Opened 2023-10-15 15:02 UTC by hyunji1203

## 📌 관련 이슈
- closed: #457 

## 🛠️ 작업 내용
- [X] 쪽지 아이콘 추가
- [X] DI Repository Module 오류 수정
- [X] 내 주변 100m 내에 존재하는 쪽지들을 조회하기
- [X] 지도에 쪽지 마커 추가하기
- [X] 반경 50m 내에 쪽지가 존재하는지 확인하는 로직 추가
- [X] 50m 확인 로직 테스트 추가
- [X] 반경 50m 내의 쪽지 활성화 시키기

## 🎯 리뷰 포인트
- 쪽지 마커가 활성화와 비활성화 구분이 잘 안되는 것 같아 글씨를 달아놨는데, 해당 마커 아이콘 괜찮은가요? 별로면 대체할 아이콘 추천받습니다!
- livedata 블록을 사용해 서버와의 정기적인 통신이 이뤄지도록 구현하였습니다. 해당 로직에 대해 리팩할 부분이 있다면 꼭 짚어주세요. 제 로직이 괜찮은 로직인지, 아니면 목이 돌아가며 날라가는 비둘기 로직인지 잘 모르겠습니다ㅎㅎㅎ
- 주기를 `delay(15000)`로 하였습니다. 해당 주기 선정 이유를 설명 드리자면, 우선 네이버 지도 정보 제공 상 100m를 걷는데 1분이라는 시간이 걸린다고 합니다. 여기서 100m 반경의 반지름인 50m를 걷을 때마다 정보가 갱신되길 바랬기 때문에, 따라서 60000ms에서 절반인 30000ms로 처음엔 지정했었습니다. 하지만 에뮬로 위치를 이동하며 실험해본 결과(실제로 해보지 않은게 좀 아쉽긴 합니당..) 좀 더 갱신 주기가 짧았으면 좋겠다는 생각이 들어 30000의 절반인 15000ms로 주기를 정하였습니다. 이에 대한 리뷰어님의 생각이 궁금합니다!
- 반경 50m 내의 쪽지 활성화 기능을 위해, 해당 거리 측정 로직을 `ClosedLetter`에 넣어놨습니다. 여기에 넣어 구현하는게 괜찮은 구조일까요?
- 포스트맨을 이용해 목서버 테스트를 거쳤습니다. 목서버를 이용한 테스트는 완벽했는데 실제 서버 API와 연동했을 때도 잘 될지는 직접 확인해봐야 알 수 있을 것 같아 이부분은 고려해주시면 될 것 같습니다!!

## ⏳ 작업 시간
추정 시간:  4h 
실제 시간:  8h
이유: 우선 livedata 블록을 이용한 서버와의 정기적인 통신을 해본 적이 없어 공부하느라 시간이 좀 걸렸고, 주기 결정 및 목서버 테스트를 거치느라 시간이 좀더 늘어진 경향이 있습니다!

2023-10-16 11:04 UTC, krrong requested changes
뽀또!🍪 정말 고생많았습니다. 처음 해보는 기능이고 도전일 수 있는 기능이었는데 잘 적용해준 것 같아서 고마워요!  
반영할만한 코멘트를 몇 가지 남겨두었습니다. 확인해주세요!

추가로 뽀또가 남긴 물음에 대한 제 생각을 코멘트로 남겨둘게요.

> 15000ms로 주기를 정하였습니다.

쪽지에 대한 주기를 정하는데 어려웠을 것 같아요. 저는 뽀또가 설정한 주기가 이유도 타당해보이고 꽤나 맘에듭니다. 주기는 언제든 변경할 수 있으니 QA 테스트를 진행하면서 적당한 주기인가 테스트 해보면 더 좋을 것 같아요.

> 거리 측정 로직을 ClosedLetter에 넣어두었습니다.

저는 Coordinate 도메인 클래스가 거리 측정 로직을 가지고 있는 것이 자연스럽다고 생각해요. 결국 ClosedLetter 내부에서도 Coordinate을 통해서 계산을 하니까요. 저는 에러가 발생하지 않는 단단한 앱을 출시하는 것이 제 1목표라고 생각하기 때문에 수정하는데 많은 시간이 소요될 것 같다면 반영하지 않아도 좋습니다.

2023-10-16 12:41 UTC, krrong approved these changes
단건조회 기능 구현 후 리팩터링 및 리뷰 반영 부탁드릴게요!

2023-10-16 12:44 UTC, merged

2023-10-17 02:20 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/NaverMapSettingDelegate.kt
> +            map = naverMap
좋아요!
현재 단건 조회 구현하면서 해당 아이콘 세팅 로직 분리하였습니다~!!!

2023-10-17 02:39 UTC, hyunji1203 commented on android/domain/src/main/java/com/now/domain/model/letter/ClosedLetter.kt
> +    var isNearBy = false
사실 첨엔 해당 변수를 만들지 않고 메서드의 반환값을 사용해 판별해주려다가 마지막에 변수를 생성해주었습니다!
그 이유는 서버와의 통신 중 쪽지리스트를 받아오자마자 내 위치와의 거리를 계산을 해줘야하는데 내위치 좌표가 저장되어있는 `myCoordinate`가 viewmodel에 존재하고 있기 때문입니다. 
따라서 `myCoordinate` 값을 활용해서, 쪽지를 불러오는 초기에 싹 거리 계산을 해주고 해당 계산 값을 각각의 쪽지 객체에 저장해 놓으면..
뒤의 쪽지 로직에서 자유롭게 쓸 수 있을 수 있게 되어 이런 장점으로 인해 해당 로직으로 구현하게 되었습니다! 
혹시 제가 생각 못한 다른 방법이 있다면.. 알려주시면 감사드리며 바로 수정하도록 하겠습니다!!🤩

2023-10-17 02:40 UTC, hyunji1203 commented on android/domain/src/main/java/com/now/domain/model/letter/ClosedLetter.kt
> +    fun isNearBy(myCoordinate: Coordinate) {
오 크롱이 추측이 아주 정확하게 맞았습니다ㅋㅋㅋㅋ
진짜 크롱의 말처럼 굳이 알 필요가 없는 정보였네요. 항상 이부분에 대해 간과하고 지나가는 경향이 있었는데 짚어주셔서 감사합니다ㅎㅎ

2023-10-17 06:54 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +
넵넵!
저도 구현을 할 때 내 위치를 잡지 못한 상황에서 어떻게 하면 좋을지 많은 고민을 했었습니다!
이를 어떻게 처리할까 생각하다 제 코드처럼 구현을 한 것인데 확실히 크롱의 말처럼 위치를 잡지 않은 상황에서는 아예 요청을 보내지 않는 것이 옳은 로직이라고 생각되네요!
해당 리뷰 반영하였습니다!
더 좋은 코드를 적용시켜 주면 좋겠다고 하셨는데...우선 마땅히 이 이상으로 생각나는 것이 없어 크롱 제안 코드로 수정하였습니다!