feat: 쪽지 단건 조회 구현
woowacourse-teams/2023-naaga pull request #493
Opened 2023-10-17 06:54 UTC by hyunji1203

## 📌 관련 이슈
- closed: #490 

## 🛠️ 작업 내용
- [X] 서버와의 통신을 통해 쪽지 데이터 불러오기
- [X] 50m 내에 있는 쪽지를 클릭 시 서버에서 받아온 쪽지 데이터를 다이얼로그에 띄워 사용자에게 보여주기
- [X] 쪽지 더블 클릭 시 다이얼로그가 여러번 뜨지 않도록 더블 이벤트 발생 막아주는 싱글이벤트클릭리스너 생성 및 적용

## 🎯 리뷰 포인트
- 뷰모델의 함수를 전달하며 사용해주는 로직을 사용 중인데 로직이 괜찮은지 궁금합니다!  

## ⏳ 작업 시간
추정 시간: 4h  
실제 시간: 9h 
이유: 우선 중간에 CI 이슈가 있어서 이거 고치느라 시간이 오래 걸렸습니다. 그리고 단건 조회 로직 구상이 좀 시간이 걸렸고.. 그리고 지난 전체 조회 때 못한 리팩터링도 좀 해야했고, 서버 에러도 있어서 시간이 더 걸렸습니다. 또 마커에 대해서도 쪽지를 불러올 때 마다 다시 싹 찍어주는 로직으로 변경하느라 좀 걸렸고 마지막으로 싱글이벤트클릭리스터를 overlay 맞춤 클릭 리스너로 바꾸는 과정이 좀 시간이 걸렸습니다ㅋㅋ

2023-10-17 08:25 UTC, krrong requested changes
고생했습니다 뽀또!!  
많은 시간이 걸린만큼 구현이 잘 된 것 같아요!!  
오프라인으로 나눴던 대화도 코멘트로 달아두었으니 확인부탁합니다!

2023-10-17 08:25 UTC, krrong commented on android/domain/src/main/java/com/now/domain/model/letter/ClosedLetter.kt
> +        isNearBy = coordinate.isNearBy(other)
[P1]  
Coordinate가 isNearBy 메서드를 가지고 있기 때문에 ClosedLetter가 같은 메서드를 가지고 있을 필요가 없어요!

2023-10-17 08:25 UTC, krrong commented on android/app/src/main/java/com/now/naaga/util/singleclickevent/OnSingleClickListener.kt
> +class OnSingleClickListener(private val onSingleClick: (overlay: Overlay) -> Unit) : Overlay.OnClickListener {
[P-1]  
대박...!👍🍪👍

2023-10-17 08:25 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
>              }
P[1]  
이 부분에 대해서는 어떤 방법이 더 좋을지 추후에 의견을 더 나눠볼까요?🤔

2023-10-17 08:25 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterReadDialog.kt
> +
P[4]  
프래그먼트를 보고 생각났는데요, 다이얼로그 프래그먼트에서도 다음과 같은 처리가 필요할까요?  
```kotlin
private var _binding: DialogReadLetterBinding? = null
private val binding: DialogReadLetterBinding = _binding!!
```

2023-10-17 08:25 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    fun getLetter(id: Long) {
P[3]  
위에 코멘트가 달리지 않아 아래 남겨놓겠습니다. 참고해서 더 좋은 코드 부탁드릴게요 :)
```kotlin
// before
private fun isLetterNearBy(letters: List<ClosedLetter>) {
    letters.forEach { letter ->
        myCoordinate.value?.let { letter.isNearBy(it) }
    }
}

// after
private fun isLetterNearBy(letters: List<ClosedLetter>) {
    letters.forEach { letter ->
        myCoordinate.value?.let { 
            letter.isNearBy = it.isNearBy(letter.coordinate)
        }
    }
}
```

2023-10-17 15:47 UTC, briandr97 requested changes
고생하셨습니다. 리뷰 남겼습니다!

2023-10-17 15:47 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    fun getLetter(id: Long) {
[P2]
우선 `ClosedLetter`내에 isNearby라는 프로퍼티와 메서드가 모두 존재하여 많이 헷갈리는 상황이네요
제안드리고 싶은 점에 대해 말씀드리겠습니다.

제가 이해한 바로는 `isNearBy` 프로퍼티는 한 번 정해지면 변하지 않는 상태입니다.
그러므로 해당 프로퍼티를 var이 아닌 val로 사용하는 것을 추천드립니다.

```kotlin
data class ClosedLetter(
    val id: Long,
    val coordinate: Coordinate,
    val isNearBy = false
)

val letters: LiveData<List<ClosedLetter>> = liveData {
    while (true) {
        val letters = myCoordinate.value?.let { myCoord ->
            letterRepository.fetchNearbyLetters(
                latitude = myCoord.latitude,
                longitude = myCoord.longitude,
            ).map { letter ->
                val isNearToPlayer = myCoord.isNearby(letter.coordinate)
                letter.copy(isNearby = isNearToPlayer)                    
            }
        } ?: emptyList()
        emit(letters)
        delay(15000)
    }
}
```

2023-10-17 22:16 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +
id와 player가 뷰를 그리는데에 있어 앞으로 필요없을 것 같기도 하고 , 크롱이 uimodel 클래스에 매퍼까지 만들어놓기도 해서 이런 이유들 + 통일성 으로 인해 uimdel로 들고 있도록 변경하였습니다!

2023-10-17 22:34 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterReadDialog.kt
> +
다음과 같은 처리가 필요한 이유를 모르겠습니다!! (저렇게 안써봐서 진짜루 모름)
혹시 저런 처리를 해주는 이유가 있을까요? 궁금합니다!

2023-10-17 22:36 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +                setError(it as DataThrowable)
넵!

2023-10-17 22:44 UTC, hyunji1203 commented on android/domain/src/main/java/com/now/domain/model/letter/ClosedLetter.kt
> +        isNearBy = coordinate.isNearBy(other)
넵넵! 삭제했습니다!

2023-10-17 22:48 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    fun getLetter(id: Long) {
두 리뷰어님의 의견들을 참고해 수정하였습니다!
크롱의 말처럼 coordinate끼리의 계산으로 가져가 isNearBy에 저장되는 느낌을 살리고
빅스의 말처럼 굳이 var로 둘 필요가 없기 때문에 val로 둔 후, 따로 isNearby를 계산해주는 함수를 넣는 것이 아닌 빅스가 추천해준 로직처럼 letters를 불러올 때 계산되어 완성 객체로 나가도록 수정하였습니다!

2023-10-17 22:51 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    fun getLetter(id: Long) {
한가지.. 지금 해당 letters의 로직이 매우 뚱뚱한 이슈가 있습니다..
이에 대한 해결책 있으신분은 언제든 말씀해 주시면 감사드리겠습니다🙏

2023-10-17 22:52 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/data/repository/DefaultLetterRepository.kt
>      override suspend fun fetchLetter(letterId: Long): OpenLetter {
이따 안드 다같이 얘기 나눠보죠!

2023-10-18 07:10 UTC, briandr97 approved these changes
고생하셨습니다! 잘 반영해주셨네요!

2023-10-18 07:10 UTC, merged