Refactor/#497
woowacourse-teams/2023-naaga pull request #513
Opened 2023-10-18 16:32 UTC by chaewon121

## 📌 관련 이슈
PR과 연관된 이슈의 번호를 작성해주세요.
PR 머지 시 close 되어야 하는 이슈의 경우 이슈 번호 앞에 `closed` 키워드를 붙여주세요.  
ex) `closed #2`

## 🛠️ 작업 내용
PR에서 작업한 주요 내용을 적어주세요.
- [ ] 작업1
- [ ] 작업2

## 🎯 리뷰 포인트
리뷰시 중점적으로 봐주었으면 좋을 부분을 적어주세요.  
없다면 적지 않아도 됩니다.  

- 리뷰 포인트

## ⏳ 작업 시간
추정 시간:   
실제 시간:   
이유: 차이가 많이 난다면 이유도 같이 적어주세요 :)

2023-11-02 06:02 UTC, kokodak requested changes
안녕하세요 채채 !

오랜만에 프로젝트에 들어와서 코드리뷰를 남겨봤어요. PR 작업한다고 고생하셨씁니다

Converter 를 직접 다뤄서 Enum 매핑 문제를 해결하려한 점이 인상 깊었어요 !

> 이넘으로 바인딩할때 해당 이넘값이 존재하지않으면 예외를 던지는데요. 이것이 핸들러에서 잡히지 않는것이었습니다.
이유는 리졸버에서 던지는 예외는 MethodArgumentTypeMismatchException.class
로 잡아야 하는데 저희 핸들러에서는 해당 클래스를 잡는 매서드가 구현되있지 않았습니다!

채채가 말해주신 부분에서 생각해볼만한 점이 있는 것 같아요.

**Enum 을 찾지 못했을 때 커스텀 예외를 던지는 것이 `MethodArgumentTypeMismatchException` 으로 변환되는 것이 좋을까?**

채채가 말씀해주신대로, 커스텀 예외를 던지더라도 저 예외로 바뀌더라구요. 왜인지 궁금해서 디버깅을 쭉 해봤는데, 범인은 Converter 였습니다.

일단 `MethodArgumentTypeMismatchException` 라는 예외를 던지는 주체는, 리졸버가 아닌 컨버터입니다. 저희가 던진 커스텀 예외는 `TypeConverterSupport` 라는 클래스에서 `TypeMismatchException` 예외로 변환됩니다. 

<img width="543" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/45879491/22562bbe-1198-4ed6-87d4-2ccc31446ace">

그후에, `AbstractNamedValueMethodArgumentResolver` 라는 이름의 리졸버에서 `TypeMismatchException` 을 잡고, 이를 `MethodArgumentTypeMismatchException` 예외로 변환시켜 클라이언트에게 던져주는 방식이네요.

<img width="650" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/45879491/178332a3-6d5e-40de-bbb6-cad486ea0a8a">

만약 채채가 `MethodArgumentTypeMismatchException` 예외가 아닌, 저희가 커스텀한 예외가 터지길 원한다면 Converter 가 아닌, 커스텀 ArgumentResolver 를 만들어서 LetterLogType 으로 매핑시켜주는게 좋을 것 같아요. 이렇게 하면 커스텀 예외가 스프링 예외로 변환되지 않고, 저희가 의도한 커스텀 예외 그대로 나가게 될 것 같아요 !

그렇지 않고 만약 커스텀 예외가 아닌, 스프링에서 사용자 입력 값에 대해 추상화된 예외를 사용하고 싶다면, 지금처럼 `MethodArgumentTypeMismatchException` 을 잡아줘서 common 예외로 변환시켜 던져주는 것이 좋을 것 같네요.

채채는 어떤 것을 왜 선호하시는지 궁금해요 ㅎㅎ

2023-11-02 13:25 UTC, dooboocookie requested changes
안녕하세요 채채

위에 Converter와 ArgumentResolver의 차이는 코코닥이 잘 설명해준 것 같은데요.
저는 추가적으로
- ArgumentResolver: 특정 조건의 아규먼트를 해결하기 위해서 HttpServletRequest, ... 의 값을 이용해서 어떻게 해결할지 정한다.
- Converter: 특정 타입을 특정 타입으로 컨버팅한다. 그리고 이것은 아규먼트를 리졸빙할 때보다 더 큰 범위에서 사용 가능하다.

전 개인적으로 해당 과정은 `Converter`가 적절하다고 생각합니다.

저는 해당 `@RequestParam`이 달린 아규먼트를 `HTTP 요청의 요청 파라미터의 밸류`를 가져온다는 것은 `RequestParamMethodArgumentResolver`에서  리졸빙을 해준다라고 생각합니다.

<img width="711" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/79090478/52947da1-8bb9-45fc-897c-2604b3df8ccf">

다만 타입컨버팅이 가능한 원시타입의 범위를 벗어난 enum타입으로 받으려는 것이 떄문에 추가적으로 타입컨버터만 필요하다고 생각합니다.

그런 이유로 채채가 한것처럼 컨버터를 추가로 한 것이 더 적절하다고 생각합니다.

그 이외에도 단 리뷰포인트들이 많아서 일단 RC합니다~

2023-11-05 09:49 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/letter/application/letterlog/ReadLetterLogServiceTest.java
> +//
허허 큰실수를 저질렀군요..

2023-11-06 08:21 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
> +    }
인정

2023-11-06 08:21 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
> +@RequestMapping
인정

2023-11-06 08:23 UTC, chaewon121 commented on backend/src/test/java/com/now/naaga/letter/presentation/LetterLogTypeTest.java
> +    }
이건 지워질거같아요 테스크를 오랜시간 작업하다보니 정리가 안되었네요..싹 수정하겠습니다

2023-11-06 08:40 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterLogType.java
> +                .orElseThrow(() -> new CommonException(INVALID_REQUEST_PARAMETERS));
해당 메서드의 역할은 컨트롤러 쿼리파라미터로 받은string을 enum으로 매핑해주는 역할입니다. 이것은 letter와 상관없이 요청 파라미터에 대한 예외라고 생각하는데 어떻게 생각하시나요!?

2023-11-06 12:36 UTC, zillionme requested changes
채채~ 이미 코코닥과 루카가 좋은 리뷰 많이 남겨준 것 같습니다!
쪽지 로그 조회에서 P2 리뷰가 하나 있어 RC리뷰 남기고 갑니당

2023-11-06 12:36 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +        final Game gameInProgress = getGameInProgress(findLetterLogByGameCommand.playerId());
P1:
findLetterLogInGame를 호출하는 시점은 게임이 종료된 이후 아닐까요?
진행중인 게임이 레터 로그를 읽을 이유가 없을 것 같아서요.

2023-11-06 12:36 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
>      }
루카와 동일한 의견입니다. 
이 부분 gameService 클래스에 아래와 같이 구현되어 있는데, 사용하면 좋을 것 같습니다!
    ```

    @Transactional(readOnly = true)
    public Game findGameInProgress(final FindGameInProgressCommand findGameByStatusCommand) {
        List<Game> gameInProgress = gameRepository.findByPlayerIdAndGameStatus(findGameByStatusCommand.playerId(), IN_PROGRESS);
        if (gameInProgress.isEmpty()) {
            throw new GameException(NOT_EXIST_IN_PROGRESS);
        }
        return gameInProgress.get(0);
    }
```

2023-11-06 12:36 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterLogType.java
> +package com.now.naaga.letter.presentation;
루선생님 강의 잘 듣고 갑니다

2023-11-06 12:36 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/domain/LetterLogTypeConverter.java
> +public class LetterLogTypeConverter implements Converter<String, LetterLogType> {
채채 컨버터라는 것은 RequestParam, RequestBody에 관계없이 동작하는 건가요? 
채채 덕분에 배우고 갑니다!

2023-11-06 12:36 UTC, zillionme commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterLogType.java
> +                .orElseThrow(() -> new CommonException(INVALID_REQUEST_PARAMETERS));
> 해당 메서드의 역할은 컨트롤러 쿼리파라미터로 받은string을 enum으로 매핑해주는 역할입니다. 이것은 letter와 상관없이 요청 파라미터에 대한 예외라고 생각하는데, 해당 매서드를 이넘에 두지 않고 다른 계층으로 이동하는 것이 맞을것같아서 수정하게 될것같네용

채채 이부분 정확히 이해하지 못해서 변경 후 알려주시면 감사하겠습니다

2023-11-06 13:16 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterLogType.java
> +                .orElseThrow(() -> new CommonException(INVALID_REQUEST_PARAMETERS));
수정 후 pr에 남겨놓겠습니다!

2023-11-06 13:34 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/presentation/LetterLogType.java
> +package com.now.naaga.letter.presentation;
확실히 서비스가 표현계층을 가지고 있는건 방향이 반대로 흐른다는 생각이드네요..

2023-11-06 14:32 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
>      }
루카의 의견대로 private으로 두는 것이 맞다고 생각합니다. 해당 메서드에 대해 테스트코트를 작성하다보니 자연스럽게 public으로 되어있던것같네요! private로직까지 함께 테스트가 되도록 수정해보겠습니당

2023-11-06 14:52 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/letter/application/LetterService.java
> +        final Game gameInProgress = getGameInProgress(findLetterLogByGameCommand.playerId());
이레천재..?

2023-11-06 15:49 UTC, chaewon121 reviewed
### 수정한 부분
1. 주석제거
2. LetterLogType -> 도메인으로 이동
3. LetterLogTypeConverter -> presentation/converter패키지로 이동
4. LetterLogType에서 예외를 LetterType으로 수정 (코코닥의견에 동의)
5. 추가적인 의견도 반영


LetterLogType에서 예외를 LetterType으로 수정후 LetterLogTypeConverter에서는 따로 예외를 잡아주지 않았습니다.

어차피 LetterLogTypeConverter에서 에외가 잡히면 MethodArgumentTypeMismatchException로 예외가 바뀌기 때문인데요! 

이유는 코코닥이 pr에서 잘 정리해주셨습니다!

또한 resolver로 수정하지 않고 converter로 가져가려는 이유는 루카가 pr에 남겨주신 의견과 같습니다.

string을 enum으로 바꿔주는것은 resolver보다 converter로 하였을때 그 역할일 더 잘 드러난다고 판단하였습니다.

또한 MethodArgumentTypeMismatchException를 잡아주는 함수를 따로 만든건 반환해주는 에러가 다르기 떄문입니다.

MethodArgumentTypeMismatchException로 잡았을때는 INVALID_REQUEST_BODY 가아닌

INVALID_REQUEST_PARAMETERS를 반환해주어야 하기때문에 함수를 따로 뺄수밖에 없는 상황입니다.

(handleTypeMismatchException에서 if 분기로 빼보았으나 코드가 꼴보기 싫어져서 함수로 뺐습니다..)

그럼 여기서 MethodArgumentTypeMismatchException로 잡힌 에러는 모두 INVALID_REQUEST_PARAMETERS로 반환해줘야 하는가?

네 일단 converter라는 애는 현재는 컨트롤러 매핑에서만 사용하며 이외의 상황에서는 어디서 추가로 사용될지 모르겠으나

당장은 문제가 없다고 판단합니다!

그렇게 생각하면 handleTypeMismatchException도 같은 상황이지 않을까요!?

2023-11-07 08:47 UTC, dooboocookie approved these changes
고생하셨어요 채채

제 생각에는 개선 여지가 조금 있을 것 같긴한데,
너무 큰 변경사항일 것 같아, 이 리뷰 저는여기서 어프루브 할게요.


생각한 개선점
1.  LetterLog 부모 클래스를 둘 수 있지 않을까?
2. LetterLogType은 완전 뷰에 관련된 값 아닌가? (도메인이 아닌것같음)

2023-11-07 08:53 UTC, chaewon121 reviewed
LetterLog 부모 클래스를 둘 수 있지 않을까?
-> 이건 더생각해봐야할것같아요 부모클래스도 생각해봤는데 둘이 완전히 같지 않고 onetoone,mantoone으로 다른부분도 존재해서 시도했을때 좀 머리아팠던 기억이있습니다!
추후 고민해보죠..!
LetterLogType은 완전 뷰에 관련된 값 아닌가? (도메인이 아닌것같음)
->저도 이부분에 대해서 어제 하루종일 고민했는데 전 도메인으로 생각이 가까워지더라구요. 물론 컨트롤러매핑때문에 생겨난 enum이지만 서비스나 도메인에서 해당 이넘을 사용할일이 (아직은 없지만 충분히 사용가능하다고 생각) 생길 수있어 컨트롤러에 한정적으로 두는것보다 도메인으로 둬도 크게 문제 없다는 생각이 들었어요. 더 확장성이 있다고 판단되어 도메인으로 두었고, 도메인으로 두어도 controller에서 사용할때 전혀 문제없다고 생각하여 굳이 presentation계층에 두지 않아도 되겠다는 생각이 들었습니다! 그래서 예외도 Letter예외로 던지는 것으로 수정되었구요..!

2023-11-08 01:17 UTC, merged