feat: 읽을 수 없는 쪽지 삭제
woowacourse-teams/2023-naaga pull request #559
Opened 2023-11-13 09:10 UTC by briandr97

## 📌 관련 이슈
- closed #558 

## 🛠️ 작업 내용
- [x] 받아온 모든 쪽지를 읽을 수 있는 쪽지로 보여줌
- [x] 쪽지 폴링 로직 변경 (내 위치를 잡으면 기다리지 않고 바로 요청할 수 있도록)

## 🎯 리뷰 포인트
쪽지 부분을 처음 만져봐서, 혹시 제가 놓친게 있는지 봐주시면 감사하겠습니다.
이번 이슈와 관계 없이 폴링 로직을 변경했는데 확인 한 번 부탁드립니다.

## ⏳ 작업 시간
추정 시간: 1h
실제 시간: 3h
이유: 폴링 로직을 다른 방식으로 변경하려고 도전해보다가 시간이 오래 걸렸습니다.

2023-11-14 08:07 UTC, hyunji1203 requested changes
빅스 고생많으셨어요!
바뀐 로직 너무 좋네요! 어제 오프라인 설명도 듣기도 해서 이해도 잘 했습니다!
나중에 진짜 시간만 되면 flow 도입해보고 싶네요ㅋㅋㅋ
자잘 리뷰 달아놨으니 확인해주시면 됩니다!
고생많으셨어요!

2023-11-14 08:07 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    private var _lastHint = MutableLiveData<Hint>()
[P3]
`val` 를 `var`로 바꾼 이유가 무엇인가요?

2023-11-16 01:54 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    private var _lastHint = MutableLiveData<Hint>()
없습니다. 저도 바뀐지 몰랐네욤! 감사합니다!

2023-11-16 01:54 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
> +    fun fetchLetters() {
감사합니다!

2023-11-16 01:57 UTC, hyunji1203 approved these changes
삑스 리뷰 반영한 거 화긴했습니다!
더이상은 수정할 부분 없는 것 같아 이만 어프로브할게요! 고생많았어요!!!!!!!!!!!!

2023-11-16 02:53 UTC, merged