feat: 플레이어 정보 조회 기능 구현
woowacourse-teams/2023-naaga pull request #563
Opened 2023-11-13 11:26 UTC by zillionme

## 📌 관련 이슈
- close: #560  

## 🛠️ 작업 내용
- [x] 플레이어 정보 조회 기능 구현
- [x] 플레이어 정보 조회 기능 테스트

## ⏳ 작업 시간
추정 시간:  1시간
실제 시간:   30분

2023-11-13 13:36 UTC, dooboocookie requested changes
빠른 적용 감사합니다.

컨벤션 지켜지지 않은 부분과
컨트롤러 클래스 다른 영역에 대해서 코멘트 남겼습니다~

2023-11-13 13:36 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/player/presentation/PlayerRankController.java
> +public class PlayerRankController {
P2: 

이 Controller를 따로 분리시킨 이유가 있으신가요??
제 생각엔 해당 컨트롤러는 속성이 플레이어 정보에 대한 내용이므로 하나의 컨트롤러로 둬도 될 것 같아요

2023-11-13 13:36 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/player/presentation/PlayerInfoController.java
> +
P2:

필요 없는 개행은 지워주세요

2023-11-13 13:36 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/player/presentation/PlayerInfoControllerTest.java
> +
P2:

필요없는 개행은 지워주세요

2023-11-13 13:36 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/player/presentation/PlayerInfoController.java
> +public class PlayerInfoController {
P2:

마찬가지로 따로 분리될 필요가 없는 컨트롤러 같습니다.

2023-11-13 13:36 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/player/presentation/PlayerInfoControllerTest.java
> +
P2:

필요 없는 개행은 지워주세요

2023-11-15 19:47 UTC, chaewon121 approved these changes
이레 고생했습니다!
컨트롤러 분리에 대한 의견은 전 나누는것도 좋다고 생각합니다. 가장 큰이유는 api의 시작이 다르기에 랭크 조회시 랭크 컨트롤러, pofile 조회시 info컨트롤러로 가는것도 가독성이 좋다고 생각해요. 루카가 남겨주신 의견대로 사실 합쳐도 그에따른 장점이 존재하고 분리해도 그에따른 장점이 있다고 생각하여 전 이레의 의견에 따르겠습니다! 아직은 프로필에 대한 더 api가 존재하지 않기때문에 굳이라는 생각이 든다는 루카의 의견에도 동의하고.. 크게 고민할 만큼의 장단점이 전 느껴지지 않네요! 또한 컨밴션은 루카가 남겨주셔서 이레가 잘 수정해서 머지할 것이라고 생각하기에 전 approve 하겠습니다!

2023-11-16 03:00 UTC, zillionme commented on backend/src/main/java/com/now/naaga/player/presentation/PlayerRankController.java
> +public class PlayerRankController {
루카의 의견에 동의합니다.

2023-11-16 03:08 UTC, zillionme commented on backend/src/main/java/com/now/naaga/player/presentation/PlayerInfoController.java
> +public class PlayerInfoController {
동의합니다

2023-11-16 05:06 UTC, kokodak requested changes
안녕하세요 이레 제 옆에 있지만 코멘트를 남겨봅니다

고생하셨고, 변경하면 좋을 것 같은거 남겼는데 확인 부탁드립니다 ㅎㅎ

2023-11-16 05:06 UTC, kokodak commented on backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
> +@RequestMapping("")
P3:

이 친구는 좀 쓸쓸해보이는데 보내주는게 어떨까요

2023-11-16 05:14 UTC, kokodak approved these changes
굿~

2023-11-16 05:47 UTC, dooboocookie approved these changes
컨벤션 관련 하나 남았는데 수정하고 머지해주세용

2023-11-16 05:47 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
> +
P2:

개행 지워주세요.

2023-11-16 06:18 UTC, merged