feat: 닉네임 변경 API 구현
woowacourse-teams/2023-naaga pull request #566
Opened 2023-11-14 06:22 UTC by dooboocookie

## 📌 관련 이슈
- closed: #562 

## 🛠️ 작업 내용
- [x] 닉네임 검증로직 추가
- [x] 닉네임 변경 기능 추가
- [x] 회원가입 시, OAuth에서 받아온 닉네임에 특수문자 포함되어있으면 제거하고, 20자 이상이면 자르는 로직 추가

## 🎯 리뷰 포인트
포인트 2가지
1. Nickname을 래핑해야할까요?
    - 일단 지금 Player에서 가지고 있는 Nickname에 대한 로직이 2가지 있습니다.
    - (1) 올바른 닉네임인지 검증한다.
    - (2) Oauth에서 받아온 닉네임 중 올바른 형태로 변환해서 새로운 Player를 만든다.
    - 근데, 래핑하지 않았습니다!
    - 일단 변경사항이 너무 커져서 래핑하지 않은 것인데요.
    - Nickname정도면 Player에서 관리해도 되지 않을까요?
2. 정규표현식
    - 제가 사용한 정규표현식이 두가지가 있는데요
    - `^.*[^가-힣a-zA-Z0-9\s]+.*$`
      - 제일 처음에 오는 `^` 문자열의 시작이라는 의미
      - `.`는 모든 문자를 의미
      - `*` 직전 문자가 0~여러번 오냐
      - `[ ]` 안에 문자의 k 의미
      - `^` []안에 문자의 부정(반대)를 의미
      - `가-힣` 한글의 첫문자 가부터 한글의 끝문자 힣까지를 의미
      - `a-z`영어소문자 a부터 z까지를 의미
      - `A-Z`영어대문자 A부터 Z까지를 의미
      - `0-9`숫자 0부터 9까지를 의미
      - `\s` 공백문자를 의미
      - `+` 직전 문자가 1개부터 여러개를 의미
      - 제일 마지막에 오는 `$` 문자열의 끝이라는 의미
      - 모든 문자가 0~여러개로 시작해서 `한글, 영어 소문자, 대문자, 숫자, 공백이 아닌 문자가 1개 이상 포함되어있고` 모든 문자가0~여러개로 끝나는 문자일 때 라는 뜻입니다
    - `^[가-힣a-zA-Z0-9\s]+$`
      - 이는 위랑 비교해서 보면
      - `한글, 영어 소문자, 대문자, 숫자, 공백 으로 시작해서 1개 이상 포함되고 끝난다.` 라는 의미겠죠?

## ⏳ 작업 시간
추정 시간:  2시간
실제 시간:  3시간
이유: 생각보다 고민 지점이 조금 있었네용

2023-11-15 18:45 UTC, zillionme requested changes
몇가지 수정점에 대해서 리뷰를 남겼지만 크게 바뀌어야할 코드는 아닌 것 같아서 approve 드리려고 했는데 잘못눌러서 rc가 되었네요.
그리고 nickname에 관해서는 nickname의 책임인 메서드들이 많아서 nickname 객체를 따로 두는 것이 객체지향적으로는 맞지만.
player이 크게 변경 되지 않을 거고 수정점이 더 많아지기 때문에, 저는 이대로 가는 것도 좋다고 생각합니다.


+) 루카의 정규표현식 설명 짱!
> 모든 문자가 0-여러개로 시작해서 한글, 영어 소문자, 대문자, 숫자, 공백이 아닌 문자가 1개 이상 포함되어있고 모든 문자가0-여러개로 끝나는 문자일 때 라는 뜻입니다

2023-11-15 18:45 UTC, zillionme commented on backend/src/main/java/com/now/naaga/player/domain/Player.java
> +            return modifiedNickname.substring(0, NICKNAME_MAX_SIZE);
생성 될 때, 플레이어 닉네임이 어떻든 무조건 플레이어를 생성 및 데이터베이스에 저장하기 위해
올바르게 변경된 닉네임이 20자 이상이면 20자까지 자르는 거군요

2023-11-15 18:45 UTC, zillionme commented on backend/src/main/java/com/now/naaga/player/domain/Player.java
> +        final boolean isUnavailableNickname = Pattern.matches("^.*[^가-힣a-zA-Z0-9\\s]+.*$", nickname);
P3:
<img width="706" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/100172683/e74e178c-fe7a-47ff-a669-d7e5b4200b47">

Pattern.matches() 메서드는 내부적으로 패턴을 컴파일하고 매칭을 수행하기 때문에 반복 호출 시에 매번 패턴을 컴파일한다고 합니다.
따라서 미리 컴파일한 정적 Pattern객체를 만들고, static상수로 재사용하는 것은 어떨까요?
```suggestion
       final static Pattern PATTERN = Pattern.compile("^.*[^가-힣a-zA-Z0-9\\s]+.*$"); // 상수
       
       ...
       
         final boolean isUnavailableNickname = pattern.matcher(nickname).find();
```

2023-11-15 18:45 UTC, zillionme commented on backend/src/main/java/com/now/naaga/player/domain/Player.java
> +    private static String modifyWithValidNickname(final String nickname) {
P3:
modifyToValidNickname
(유효한 닉네임으로 변환한다) 어떤가요?

2023-11-15 18:45 UTC, zillionme commented on backend/src/test/java/com/now/naaga/player/domain/PlayerTest.java
> +                "루카20살",
unavailable로 옮겨주세요

2023-11-15 18:45 UTC, zillionme commented on backend/src/test/java/com/now/naaga/player/domain/PlayerTest.java
> +    @MethodSource("availableNicknames")
테스트 짱👍🏻👍🏻

2023-11-16 02:01 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/player/domain/PlayerTest.java
> +                "루카20살",
스물열살ㅎㅎ

2023-11-16 02:03 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/player/domain/Player.java
> +            return modifiedNickname.substring(0, NICKNAME_MAX_SIZE);
맞아용.
저희 서비스 요구사항 상, 회원이 첫 로그인하면 바로 회원가입 처리가 되기 때문에 회원이 직접 닉네임변경을 하지 않는 이상 카카오톡에서 받은 닉네임을 써야합니다

2023-11-16 02:03 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/player/domain/Player.java
> +    private static String modifyWithValidNickname(final String nickname) {
변경하겠습니다

2023-11-16 02:42 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/player/domain/Player.java
> +        final boolean isUnavailableNickname = Pattern.matches("^.*[^가-힣a-zA-Z0-9\\s]+.*$", nickname);
그렇네요.
Pattern에 명시가 되어있는 내용이네요.
근데 pattern.matcher()를 해도 Matcher라는 비교하는 객체를 생성하네요. 제 생각엔 크게 차이는 없을 것 같기는 하나, 정규표현식을 포함해서 상수화 해놓는게 나을 것 같아서 적용했습니다!!

2023-11-16 02:42 UTC, dooboocookie reviewed
안녕하세요 이레, 리뷰 남겨주신 내용 처리하였습니다!!

2023-11-16 05:32 UTC, kokodak requested changes
고생하셨습니다 루카

정규표현식으로 닉네임 검증하는 거 좋네요 ㅎㅎ

원시값 포장의 경우, 스스로 검증해야할 로직이 있다면 전 포장하는 편이긴 해요.

> Nickname정도면 Player에서 관리해도 되지 않을까요?

물론 이것도 좋다고는 생각하지만, 추후에라도 원시값 포장을 하는게 나을 것 같다고 생각합니다.

전체적으로 잘 짜주신 것 같고, 간단한 의견 두가지 정도 남겨서 RC 를 남겨봅니다.

근데 불필요하다 생각되시면 그냥 Approve 라고 생각해주세요!

2023-11-16 05:32 UTC, kokodak commented on backend/src/main/java/com/now/naaga/player/application/PlayerService.java
> +        final Player player = playerRepository.findById(playerId).orElseThrow(() -> new PlayerException(PLAYER_NOT_FOUND));
P3:

코드가 중복되는 듯한데, `findPlayerById()` 메서드를 재활용해도 괜찮지 않을깝쇼?

2023-11-16 05:32 UTC, kokodak commented on backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java
> +    }
P3:

예외 검증을 좀 더 상세하게 하면 좋을 것 같아요

2023-11-16 06:12 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java
> +    }
적용했어용~

2023-11-16 06:12 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/player/application/PlayerService.java
> +        final Player player = playerRepository.findById(playerId).orElseThrow(() -> new PlayerException(PLAYER_NOT_FOUND));
적용했어용~~

2023-11-16 06:13 UTC, dooboocookie commented
안녕하세요 여러분?
남겨주신 내용 전부 적용하였습니다~~

2023-11-16 06:20 UTC, kokodak approved these changes
굿 고생하셨습니다

2023-11-16 06:24 UTC, zillionme approved these changes
루카 짱

2023-11-16 06:28 UTC, merged