feat: 좋아요 수 집계에 대한 동시성 문제 해결
woowacourse-teams/2023-naaga pull request #567
Opened 2023-11-14 07:12 UTC by kokodak

## 📌 관련 이슈
- close: #561 

## 🛠️ 작업 내용
- [x] 좋아요 수 집계에 대한 갱신 유실 문제 해결

## 🎯 리뷰 포인트

## 기존의 문제

두명 이상의 사용자가 같은 장소에 대한 좋아요 상태를 `동시에 변경`시, 이에 대한 좋아요 수 집계에 대해 `갱신 유실 문제`가 발생합니다. 따라서, 좋아요 집계 수가 정확하게 동작하지 않는 문제가 존재했습니다.

## 해결 방법

장소 통계에 대한 동시성 발생 시나리오는 뎁스가 꽤 있는 편입니다.

1. 같은 장소에 선정되어야한다.
2. 비슷한 시간대에 게임 결과창으로 진입해야한다.
3. 동시간대에 좋아요 버튼을 눌러야한다.

따라서, 비교적 트랜잭션 충돌의 빈도가 낮은 시나리오라고 생각하였고, 이에 기반해서 낙관적 락을 사용하도록 했습니다.

또한, 동시성으로 인한 낙관적 락 예외 발생시, 예외를 바로 클라이언트에 내려주는 것보다는 서버에서 로직을 재시도해서 성공한 요청으로 만들어주는 것이 좋다고 생각했습니다.

이를 구현하기 위해 서비스 상위 계층을 도입했고, 이름을 퍼사드(Facade) 라고 붙였습니다.

서비스에서는 최대한 비즈니스 로직만 담기 위해서, 재시도 로직은 퍼사드 클래스 안에 두었습니다.

## ⏳ 작업 시간
추정 시간:   4시간
실제 시간:   8시간

2023-11-15 14:54 UTC, dooboocookie requested changes
꼬꼬닷쿠. 이번에도 멋있는 고민과 구현을 해주셨군요...

동시성에 대해서 고민을 하다보니,
락, 트랜잭션, 패턴, 도메인 제약조건, ... 참 고민할게 많네요.
리뷰하면서 여러가지 의문점들이 많이 떠오르더라구요.

일단 코코닥 PR에서 언급할만한 부분들은 다 언급을 하였고,
P2 레벨이 2군데 정도 있어서 RC일단 날립니다.

그리고 이미 오프라인으로 나눴던 얘기지만 다른 팀원도 고려해보면 좋을 것 같아서 남겨봐요.
> 꼭 이것을 동시성으로 해결해야할까?
동시성을 고려하지 않고 +1, -1을 하다가, 특정 시간마다 정합성을 맞추는 작업을 하면되지 않을까?

2023-11-15 14:54 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/like/application/PlaceLikeFacadeTest.java
> +        countDownLatch.await();
이런 훌륭한 방법의 테스트가 존재한다니요!!
대단한데요?

근데 제가 이해한게 맞는지 체크 좀 해주세요.

- CountDownLatch.countDown(); Latch의 숫자를 하나씩 내린다 
- Latch를 쓰레드 숫자와 같이 둔다.
- 지금 다른 쓰레드에 비동기적으로 로직이 끝나면 카운트를 내린다.
- CountDownLatch.await()은 Latch가 0이 될 떄까지 기다린다.
- 즉 131라인을 통과한다는 것은 20번의 쓰레드가 다 종료되었을 때이다.

맞나요?

2023-11-15 14:54 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/like/application/PlaceLikeFacadeTest.java
> +        countDownLatch.await();
P4:

근데 뭔가 127라인 로직이 실행되는 속도가 for문이 다음으로 넘어가는 속도보다 훨씬 느릴것 같긴한데, 이게 동시성을 처리해준다는 보장이 될까요?
(사실 될것같긴해요.. 속도차이가 좀 심할것같은데)
지금은 Facade를 테스트하는것이니, Service를 모킹한다음에, Facade에 모킹한 애를 주입해주는 것은 어떨까요?
모킹한 Service에는 쓰레드를 일정시간동안 재우고, 몇번 동시성 예외를 터뜨린다. 이런식으로 만들어놓으면 어떨까요??

2023-11-15 14:54 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/like/application/PlaceLikeFacadeTest.java
> +        for (int i = 2; i <= threadCnt + 1; i++) {
P2: 

어차피 검증에서 Repository를 사용하자나요.
i를 쓰지않고 플레이어를 전부 조회해서 해당 플레이어 리스트를 순회하면서 테스트하는 것은 어떨까요??
i가 2번부터 안생길 수도 있자나요. (상황에 따라선)

2023-11-15 17:56 UTC, zillionme requested changes
코코닷쿠... 짱...
동시성 테스트도 짱이네여
placeLikeService를 래핑하는 클래스로, 낙관적 락의 오류 발생시 placeLikeService의 메서드를 파사드 클래스의 로직대로 해결하려고 파사드 패턴을 사용하신 것 같은데 맞나요?

궁금한 점은 낙관적 락의 오류처리를 하는 것이 placeLikeService 상위 클래스의 책임일까요?

2023-11-15 17:56 UTC, zillionme commented on backend/src/main/java/com/now/naaga/like/presentation/PlaceLikeController.java
>  public class PlaceLikeController {
P5:
`PlaceLikeController`에서 `PlaceLikeFacade`와 `PlaceLikeService`을 의존하고
`PlaceLikeFacade`에서 `PlaceLikeService`을 의존하고 있는데.
파사드 패턴을 사용하신 이유가 뭔가요?

1. 함수형 인터페이스를 만든다 
2. 구현한다 (매개변수로 함수형 인터페이스를 받고, 동시성 문제가 발생하지 않을 때까지 while문)을 돈다
3. `PlaceLikeService`의 applyLike와 cancelLike가 해당 인터페이스를 사용한다
와 같은 방식으로도 충분히 해결할 수 있을 것 같아서요.

낙관적 락의 문제를 해결하는 것은 `PlaceLikeService`의 역할이 아니라고 판단했기 때문인가요?

2023-11-15 17:56 UTC, zillionme commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeFacade.java
> +}
P5 :
`applyLike` 메서드와 `cancelLike` 메서드의 코드가 중복된다는 생각이 들었습니다.
함수형 인터페이스를 사용해보는 건 어떨까요?

파사드 패턴을 조금 검색해봤는데, 하위 클래스들이 공통된 로직을 갖고 있고, 해당 로직은 인터페이스화 한 뒤에, 파사드 클래스에서 사용하는 것 같아서요.(잘못 이해했으면 패스~)

2023-11-15 17:56 UTC, zillionme commented on backend/src/test/java/com/now/naaga/like/application/PlaceLikeFacadeTest.java
> +                  () -> assertThat(actualPlaceStatistics.getLikeCount()).isEqualTo(threadCnt));
P4:
이 부분에서 실제로 동시성 문제가 발생했다는 건 어떻게 알 수 있나요?
실제로 OptimisticLockingFailureException가 발생했는지 알 수 있는 코드인가요?

2023-11-15 17:56 UTC, zillionme commented on backend/src/test/java/com/now/naaga/like/application/PlaceLikeFacadeTest.java
> +        for (int i = 2; i <= threadCnt + 1; i++) {
루카의 말은 cancel의 경우 어차피 place와 playerid로 좋아요를 조회해 오는데, 조회 결과가 null일 경우 무시하기 때문인가요?
id =1 인 플레이어의 좋아요는 없을테고, 따라서 해당 무시가 될테니까요.

> id가 2번부터 안생길 수도 있자나요. (상황에 따라선)


가 무슨 말인지 모르겠네용

2023-11-15 19:34 UTC, chaewon121 requested changes
코코닥! 고민을 많이한 흔적이 보이네요 덕분에 락에 대해서 좀 공부가 되었습니다! 고생 많으셨네요
가장 궁금한것은 update쿼리문을 사용한 동시성문제 해결인데요..! 일단 영속성 컨테스트에 대한 이해도가 완벽한 상태가 아닌지라 해당 의견에 대해서 코코닥과 논의해보고 싶어서 의견 남겼습니다!

2023-11-15 19:34 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/like/application/PlaceLikeFacade.java
> +                log.info("낙관적 락 재시도 횟수: {}", retryCnt);
p4: 
저는 재시도 한 것에 대한 로깅 찬성입니다. 일반적인 상황이 아니고, 동시성이 발생한 상황이기 때문에 개발자가 재시도가 일어난 상황을 알아야한다고 생각합니다. 하지만 해당 상황은 물론 개발자가 의도적으로 잡아준 애러이긴하나, 일반적으로 발생하는 문제가 아니기 때문에 warn레벨이라고 생각합니다! 코코닥 의견은 어떠신가요?

2023-11-16 06:18 UTC, kokodak commented on backend/src/test/java/com/now/naaga/like/application/PlaceLikeFacadeTest.java
> +        countDownLatch.await();
> 근데 뭔가 127라인 로직이 실행되는 속도가 for문이 다음으로 넘어가는 속도보다 훨씬 느릴것 같긴한데, 이게 동시성을 처리해준다는 보장이 될까요?
(사실 될것같긴해요.. 속도차이가 좀 심할것같은데)

동시성 테스트 환경을 구성하는 것중 제일 중요한 점은, `여러 스레드가 동시에 타겟 메서드로 진입하게 만든다` 라는 점인 것 같아요.

각 스레드 별 타겟 메서드 진입 시점의 간격은 for문이 다음으로 넘어가는 매우 짧은 찰나의 시간과 같을거구요. 이 간격은 제 로컬 기준에서 약 `0.00002초` 정도 됩니다. 이정도의 간격은 동시성이 충분히 발생할 수 있는 시간인 것 같아요.

그래서 제 답은, `동시성이 발생하는 환경이 보장된다` 입니다.

> 지금은 Facade를 테스트하는것이니, Service를 모킹한다음에, Facade에 모킹한 애를 주입해주는 것은 어떨까요?
모킹한 Service에는 쓰레드를 일정시간동안 재우고, 몇번 동시성 예외를 터뜨린다. 이런식으로 만들어놓으면 어떨까요??

일단 전 Facade 계층을 슬라이스 테스트하려고 한게 아닌, 실제 동시성 환경을 최대한 똑같이 재현해서 테스트를 하려고 했습니다.

이 과정에서 만약 Service 를 모킹한다면 DB 를 거치지 않을텐데, 그렇다면 과연 제가 의도한대로 동시성 제어가 잘 되는지 확인할 방법이 있을까요? 일단 전 동시성 관련 테스트에서는 DB 를 찍고 오는 실제 테스트를 하는 것이 굉장히 중요하다고 생각합니다.

2023-11-16 06:42 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
<img width="740" alt="image" src="https://github.com/woowacourse-teams/2023-naaga/assets/79090478/f03954ea-e3a2-4fae-9ab5-5148e4f84905">


(출처: https://hudi.blog/jpa-concurrency-control-optimistic-lock-and-pessimistic-lock/)

만약 해당 로직이 동시성을 많이 일으킨다는 기대가 있어서 도메인 로직을 Repository로 이동시킨다면, 
비관적 락으로도 해결할 수 있지 않을까요?

2023-11-16 06:56 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
일단 저는 해당 로직이 동시성을 일으키는 일이 많지 않아서 락을 최소화 하고 싶은 입장입니다.
루카 의견은 애초에 장소정보 조회시 비관적락을 걸자는 말씀일까요??

2023-11-16 06:59 UTC, kokodak commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
매우 좋은 방법이라고 생각하고, 일단 제 의견을 정리해서 달도록 하겠습니다. 성능 측정이 필요해보여서, 종합적으로 검토하고 알려드릴게요!

2023-11-16 07:21 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
pr에 남김 영속성 컨테스트 문제에 관해서 더 찾아보았는데요
@Modifying을 사용할 시 clearAutomatically = true 를 걸어 영속성 컨테스트를 초기화 한다고 합니다
그럼 PlaceStatistics와 관련없는 엔티티에 대해서는 데이터베이스에 반영되지 않을 위험성이 생긴다고 하네요
그래서 flushAutomatically = true 쿼리 실행 전 쓰기 지연 저장소의 쿼리를 flush 하는 옵션을 달아주어 해당 문제를 해결할 수 있다고 합니다 그래서 @Modifying 시에
```
@Modifying(clearAutomatically = true, flushAutomatically = true)
    @Query("UPDATE PlaceStatistics ps SET ps.likeCount = ps.likeCount + 1 WHERE ps.place.id = :placeId")
    void updateLikeCount(@Param("placeId") Long placeId);
```
이렇게 조건을 달아주어 쿼리 실행전 영속성 컨테스트를 모두실행한다. 쿼리 실행 후 영속성 컨텍스트를 비워준다.
로 해서 캐시문제는 해결될것같아요!
참고블로그
https://velog.io/@gruzzimo/JPA-Modifying%EC%9D%98-flushAutomatically-%EC%98%B5%EC%85%98%EC%9D%80-%EC%96%B8%EC%A0%9C-%EC%93%B0%EC%A7%80
다만 이것에 대한 조사를 하다보니 수정 쿼리를 사용할 시 flush를 더 자주해줘야하기때문에 이것만의 성능저하도 일어날 수 잇을것 같다는 생각이 드네요

2023-11-16 07:35 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
옷 성능측정을 해주신다니 부탁합니다 코닥

2023-11-17 00:42 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
코코닥이 잘 정리하고 있어서 그 답변을 기다리면서 제 생각을 밝혀보자면, 저는 개인적으로 비관적 락과 update문은 거의 비슷한 상황이라고 생각합니다.
비관적 락을 걸고 DB에서 find를 해오면, `SELECT ... FOR UPDATE`로 조회를 해오기 때문에 해당 레코드의 X락이 걸립니다.
마찬가지로 UPDATE문을 직접 작성해서 @Modifying으로 클리어를 해도 그때 `UPDATE`문이 디비에 날라가기 떄문에 해당 레코드의 X락이 걸립니다.
두 경우 다 `X락 걸리는 시점 <-> 트랜잭션 종료` 사이에 텀이 존재할 수 있다는 점이 있는데, 이것은 저희 비즈니스 로직상 매우 찰나이고, 해당 부분에 X락이 걸린다고 해도 현재로서는 좋아요 밖에 `place_statistics`에 접근하는 내용이 없기 때문에, 문제 없을 것 같습니다!!
그래서 저는 채채가 제시해주신 UPDATE 하는 방법이 낙관적 락보다 좋다고 생각하는데요!!
그렇다면 더 `비즈니스 로직이 짧다고 상황을 낙관적으로 봐서` 비관적 락으로 `SELECT .. FOR UPDATE` 해와서 도메인 로직을 안전하게 어플리케이션에서 돌리고(좋아요는 음수가 될 수 없다 등) DB에 flush하면서 커밋 쳐버리는것이 괜찮을 것 같은데요 채채는 어떻게 생각하시나요.

2023-11-17 01:44 UTC, dooboocookie commented on backend/src/test/java/com/now/naaga/like/application/PlaceLikeFacadeTest.java
> +        countDownLatch.await();
그쵸. 제 생각에도 보장만 된다면 슬라이스 테스트보다는 통합 테스트가 나은 것 같아요.

제 관점은 Service 로직에 대한 (DB에 들리는)통합테스트를 하는 것이 좀 더, 낙관적 락이 걸렸다라는 테스트에 가깝지 않을까요?
만약 Service 로직에서 낙관적 락 에러가 터진다는 테스가 작성이 되었다면,
Facade에서 모킹한 서비스가 동시에 낙관적 락 예외를 터질 때, 재시도를 지속적으로 해서 모두 처리한다.로 할 수 있지 않을까라는 관점이였습니다.

근데, 일단 Facade와 Service자체를 의존도를 높게 설계되어있기 때문에 이런 낙관적 락에 대한 테스트를 파사드에 둬도 괜찮을 것 같아요

2023-11-17 05:34 UTC, chaewon121 commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
아하 저는 find해오는 행위 자체에 비관적락을 걸자는 말인줄 알았어요! 그럼 좋아요수를 수정하는것이아닌 단순조회만 할때도 비관적락이 걸리지 않을까 생각해서 많이 반대 라고 말했던것입니다! 비관적락으로 SELECT .. FOR UPDATE 한다는게 무슨말인지 잘이해를 못했는데 설명해주실수있나요!?

2023-11-17 07:44 UTC, kokodak commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
좋은 방법 제시 감사합니다 채채!!

이 리뷰를 보고 정말 많은 고민을 했는데요. 사실 채채가 제시한 방법이 너무 좋은 방법이라고 생각되네요. 전 이걸 생각하지 못했거든요.. 일단 제가 한 고민들 그리고 제 의견을 밑에 남겨둘게요.

## `도메인 로직을 통한 변경감지 UPDATE` vs `Repository UPDATE`

저는 전자가 좋다고 생각합니다. 그에 대한 근거는 아래와 같아요.

1. 좋아요 관련 비즈니스 로직 및 제약조건(좋아요 수는 음수일 수 없다 등)을 DB 쿼리 기반으로 풀어내는 것보다는, 애플리케이션 단에서 도메인 로직으로 풀어내는 것이 좋을 것 같다.
2. `@Modifying` 을 이용한 직접적인 UPDATE 쿼리의 경우, 벌크 연산이 필요한 경우에는 확실한 성능 이점이 있기 때문에 고려해볼만하지만, 단건 UPDATE 쿼리 경우에는 1번의 이유로 변경감지를 통한 UPDATE 를 사용하는 것이 좋아보인다.

요약해보자면, 현재의 상황에서는 간단한 수준의 단건 UPDATE 쿼리가 사용됩니다.

이는 도메인 로직을 통한 변경감지 기능으로도 충분히 커버할 수 있고, 확장성이나 개발자 가독성 측면에서도 도메인 로직을 통한 로직 전개가 좋아보입니다.

따라서, 저는 현 상황에서는 Repository 를 통한 쿼리 직접 실행보다 도메인 로직을 전개하는 방향을 선택할 것 같아요.

## `비관적 락`인가, `낙관적 락`인가?

기존에 제가 적용했던 `낙관적 락 + 재시도 로직의 도입 근거`는 PR 본문에도 나와있듯이, `트랜잭션 충돌 가능성이 낮다` 라는 전제였습니다.

때문에 레코드 락에 의한 사이드 이펙트를 최대한 줄이기 위해서, 레코드 락을 애초에 걸지 않는 대신 트랜잭션 커밋 직전에 버전 정보 비교를 통해 트랜잭션 충돌 여부를 파악하는 구조를 선택했습니다.

다만, 채채의 리뷰를 보면서 `정말 낙관적 락일까?` 라는 질문을 스스로에게 해봤는데요. 이 생각이 들었던 근거는, 채채가 간단한 UPDATE 쿼리 하나로도 현재의 동시성 문제를 잘 풀어낼 수 있다는 점을 시사해주었기 때문입니다.

비관 락과 낙관 락의 본질적인 차이는, `엔티티 조회 시에 X락을 획득하는가?` 입니다. 이 차이는 정말 중요한 성능 차이를 불러올 수 있기 때문에 잘 고민해봐야하는데요. 현 상황에서 비관 락과 낙관 락의 차이점은 아래와 같아요.

![image](https://github.com/woowacourse-teams/2023-naaga/assets/45879491/e44ec604-2801-4f16-aacb-ab25fc1a5ede)

위 도식도에서 알 수 있듯이, X락의 범위는 비관적 락을 적용했을 때가 더 큽니다. 다만, 여기서 주목해볼만한 점은, X락 범위 차이에서 발생하는 연산이 굉장히 가벼운 수준의 연산이라는 점이에요.

트랜잭션 충돌이 나지 않는 경우에, 비관적 락에서 X락 범위 차이로 인해 발생하는 시간은 약 0.03초(제 로컬기준) 정도로 측정됐어요. 즉, 비관적 락이 낙관적 락보다 추가로 X락을 잡고 있는 시간이 0.03초 정도라는 얘기입니다.

이는 정말 찰나의 시간이라고 생각되고, 현 운영 서버 환경에서 이 시간적 차이가 사용자의 경험성이 바뀔 정도로 크다! 는 아니라고 생각해요.

따라서 제가 결론적으로 주장하고 싶었던 얘기는, 현재 저희 로직의 특성상, 좋아요 수 수정 로직의 복잡도가 매우 낮습니다.

이에 따라 X락이 잡히는 테이블 범위가 충분히 작고, 추가적으로 X락을 잡고 있는 시간 또한 정말 찰나의 시간이라 판단되기 때문에, 아래와 같은 결론에 도달했습니다.

- 평상 시 시나리오 대로 트랜잭션 충돌이 적을 경우에, 낙관적 락과 비관적 락 사이에서 유의미한 성능 차이를 찾을 수 없었다.
- 낮은 확률로 다수의 트랜잭션 충돌 시, 한개의 트랜잭션만 성공하고 나머지의 모든 트랜잭션은 실패하기 때문에, `트랜잭션 재시도에 의한 성능 저하 폭`이 `비관적 락에 의한 성능 저하 폭`보다 크다.
    - 근거: 동일한 환경에서 테스트 10회 반복했을 때의 성능 차이
        - 트랜잭션 50개 충돌인 경우, 낙관적 락 + 재시도 → 처리 속도 약 970 ~ 980ms
        - 트랜잭션 50개 충돌인 경우, 비관적 락 → 처리 속도 약 690 ~ 720ms
- 낙관적 락 + 재시도 로직을 구현할 경우, 비관적 락의 경우보다 코드 복잡도가 올라간다.
- **결론: 낙관적 락 대신 비관적 락을 사용해서 동시성 처리를 진행한다.**

## 최종 의견

위 근거들을 종합해서 제 의견을 정리해보자면..

`도메인 로직 실행을 통한 변경감지를 이용해 UPDATE 쿼리를 발생시키고, 동시성 제어는 낙관적 락이 아닌 비관적 락을 통해 진행한다.`

입니다.

2023-11-17 08:37 UTC, kokodak commented
다들 리뷰 남겨주셔서 감사합니다!! 전반적인 팀의 의견을 보았고, 이에 대해 제 최종 의견을 정리해서 [이 코멘트](https://github.com/woowacourse-teams/2023-naaga/pull/567#discussion_r1396815470)에 남겨두었습니다. 확인해주시면 감사하겠습니다 !!

2023-11-17 16:23 UTC, dooboocookie commented on backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
> +    Optional<PlaceStatistics> findByPlaceIdWithOptimisticLock(@Param("placeId") final Long placeId);
P5:

코코닥 혹시 근데 트랜잭션 50개로 테스트한 이유가 있을까요? (시비 아님)
저희 쓰레드풀 설정값이 20개고, 현재 유저 수나 시나리오 상으로 50개는 근처도 안갈거같긴한뎅
유의미한 결과값을 찾기 위한 값이였나용?

2023-11-17 16:25 UTC, dooboocookie approved these changes
진짜 찐한 고민 오랜만에 했네요!
늘 이렇게 깊은 고민 해주는 코코닥에게 박수를 드리고,
리뷰 열심히 해준 채채, 이레에게도 박수를 드립니다!!
감사합니다 덕분에 좋은 고민 많이하고 좋은 결과 나온 것 같아요

2023-11-20 04:25 UTC, merged