Feat/#57
woowacourse-teams/2023-naaga pull request #58
Opened 2023-07-23 17:54 UTC by briandr97

## 📌 관련 이슈
- closed: #57 

## 🛠️ 작업 내용
- [x] IN_PROGRESS 상태의 모험이 있는지 서버에 요청한다.
- [x] IN_PROGRESS인 모험이 있다면 해당 모험을 OnAdventureActivity로 보내며 화면을 전환한다.
- [x] IN_PROGRESS인 모험이 없다면 BeginAdventureActivity로 화면을 전환한다.

## 🎯 리뷰 포인트
- 스플래시 화면을 저도 제대로 처음 만들어봐서 이상하고 미숙할 수 있습니다. 사실 아직 완전히 이해하진 못한 것 같습니다.
- OnAdventureActivity에서 두 가지 경우에 따라 분기하는 부분 봐주시면 좋을 것 같습니다.

## ⏳ 작업 시간
추정 시간:   1h
실제 시간:   2h
이유: 안드로이드 12부터 적용된 스플래시 api를 어떻게 써야하는건지 잘 모르겠다.

2023-07-27 05:18 UTC, krrong approved these changes
스플래시 어려웠을 것 같은데 구현을 잘해줘서 좋네요.
덕분에 쉽게 공부했어요 🙃

프로젝트를 진행하면서 추후에 고민해야될 점들을 제외하고는 고칠 부분이 없어보어요

2023-07-27 05:21 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
>                  LocationPermissionDialog().show(supportFragmentManager, "location")
location을 상수로 관리하는건 어떤가요?

2023-07-27 05:23 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
>              viewModel.beginAdventure(Coordinate(lastLocation.latitude, lastLocation.longitude))
지난번에 레아가 이런 방식은 위험하다고 했던 기억이 있는데 이 부분도 어떻게 개선하면 좋을지 함께 생각해보면 좋을 것 같아요.

2023-07-27 05:41 UTC, briandr97 commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
> +        )
동반 객체로 분리하는 부분 좋습니다.
다만 두 번째 문단에서 오해가 있었던 것 같습니다.
해당 코드는 오류 처리 부분이 아니라 "빠르게 실패하기"를 선택한 것은 아닙니다.

해당 코드는 서버에서 "진행중"인 게임이 있는지 받아오고 해당 리스트가 비어있을 때, 즉 "진행중"인 게임이 없을 때 "ERROR" 상태의 모험을 생성하는 것입니다.
모험의 상태를 통해 진행 중인 게임의 유무를 판단하고 넘어갈 다음 화면을 액티비티에서 정합니다.

사실 그래서 "ERROR"보다 "NONE"과 같은 네이밍이 더 좋을 것 같다고 생각이 들긴 합니다!

2023-07-27 13:01 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
> +        )
어떤 의미로 구현한지 이해했어요!
빅스가 이야기한대로 네이밍을 수정하는 것이 더 좋을 것 같네요ㅎㅎ 🙃

2023-07-27 20:56 UTC, hyunji1203 requested changes
빅스 정말 고생많았어요!
저도 새로 변경 된 splash 구현 방법에 대해서 익숙하지 못해, 해당 부분에 빅스가 원하는 리뷰를 다 드리지 못한 것 같아 아쉽네요🥲 그리고 미리 달려있던 리뷰와 최대한 중복되지 않도록 리뷰 남겼습니다!

2023-07-27 20:56 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
> +            DONE -> Intent(this, BeginAdventureActivity::class.java)
`ERROR`와 `DONE` 분기에서 사용 된 `BeginAdventureActivity`의 Intent 생성도 위의 `IN_PROGRESS` 분기처럼 해당 액티비티 내의 intent 생성 함수를 통해 가져오면 좋을 것 같아요~

2023-07-27 20:56 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
> +    val adventure: LiveData<Adventure> get() = _adventure
빅스가 알려준 대로 `get`문구 없이  `val adventure: LiveData<Adventure> = _adventure` 이렇게 수정해보면 어떨까요?

2023-07-27 20:56 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
> +                .onFailure { }
통신에 실패했을 때에 대한 처리를 어떤 식으로 할 지 나중에 같이 고민해봅시다!

2023-07-28 08:05 UTC, hyunji1203 approved these changes

2023-07-28 08:19 UTC, merged