[AN] feat: registerForActivityResult 분기처리 기능 구현
woowacourse-teams/2023-naaga pull request #72
Opened 2023-07-26 15:22 UTC by briandr97

## 📌 관련 이슈
- closed: #61 

## 🛠️ 작업 내용
- [x] 유저의 권한 요청 응답을 토스트 메시지로 다시 알려준다.
- [x] Dialog 내에서 대략적인 위치 권한이 있을 시와 전혀 없을 시를 구분하여 문구를 바꿔준다.
- [x] BeginAdventureActivity 코드 정리

## 🎯 리뷰 포인트
현재 기획대로 구현 완료하였습니다.
다만 구현하면서 또 한 가지의 변경이 필요하다는 생각이 들었습니다.

스플래시에서 게임 중인지 아닌 지를 구분하여 바로 게임 화면으로 보내는 경우가 존재하기 때문에
BeginAdventureActivity를 거치지 않고 앱이 실행될 수 있습니다.

만일 유저가 처음에 권한을 허용하고 게임을 진행하다 앱을 종료하고 앱의 권한을 삭제하면
다시 접속 시 바로 게임 화면으로 넘어가지만 유저의 현재 위치를 잡지 못하는 경우가 발생합니다.

그래서 다른 곳으로 넘어가기 전에 스플래시에서 모든 걸 처리하거나
인 게임 화면에서도 권한 체크를 하는 등의 조치가 필요할 것 같습니다.

## ⏳ 작업 시간
추정 시간: 1h
실제 시간: 2h

분기 처리를 어디서 할 지에 대해 고민하느라 시간이 생각보다 오래 걸렸다.

2023-07-27 13:29 UTC, krrong requested changes
> 그래서 다른 곳으로 넘어가기 전에 스플래시에서 모든 걸 처리하거나
인 게임 화면에서도 권한 체크를 하는 등의 조치가 필요할 것 같습니다.

빅스의 의견에 동의해요. 
그렇다면 첫 화면에서 위치 권한을 요청하도록 바꿔볼까요?

2023-07-27 13:29 UTC, krrong commented on android/app/src/main/res/values/strings.xml
> +    <string name="locationDialog_approximate_description">대략적인 위치 권한만 허용되었어요\n나아가 서비스를 이용하기 위해서는\n정확한 위치에 엑세스할 권한을\n부여해주셔야 해요</string>
읽다보니까 생각난건데 
> 정확한 위치에 액세스할 권한을 부여해주셔야 해요

보다
> 정확한 위치 권한을 부여해주셔야 해요 

로 바꾸는건 어떨까요?

만약 바꾼다면 locationDialog_description도 바꾸는 게 좋겠어요.

2023-07-27 13:29 UTC, krrong commented on android/app/src/main/java/com/now/naaga/presentation/beginadventure/LocationPermissionDialog.kt
> +    }
```
    private fun checkPermission() {
        return if (checkSelfPermission(requireContext(), ACCESS_COARSE_LOCATION) == PERMISSION_GRANTED) {
            setDescription(true)
        } else {
            setDescription(false)
        }
    }
```
이렇게 쓰면 더 간결해질 수도 있을 것 같아요! 🙃

2023-07-27 21:28 UTC, hyunji1203 requested changes
빅스 너무 고생 많았어요~ 기획대로 잘 구현해주셨네요ㅎㅎ
저 또한 빅스의 의견에 공감합니다!
개인적으로 Splash 화면에서 처리하는 건 어떨까 생각이 드는데 다른 사람들의 의견도 궁금합니다.

2023-07-27 21:28 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
> +            startActivity(Intent(this, OnAdventureActivity::class.java))
해당 목적지에서 Intent를 얻어오는 방식으로 수정하면 어떨까요?

2023-07-27 21:28 UTC, hyunji1203 commented on android/app/src/main/java/com/now/naaga/presentation/beginadventure/LocationPermissionDialog.kt
> +            return
`return` 문을 밖으로 빼줘도 좋을 것 같아요~

2023-07-28 08:33 UTC, hyunji1203 approved these changes

2023-07-28 08:34 UTC, merged