[AN] feat: OnAdventureActivity UI 변경사항 적용
woowacourse-teams/2023-naaga pull request #73
Opened 2023-07-27 02:17 UTC by krrong

## 📌 관련 이슈
- closed: #62 

## 🛠️ 작업 내용
UI 변경사항 적용

- [x] 서버로부터 받아온 목적지에 핀을 꽂는 기능 제거
- [x] 버튼 추가 및 재배치

## 🎯 리뷰 포인트
drawable, color를 추가했는데 네이밍이 적절한지 확인해주세요.  
추후 힌트를 사용했을 때 해당 위치에 마커를 찍어야 하기 때문에 addMarker 함수는 삭제하지 않고 남겨두었어요.  

## ⏳ 작업 시간
추정 시간: 1h  
실제 시간: 1h

2023-07-27 02:48 UTC, briandr97 requested changes
고생하셨습니다

2023-07-27 02:48 UTC, briandr97 commented on android/app/src/main/res/layout/activity_on_adventure.xml
> +            android:id="@+id/iv_onAdventure_drop"
포기하기를 drop으로 하신 이유가 있을까요?
개인적으로 giveup이 조금 더 직관적으로 느껴져서 여쭤봅니다!

2023-07-27 02:48 UTC, briandr97 commented on android/app/src/main/res/layout/activity_on_adventure.xml
>              android:layout_height="wrap_content"
현재 우측 세 개의 버튼 크기가 54 x 54 dp로 고정되어있고 남은 부분을 이 버튼이 차지하는 거죠? 좋습니다!!
다만 일관성을 위해 높이도 54dp 혹은 0dp + 옆버튼 위아래 제약으로 통일하는 것이 어떨까요?
한 줄에 있는 버튼이라 높이가 통일 되는 것이 일관성 있어 보일 것 같아서 말씀드립니다!

2023-07-27 02:48 UTC, briandr97 commented on android/app/src/main/res/layout/activity_on_adventure.xml
>              android:backgroundTint="@color/selector_main_gray_purple"
혹시 이렇게 해도 그림자 적용이 되나요? (다른 버튼도 이하 동문)
같은 경우에서 제가 안돼서 새로운 drawable을 만들고 background를 적용해서 여쭤봅니다!

2023-07-27 13:31 UTC, krrong commented on android/app/src/main/res/layout/activity_on_adventure.xml
> +            android:id="@+id/iv_onAdventure_drop"
give up은 복합단어라 애매하지 않을까하여 drop으로 진행했어요!
의도가 잘 느껴지지 않나요?

2023-07-27 13:40 UTC, krrong commented on android/app/src/main/res/layout/activity_on_adventure.xml
>              android:layout_height="wrap_content"
반영했어요 🙃

2023-07-27 21:06 UTC, hyunji1203 requested changes
크롱 고생 많았어요~
저희가 말했던 와이어프레임처럼 잘 만들어 주셨네요! 간단한 리뷰 몇가지 남겼으니 확인해주세요!

2023-07-27 21:06 UTC, hyunji1203 commented on android/app/src/main/res/layout/activity_on_adventure.xml
> +            android:id="@+id/tv_hint_count"
ID 네이밍에 `where`절을 추가해보는 건 어떨까요?

2023-07-27 21:06 UTC, hyunji1203 commented on android/app/src/main/res/values/strings.xml
> +    <string name="end_adventure">도착!</string>
strings를 보니 생각나는 건데, 나중에 저희 다같이 strings 안에 있는 아이들을 <!-- OnAdventureActivity --> 이런 식으로 액티비티 별로 주석달고 해당 액티비티에 쓰이는 애들을 한 눈에 보기 쉽게 배치하는 거로 바꾸는 거 어때요?

2023-07-28 03:47 UTC, briandr97 commented on android/app/src/main/res/layout/activity_on_adventure.xml
> +            android:id="@+id/iv_onAdventure_drop"
저는 포기하다는 의미에서 drop을 처음 만나봐서 생소했습니다.
실제 영어에서 drop을 포기하다는 의미로 많이 쓰나요?

2023-07-28 05:38 UTC, krrong commented on android/app/src/main/res/layout/activity_on_adventure.xml
> +            android:id="@+id/tv_hint_count"
반영했어요🙃

2023-07-28 05:38 UTC, krrong commented on android/app/src/main/res/values/strings.xml
> +    <string name="end_adventure">도착!</string>
좋은 생각이네요!🙃

2023-07-30 05:42 UTC, hyunji1203 approved these changes
👍

2023-07-30 05:42 UTC, merged